### ISSUE TITLE
pods in CreateContainerError after upgrading to aws-efs-csi-driver-2.4.4  [protocol family not supported]

### ISSUE THREAD

**Issue by lefterisALEX** [kubernetes-sigs/aws-efs-csi-driver#1023]
/kind bug

**What happened?**
After updating helm released to `aws-efs-csi-driver-2.4.4` we experienced an issue with a deployment which is using an EFS  pvc .

All pods of this deployment changed to `CreateContainerError` state.
![image](https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/24940221/62c9fcaa-4713-4a9b-b931-a038bf520e8d)
 
In the pod (kubectl get pods -oyaml) we see an error that protocol family not supported :

```
<output_omitted>
....
    state:
      waiting:
        message: 'failed to generate container "9111702e6730c8695a3a881cc7d83e0f33ec2d4bad33296162a6624a0bc931a5"
          spec: failed to generate spec: failed to stat "/var/lib/kubelet/pods/b55ce997-c55e-4c13-a4e9-0980b6eb43d7/volumes/kubernetes.io~csi/pvc-5982d54c-6531-4582-9aba-bb2c3f77cb80/mount":
          stat /var/lib/kubelet/pods/b55ce997-c55e-4c13-a4e9-0980b6eb43d7/volumes/kubernetes.io~csi/pvc-5982d54c-6531-4582-9aba-bb2c3f77cb80/mount:
          protocol family not supported'
        reason: CreateContainerError
...
<output_omitted>
```

and when we describe the pods:
```
<output_omitted>
...
Containers:
  reflector:
    Container ID:   containerd://7a0a321bedf01461fa8b74aaeb7a8cd6207b0341bee963a3f03f0fd2a56ef658
    Image:          artifacts.xxx.com/xyz/...
    Image ID:       artifacts.xxx.com/xyy...
    Port:           8000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CreateContainerError
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Tue, 30 May 2023 09:19:54 +0200
      Finished:     Wed, 31 May 2023 16:02:54 +0200
....
<output_omitted>
```

```
sh-4.2$ cat /var/run/efs/fs-07becbc574b70eb77.var.lib.kubelet.pods.b55ce997-c55e-4c13-a4e9-0980b6eb43d7.volumes.kubernetes.io~csi.pvc-5982d54c-6531-4582-9aba-bb2c3f77cb80.mount.20278
{"pid": 436, "cmd": ["/usr/bin/stunnel5", "/var/run/efs/stunnel-config.fs-07becbc574b70eb77.var.lib.kubelet.pods.b55ce997-c55e-4c13-a4e9-0980b6eb43d7.volumes.kubernetes.io~csi.pvc-5982d54c-6531-4582-9aba-bb2c3f77cb80.mount.20278"], "files": ["/var/run/efs/stunnel-config.fs-07becbc574b70eb77.var.lib.kubelet.pods.b55ce997-c55e-4c13-a4e9-0980b6eb43d7.volumes.kubernetes.io~csi.pvc-5982d54c-6531-4582-9aba-bb2c3f77cb80.mount.20278"], "mount_time": 1685431182.376611, "mountpoint": "/var/lib/kubelet/pods/b55ce997-c55e-4c13-a4e9-0980b6eb43d7/volumes/kubernetes.io~csi/pvc-5982d54c-6531-4582-9aba-bb2c3f77cb80/mount", "accessPoint": "fsap-03c604ea9be17c0c0", "mountStateDir": "fs-07becbc574b70eb77.var.lib.kubelet.pods.b55ce997-c55e-4c13-a4e9-0980b6eb43d7.volumes.kubernetes.io~csi.pvc-5982d54c-6531-4582-9aba-bb2c3f77cb80.mount.20278+", "commonName": "ip-10-28-104-112.eu-west-1.compute.internal", "region": "eu-west-1", "certificateCreationTime": "230531131942Z", "certificate": "/var/run/efs/fs-07becbc574b70eb77.var.lib.kubelet.pods.b55ce997-c55e-4c13-a4e9-0980b6eb43d7.volumes.kubernetes.io~csi.pvc-5982d54c-6531-4582-9aba-bb2c3f77cb80.mount.20278+/certificate.pem", "privateKey": "/etc/amazon/efs/privateKey.pem", "fsId": "fs-07becbc574b70eb77", "unmount_count": 0, "last_stunnel_check_time": 1685540533.6984453}sh-4.2$ 
```

**efs-csi-driver helm chart values**
https://pastebin.com/JvGTZKzs
**storage class**
https://pastebin.com/cfE7jqQ6
**deployment**
https://pastebin.com/9YVra51q
**pvc**
https://pastebin.com/Q4J5ZNRC

**What you expected to happen?**
Pods should keep running without issue.

**How to reproduce it (as minimally and precisely as possible)?**
Upgrade from `2.4.3` -> `2.4.4` , might reproduce it, but that issue might relevant with our configuration. 

**Anything else we need to know?**:
After we deleted the pods and rolled out new everything was working again 
**Environment**
- Kubernetes version : v1.23.17-eks-0a21954
- Driver version: aws-efs-csi-driver-2.4.4

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by lefterisALEX** [comment]
attached output of `log_collector.py`
[results.tgz](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/11617891/results.tgz)

**Comment by felixng1028** [comment]
same issue for me from 2.4.3 > 2.4.4

**Comment by mskanth972** [comment]
Hi @lefterisALEX, thanks for bringing here. Can you elaborate the configuration you had which is mentioned above?

**Comment by lefterisALEX** [comment]
hi @mskanth972  , thanks for the reply

I added some links in the original post with the deployment configuration, pvc, storage class and our helm chart values for efs-csi-driver.
Please let me know if something more is needed.

**Comment by mskanth972** [comment]
Hi @lefterisALEX , I don't see any error logs from what you pasted. Can you enable the debug logs and paste again?
https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting

**Comment by mskanth972** [comment]
And also can you install the latest helm version 2.4.5 and check whether the issue still persists?

**Comment by lefterisALEX** [comment]
unfortunately was not able to reproduce the issue again..isn't the log provided till now giving some hints to continue investigation?

**Comment by willthames** [comment]
We had this problem with the same helm chart bump, but the recent helm chart update using version 1.5.7 doesn't seem to have this problem

**Comment by mskanth972** [comment]
Closing the issue as the latest version(v1.5.7) is able to mitigate the problem. Feel free to open again if you have any questions regarding this.
/close
