### ISSUE TITLE
Remove non-standard label "app" in the Helm Chart

### ISSUE THREAD

**Issue by thetric** [kubernetes-sigs/aws-efs-csi-driver#1034]
/kind bug

**What happened?**
The Helm chart is deployed with the resources labelled with `app` instead of the [Kubernetes recommended label](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) `app.kubernetes.io/name`.

**What you expected to happen?**

The Helm chart makes use of the recommended label.

**How to reproduce it (as minimally and precisely as possible)?**

Deploy it.

**Anything else we need to know?**:

This may possibly be a breaking change as it might require a re-installation of the Helm chart because the `selector` `matchLabels` will change.

Same issue in the AWS EBS CSI driver: https://github.com/kubernetes-csi/external-snapshotter/issues/843

**Environment**
- Kubernetes version (use `kubectl version`): 1.27
- Driver version: 2.4.5

**Please also attach debug logs to help us better diagnose**

n/a

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by Ashley-wenyizha** [comment]
Hi @thetric

Thanks for bringing this to us, although currently efs-csi-driver is already using `app.kubernetes.io`

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/_helpers.tpl#L38

```
kubectl describe pod efs-csi-controller-fdd6d9d4b-slnn2 -n kube-system

Name:                 efs-csi-controller-fdd6d9d4b-slnn2
Namespace:            kube-system
Node:                 <none>
Labels:               app=efs-csi-controller
                      app.kubernetes.io/instance=aws-efs-csi-driver
                      app.kubernetes.io/name=aws-efs-csi-driver
```

**Comment by thetric** [comment]
Hi @Ashley-wenyizha, I would like to remove the "app"

**Comment by Kavinraja-G** [comment]
@Ashley-wenyizha Do we need to remove the label `app=efs-csi-controller` ? I hope that's being used by the selectors. Let me know if it's not needed, I can work on it. Thanks!
