### ISSUE TITLE
Run the controller in non-privileged mode

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-sigs/aws-efs-csi-driver#1050]
I saw these lines in the controller deployment

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/e9145582ebecf1055f11cb0ffbaf4bde393731fb/deploy/kubernetes/base/controller-deployment.yaml#L36-L37

Does it need to run as privileged? From my understanding the node plugin is the one that might be doing format/mount which are privileged storage operations but the controller would only be making cloud requests. Could we remove it safely?

**Comment by EshamAaqib** [comment]
I have the same question

**Comment by mskanth972** [comment]
Hi @mauriciopoppe, thanks for bringing here. Yes, it does not need to run as privileged, will raise a PR and mark in the next release.

**Comment by mskanth972** [comment]
The latest version 1.5.8 has the updated the security context.
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/CHANGELOG-1.x.md#v158

**Comment by mskanth972** [comment]
/close
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1055
