### ISSUE TITLE
AWS EFS CSI Driver - SecurityContext

### ISSUE THREAD

**Issue by quadrinho** [kubernetes-sigs/aws-efs-csi-driver#1066]
/kind bug

**What happened?**
We are installing aws-efs-csi-driver chart version 2.4.7 on EKS 1.25.

i use this securityContext (both for controller and node):

    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
         - ALL

The pods cannot start and we recieve this error:

`unable to create symlink from '/etc/amazon/efs' to '/var/amazon/efs': symlink /var/amazon/efs /etc/amazon/efs: permission denied`

**What you expected to happen?**

The application starts correctlu

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):  AWS EKS 1.25
- Driver version: Chart version 2.4.7 - Application version 1.5.8

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by mskanth972** [comment]
Hi @quadrinho, EFS CSI driver rely on certain operations that require root privileges, such as creating system-level resources, accessing specific directories. Can you change the `runAsNonRoot: true` to `false` and deploy the pods again to see if the error still persists.

**Comment by quadrinho** [comment]
> Hi @quadrinho, EFS CSI driver rely on certain operations that require root privileges, such as creating system-level resources, accessing specific directories. Can you change the `runAsNonRoot: true` to `false` and deploy the pods again to see if the error still persists.

Hello @mskanth972 ,

but i recieved this error on EKS 1.25:

Error creating: pods "efs-csi-controller-84f7c4d8f9-zbp7b" is forbidden: violates PodSecurity "restricted:v1.24": host namespaces (hostNetwork=true), hostPort (container "efs-plugin" uses hostPort 9909), allowPrivilegeEscalation != false (container "efs-plugin" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "efs-plugin", "csi-provisioner", "liveness-probe" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod must not set securityContext.runAsNonRoot=false), runAsUser=0 (pod must not set runAsUser=0), seccompProfile (pod or containers "efs-plugin", "csi-provisioner", "liveness-probe" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

It seems that in  kubernetes 1.25 some securityContext are forced.

How is this solved for efs csi driver?

Thanks!

**Comment by mskanth972** [comment]
Seeing the above error message, the admission profile `restricted:v1.24` a PSP(podsecuritypolicy) which is enforcing a set of security constraints which seems they are not compliant to `restricted:v1.24`. Can I have some context here why is this implemented? And also if possible can you share the driver file?

**Comment by quadrinho** [comment]
Hello @mskanth972 ,

This set of security constraints is created and configured by default from EKS 1.24.

What do you mean for driver file?

Thanks!

**Comment by mskanth972** [comment]
closing this as there is no further response. Please feel free to open if you are facing the issue still. Thanks again for bringing here.
/close
