### ISSUE TITLE
--delete-access-point-root-dir parameter not working as expected

### ISSUE THREAD

**Issue by rshiva777** [kubernetes-sigs/aws-efs-csi-driver#1077]
/kind bug

**What happened?**
I have deployed aws-efs-csi-driver with " **- --delete-access-point-root-dir=false**" flag to the efs-plugin deployment. So when i create an pvc, access point and pvc-content is created under efs data directory as expected. But when i delete the pvc, access point gets deleted, but the pvc-content is  under efs data directory is not getting deleted

**What you expected to happen?**
pvc-content under efs data directory should be deleted along with pvc and access point

**How to reproduce it (as minimally and precisely as possible)?**
Install aws-efs-csi-driver with " **- --delete-access-point-root-dir=false**" flag to the efs-plugin deployment

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.25
- Driver version: v1.5.8

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by rshiva777** [comment]
So,  as mentioned in the issue https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/411 i updated the  " **- --delete-access-point-root-dir=true**" flag to the efs-plugin deployment

Now, when i create an pvc, access point and pvc-content is created under efs data directory as expected. But when i delete the pvc, **access point is not deleted**, and  **pvc-content is under efs data directory is not getting deleted**

pv status is in released state, actually it should be deleted from cluster

when i check the logs, found there is some error as below

<img width="899" alt="image" src="https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/42074614/58338214-092e-4b72-8f88-47c76ba931e5">

**Comment by alexander-maksymiw-bl** [comment]
I had the same issue, IAM policies are according to documentation.
It looks like it's again working when downgrading the aws-efs-csi-driver to e.g. 1.5.4 (the version I was running before)
Could this be related to #1055 or #1001 ?

**Comment by RyanStan** [comment]
Hi @alexander-maksymiw-bl , thank you for bringing this to our attention. Yes, we need to re-add `privileged: true` to the controller Deployment, since the controller Pods perform a mount to the filesystem to delete the access point directory.
