### ISSUE TITLE
Add IAM policy needed and K8S RBAC needed by the container in the documentation. 

### ISSUE THREAD

**Issue by ipnextgen** [kubernetes-sigs/aws-efs-csi-driver#109]
In order to  be able to create a role for the pod and assign right IAM policies. Also maybe specify needed RBAC rights.

This will help to deploy from a terraform kubernetes provider or any other similar tool.

Thanks

**Comment by leakingtapan** [comment]
Since this driver is not talking to EFS for creating EFS filesystem yet. There is no actual IAM policy required at the moment.

See https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/82#issuecomment-529005188
