### ISSUE TITLE
EFS CSI Driver: Abandonware?

### ISSUE THREAD

**Issue by MurphyPuppy** [kubernetes-sigs/aws-efs-csi-driver#1099]
What's going on with the EFS CSI Driver? Has AWS laid off everybody that works on it? In the entirety of 2023 there have been a total of 5 commits (across 4 PRs) that modified the `pkg` directory: https://github.com/kubernetes-sigs/aws-efs-csi-driver/commits/master/pkg

One of those PRs is just a dependency update, so really there have been 3 PRs that modified the core EFS CSI Driver code in ALL OF 2023. Meanwhile, there are THIRTY FOUR PRs waiting to be merged.

Many of those PRs have no response, despite the authors basically begging the maintainers to review. Here's a few random examples it took me all of 60 seconds to find:

- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/689
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/926
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/963

Another example: here's an issue with a CRITICAL bug that's been open for WEEKS: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1085
Shouldn't this be priority number one? There's currently a bug in the driver **THAT MAY CAUSE IT TO DELETE ALL OF YOUR VOLUMES**!!!!!

The only official response is clueless, suggesting that a pod is deleting files it cannot have access to (hint for AWS: if it's not inside the folders with names like `pvc-5496e45b-7e0c-4e1d-8cfe-22d2d91ec010`, then the application pod CANNOT have deleted it, it MUST be the EFS CSI Driver).

If AWS doesn't have the resources to maintain this repo, I suggest they give it back to the community that obvious cares enough to submit dozens of PRs for AWS to ignore.
cc @wongma7
cc @Ashley-wenyizha
cc @mskanth972
cc @torredil

**Comment by Nuru** [comment]
I know +1 responses are discouraged for a good reason, but this is not a full +1 or else I would have just responded by adding a thumbs up. 

I support the request for additional resources to be applied to maintaining this project, which includes maintaining responses to PRs and issues. So 👍 to that.

Respectfully, I do not support the tone or language of this issue. While #1085 is serious, it is only 2 weeks old, a maintainer tried to reproduce the issue and could not, and posted that response 1 week ago, and is asking for more information to isolate the problem. All appropriate and while not lightning-fast, reasonably fast for an open source project. No one deserves to be berated for this.

Let's all play nice together.
