### ISSUE TITLE
support for arm64 nodes

### ISSUE THREAD

**Issue by zhouziyang** [kubernetes-sigs/aws-efs-csi-driver#111]
docker image and k8s manifest for arm64

**Comment by leakingtapan** [comment]
High level changes could include:
* cross compile the driver for arm
* build container image for arm
* install efs mount helper for arm
* install nfs client for arm

@zhouziyang could you give some some use case about why do you need to run the driver on arm platform?

**Comment by zhouziyang** [comment]
Hi @leakingtapan , I'm currently evaluating EKS Arm worker nodes (1.14); and efs csi seeming missing arm64 images. I created them myself ([docker hub] zhouziyang/aws-efs-csi-driver-arm64, zhouziyang/livenessprobe-arm64, zhouziyang/node-driver-registrar-arm64), and they worked as expected. 
It would be much more convenient if officially supported!
Thanks!

**Comment by tsarna** [comment]
#184 is indeed the same issue. Sorry, I think I searched for aarch64 and not arm64 so I missed this.

> could you give some some use case about why do you need to run the driver on arm platform?

The arm64 based m6g family VMs are now generally available, and price/performance is reportedly much better than m5. I think many people would want to use them in unless they have a specific need to stay on x86_64.

**Comment by leakingtapan** [comment]
I created a PR for arm64 and an arm64 image using similar command in #197. Since I don't have arm64 machine, mind testing using the image: chengpan/aws-efs-csi-driver:latest ?

**Comment by leakingtapan** [comment]
@tsarna

**Comment by paolofacchinetti** [comment]
Any update on a release for arm64 EC2 instances?

We want to try a c6g cluster, but the lack of support for arm64 means that we can't proceed in that direction.

**Comment by tsarna** [comment]
Sorry this took so long to test, I had some other blockers come up.

chengpan/aws-efs-csi-driver:latest seems to work just fine for me on a t4g instance. Sad to see that #197 was closed

**Comment by tsarna** [comment]
Thanks for working on this! It looks like the sticking point for #197 was the charts. Any chance the build portion could be committed and a separate issue split off for the charts portion?

Thanks!
