### ISSUE TITLE
Document fix on readme for private deployments

### ISSUE THREAD

**Issue by alext3500** [kubernetes-sigs/aws-efs-csi-driver#1110]
/kind bug

**What happened?**

Can't deploy the driver on a private network with all the endpoints required. The only image missing is the one related to 
Pulling image "public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar:v2.8.0-eks-1-27-3"

**What you expected to happen?**

By following the next set of instructions the deployment should be possible:

If you don't have outbound access to the Internet, add the following arguments.

--set sidecars.livenessProbe.image.repository=602401143452.dkr.ecr.region-code.amazonaws.com/eks/livenessprobe \
--set sidecars.node-driver-registrar.image.repository=602401143452.dkr.ecr.region-code.amazonaws.com/eks/csi-node-driver-registrar \
--set sidecars.csiProvisioner.image.repository=602401143452.dkr.ecr.region-code.amazonaws.com/eks/csi-provisioner

**How to reproduce it (as minimally and precisely as possible)?**

- Deploy a basic EKS with a node group attached to a private network.
- Attach endpoints to ECR, EKS, and any other necessary service on the private network.
- Use helm to deploy the driver following the instructions on the readme.

**Anything else we need to know?**:

Please replace this section of the document:

--set sidecars.node-driver-registrar.image.repository=602401143452.dkr.ecr.region-code.amazonaws.com/eks/csi-node-driver-registrar

with the next line:

--set sidecars.nodeDriverRegistrar.image.repository=602401143452.dkr.ecr.region-code.amazonaws.com/eks/csi-node-driver-registrar

Otherwise, the code doesn't take the new image definition, and it fails, loose sometime today, but learned some other stuff.

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by mskanth972** [comment]
Hi @alext3500, thanks for bringing here. Surely we will update the document which could benefit users using helm in private networks.
