### ISSUE TITLE
EKS add-on does not apply the deleteAccessPointRootDir flag

### ISSUE THREAD

**Issue by kordian2k** [kubernetes-sigs/aws-efs-csi-driver#1112]
/kind bug

**What happened?**
I added the EFS driver **add-on** to the EKS cluster with the following additional configuration setting:
`{"deleteAccessPointRootDir":true}`

However, the files associated to a PVC are not removed once the PVC is removed. It might be a deployment issue of the add-on since it does not happen if deployed via the helm chart.

**What you expected to happen?**
The files should be deleted if the flag is true and the corresponding PVC is removed.

**Anything else we need to know?**:
The `efs-plugin` container within the `efs-csi-controller` pod starts with the argument `--delete-access-point-root-dir=false`.
See also: https://github.com/aws/containers-roadmap/issues/2120

**Environment**
- Kubernetes version (use `kubectl version`): EKS: 1.27
- Driver version: EFS add-on: v1.5.8-eksbuild.1

**Comment by mskanth972** [comment]
Hi @kordian2k , thanks for bringing here. The latest release EFS CSI driver v1.6.0 which has this fix is not available yet in Addons due to some internal delays. But most probably it will be available by tomorrow.

**Comment by mskanth972** [comment]
v1.6.0 is into Addons. Please feel free to open the issue if you are facing it sill.
/close

**Comment by shandr** [comment]
Hey! I'm on v1.7.0-eksbuild.1 version, and it's still not working.

In the deployment, I see that - --delete-access-point-root-dir=false

Advanced configuration: {"deleteAccessPointRootDir":true}

**Comment by kordian2k** [comment]
I can confirm that the issue is still not resolved on 1.7.0.

**Comment by namanjoshi01** [comment]
Hello... I can confirm the same from my end. still facing this same issue. :(

**Comment by shuai-hao-hs** [comment]
+1 

We are having the same issue.

**Comment by cloudgrimm** [comment]
+1
