### ISSUE TITLE
Update example IAM Policy to use new managed IAM Policy and annotate Node SA

### ISSUE THREAD

**Issue by RyanStan** [kubernetes-sigs/aws-efs-csi-driver#1126]
**Is your feature request related to a problem?/Why is this needed**
1. Instead of referencing this [example IAM policy](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json) in our IAM Role creation instructions, we should tell users to use the new managed IAM Policy,  `AmazonEFSCSIDriverPolicy`.
2. We need to update our installation instructions to inform users that they have to annotate the Node Service Account in addition to the Controller Service Account. For example, see our add-on installation instructions, https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html.

**Comment by runningman84** [comment]
The new managed policy does not allow any other tags. This means the example in the values.yaml with tags for region or something like that will break everything...

**Comment by runningman84** [comment]
I also question the efs-csi userguide, why does the node(daemonset) need the same rights as the controller? This doesn't look right to me.
