### ISSUE TITLE
Timeouts binding to volume on same node

### ISSUE THREAD

**Issue by stefansedich** [kubernetes-sigs/aws-efs-csi-driver#115]
/kind bug

**What happened?**

Have started seeing the `timeout expired waiting for volumes to attach or mount for pod` error when a pod is being restarted and it lands on the same node after I let things sit for some time. This is only recent and it appears ever since I updated to the latest EKS AMI but I cannot prove that for sure at the moment (still digging deeper).

I can have a pod binding /foo using one PVC and even if I try start another pod with a totally seperate PVC mounting say /bah I am still seeing timeouts, if that pod moves to a node without any binds at all everything works.

My current fix is to terminate my nodes and upon coming back up binds will work for some time. For some reason everything will work fine at first I can restart pods hapilly but then if I come back a number of hours later the problem will appear again.

One more thing is looking at the efs-plugin container I see no more `NodePublishVolume` coming through since the initial binds when I last terminated my nodes to make things happy which is also odd. I attempted to restart the csi pods to no avail the only fix appears to be to bring up new nodes.

**What you expected to happen?**

For no mount timeouts to occur.

**How to reproduce it (as minimally and precisely as possible)?**

Create two PVC for the same EFS volume both for seperate folders in the root, create the pods on the same node, the second pod will fail to start due to timeouts.

**Anything else we need to know?**:

Running in EKS using latest AMI.

**Environment**
- Kubernetes version (use `kubectl version`): v1.14.9-eks-c0eccc
- Driver version: 0.2.0

**Comment by stefansedich** [comment]
Checked the node in question, saw some dangling nfs mounts which I unmounted, but even after that no mounts are working on the node in question.

**Comment by stefansedich** [comment]
Looking at the node where things are failing I am seeing the following in dmesg too, I am not overly familar with debugging this does anyone have any more tips?

```
[76828.295688] nfs: server 127.0.0.1 not responding, timed out
[76828.299542] nfs: server 127.0.0.1 not responding, timed out
[77018.755771] nfs: server 127.0.0.1 not responding, timed out
```

**Comment by leakingtapan** [comment]
From what you said, are you using `tls` for encryption in transit? And do you see the stunnel process in the  `efs-plugin` container of the `efs-csi-node-` pod?

**Comment by stefansedich** [comment]
@leakingtapan yes to TLS, I see no stunnels at all, if I manually jump into the csi pod on that node and run ` mount -t efs -o tls fs-xxx:/ /mnt/foo` it mounts without issue, however using a pod with a pvc I see nothing happen at all apart from a timeout.

I would expect that after rebooting the pod I could mount volumes again? what else could be broken here? I am seeing the same behavior on all our new clusters now and my old one is humming along without issue which is strange.

**Comment by stefansedich** [comment]
BTW this is the only output I see from a freshly restarted efs-plugin container on the node with issues:

```
I1228 19:13:07.681410       1 mount_linux.go:174] Cannot run systemd-run, assuming non-systemd OS
I1228 19:13:07.681478       1 mount_linux.go:175] systemd-run failed with: exit status 1
I1228 19:13:07.681489       1 mount_linux.go:176] systemd-run output: Failed to create bus connection: No such file or directory
I1228 19:13:07.681897       1 driver.go:83] Listening for connections on address: &net.UnixAddr{Name:"/csi/csi.sock", Net:"unix"}
I1228 19:13:08.683574       1 node.go:159] NodeGetInfo: called with args
```

**Comment by leakingtapan** [comment]
what’s the kubelet version of both worker nodes( working one and not working one)? Since mount operation is called from kubelet, do you have kubelet logs for both cases?

**Comment by stefansedich** [comment]
@leakingtapan both running v1.14.9-eks-c0eccc, I have logs just let me know what I need to provide, I looked at api logs and could not find anything initiallly odd. I am leaving this cluster running as is so would love to try work out what is wrong also happy to jump on a zoom or something to debug.

**Comment by leakingtapan** [comment]
Ah, I might know the reason why. This seems related to https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/100 which is the issue you reported a while back. And the fix is only in master branch for now

What's your PV specs that uses the same EFS volume for two PVCs?

**Comment by stefansedich** [comment]
This is definitely odd as I have no issues in another cluster. In this case
there is no binding at all to the folder, I can successfully bind it if I
pin my pod to node B but it never works pinned to node A.

Node A is unable to mount any EFS volume the efs-plugin never sees an
NodePublishVolume no matter what I do. If I terminate the instance and let
a new one come up things will be fine but after some time will stop working
again randomly.

I have tried restarting the csi pod to no avail the only fix is to
terminate the node.

**Comment by stefansedich** [comment]
To add too this is not a duplicate PVC or path it is a new test PV/PVC and
path that nothing is bound too anywhere.

**Comment by stefansedich** [comment]
@leakingtapan figured I would fire up the latest dev build on one of the bad nodes to see if that helps but it made no difference. Still no NodePublishVolume being called on the plugin, I take there is some bad state in kubelet somewhere causing this not to be called but so far I cannot find what it could be.

**Comment by leakingtapan** [comment]
I suspect it something to do with kubelet. But you also mentioned both are using `v1.14.8-eks-b8860f`, which is surprising. What's the AMI you are using? Have you find any differences between the two AMIs?

**Comment by stefansedich** [comment]
@leakingtapan all nodes are running the same AMI which is the latest `ami-0c13bb9cbfd007e56` in us-west-2. Also surprising to me, today I had to keep moving forward so brought up new nodes in all our clusters but it is likely to stop working again within a a day or so.

I will look at setting more verbose logging for kubelet so I can see if that gives me any more clues as right now I am all out of ideas.

**Comment by stefansedich** [comment]
@leakingtapan I cant explain it fully but our clusters were running 1 replica of opa wrongly, ever since I re-configured to run multiple instances over AZs I am yet to see this issue and the cluster has been solid with no EFS issues since the last time I brought up new nodes.

I am closing this off for now and will monitoring things going forward.
