### ISSUE TITLE
VolumeFailedDelete Mount Amazon EFS file systems cross-account from Amazon EKS

### ISSUE THREAD

**Issue by FedericoDelSaz** [kubernetes-sigs/aws-efs-csi-driver#1154]
I have developed "[Mount Amazon EFS file systems cross-account from Amazon EKS](https://aws.amazon.com/blogs/storage/mount-amazon-efs-file-systems-cross-account-from-amazon-eks/)" approach. it works on creating pvc, pv and accesspoint cross-accounts. Unfortunately, when we delete pvc, pv keeps on Released status.
In efs driver csi deployment appears next message: 

**controller.go:1007] error syncing volume "pvc-xxxxxxx": rpc error: code = Unauthenticated desc = Access Denied. Please ensure you have the right AWS permissions: Access denied                                                                                    │
│ efs-csi-controller-5c588cb8d-w6gs5 csi-provisioner I0925 10:07:25.035411       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-xxxxxx", UID:"xxxxxx", APIVersion:"v1", ResourceVersion:"398033728", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error │
│ : code = Unauthenticated desc = Access Denied. Please ensure you have the right AWS permissions: Access denied**

I have configured efs csi driver with delete-access-point-root-dir=true, but cross-accounts does not work. 

any idea?

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
parameters:
  provisioningMode: efs-ap
  fileSystemId: ${data.aws_efs_file_system.efs_eks[0].id}
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"

**Comment by FedericoDelSaz** [comment]
Warning  VolumeFailedDelete  3m59s (x13 over 22m)  efs.csi.aws.com_efs-csi-controller-59f778c9db-c9fmw_b97772fd-bf02-48a2-91a0-bb5c00ded189  rpc error: code = Internal desc = Coul │
│ d not mount "fs-0c4b55f47c728b173" at "/var/lib/csi/pv/fsap-09ecabbbad5aa0c16": mount failed: exit status 1                                                                           │
│ Mounting command: mount                                                                                                                                                               │
│ Mounting arguments: -t efs -o tls,iam fs-0c4b55f47c728b173 /var/lib/csi/pv/fsap-09ecabbbad5aa0c16                                                                                     │
│ Output: Failed to resolve "fs-0c4b55f47c728b173.efs.eu-central-1.amazonaws.com". The file system mount target ip address cannot be found, please pass mount target ip address via mou │
│ nt options.                                                                                                                                                                           │
│ The file system fs-0c4b55f47c728b173 is not found                                                                                                                                     │
│ Warning: config file does not have fips_mode_enabled item in section mount.. You should be able to find a new config file in the same folder as current config file /etc/amazon/efs/e │
│ fs-utils.conf. Consider update the new config file to latest config file. Use the default value [fips_mode_enabled = False].Warning: config file does not have fips_mode_enabled item │
│  in section mount.. You should be able to find a new config file in the same folder as current config file /etc/amazon/efs/efs-utils.conf. Consider update the new config file to lat │
│ est config file. Use the default value [fips_mode_enabled = False].

**Comment by FedericoDelSaz** [comment]
EKS = 1.24
efs driver: 
- Helm chart: 2.4.0
- diver: 1.5.3

**Comment by seanzatzdev-amazon** [comment]
@FedericoDelSaz Could you please provide DEBUG level logs? https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/troubleshooting/README.md

**Comment by FedericoDelSaz** [comment]
Hi,

Finally I found how to fix it. efs driver need DNS name on efs aws service, then we should configure network, therefore we have to create securiry group and add a tcp rule where allow inbound traffic on 2048 port.

Thanks

**Comment by FedericoDelSaz** [comment]
Fixed

**Comment by FedericoDelSaz** [comment]
Fixed
