### ISSUE TITLE
EKS add-on v1.7.0 does not apply the deleteAccessPointRootDir flag

### ISSUE THREAD

**Issue by kordian2k** [kubernetes-sigs/aws-efs-csi-driver#1171]
/kind bug

Seems to be a regression of https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1112

**Comment by mskanth972** [comment]
Hi @kordian2k, did you try EKS add-ons advanced configuration where we can configure parameters exposed via the add-on schema?
https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/

**Comment by kordian2k** [comment]
Hi @mskanth972, in my case the configuration of the add-on is:
`{"deleteAccessPointRootDir":true}`
This setting is also shown on the management console page of the add-on under _Advanced configuration_. In my case, the only change to the linked issue is the EKS version (1.28).

**Comment by luizm** [comment]
> Hi @kordian2k, did you try EKS add-ons advanced configuration where we can configure parameters exposed via the add-on schema?

I've tried it as well, it does not work

**Comment by shuai-hao-hs** [comment]
+1

we are having the same issue.

**Comment by kordian2k** [comment]
This has been fixed in 1.7.6.

Change the _advanced configuration_ of the EKS add-on to

`{"controller":{"deleteAccessPointRootDir":true}}`

See also https://github.com/aws/containers-roadmap/issues/2120
