### ISSUE TITLE
Use EFS in self-managed k8s cluster

### ISSUE THREAD

**Issue by fenwuyaoji** [kubernetes-sigs/aws-efs-csi-driver#1172]
Hi, I want to use efs in my self-managed k8s cluster, NOT the EKS, is it possible? 
I just follow the [manual](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/README.md#Installation) but facing some problems. 
I'm not sure this is the right place to ask for help, but I would appreciate for your help. 
versions:
k8s: 1.21.10
aws-efs-csi-driver: master branch

/triage support

**Comment by BeyondEvil** [comment]
Did you manage to get this working? If so, how exactly?
