### ISSUE TITLE
Use secret or env to pass AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in non-eks cluster to setup the driver permission

### ISSUE THREAD

**Issue by fenwuyaoji** [kubernetes-sigs/aws-efs-csi-driver#1174]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to deploy efs-csi to a self-managed k8s cluster. So far there is one way to grant driver IAM permission by using an IAM instance profile. However, I have no permission to set this profile so I wanna to use my AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as the credentials.

**Describe the solution you'd like in detail**
What I have tried is to pass AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as env parameters for containers efs-plugin and csi-provisioner (both in controller and ds), I'm not sure this is the right way to achieve my goal, but it works.

**Describe alternatives you've considered**
If I'm doing it the right way, I'd like to create PR and modify the chart files to support this feature. Or, make some changes to let csi support a secret like what IAM ARN is.

**Additional context**
No

**Comment by fenwuyaoji** [comment]
已收到您的邮件，我将及时查看并回复，谢谢                                                                                                                     王鑫

**Comment by mjj29** [comment]
Second this, I have to use a non-eks cluster but I want to use shared filesystems with the EFS driver (rather than just non-shared EBS filesystems)
