### ISSUE TITLE
Fails to connect to EFS when PVC uses non-default (kube-system) namespace

### ISSUE THREAD

**Issue by FrankieLi** [kubernetes-sigs/aws-efs-csi-driver#119]
/kind bug

**What happened?**

When I try to use a PVC created in namespaces other than where `aws-efs-csi-driver` is installed (kube-system), only *one and only one pod* may successfully connect to the EFS volume. The remaining fails with mount error:

-------Error starts-------------------
```
  Warning  FailedMount  48s                  kubelet, ip-192-168-65-155.us-east-2.compute.internal  Unable to mount volumes for pod "app2_bob(de568a47-3122-11ea-a4ac-0630bc32aff6)": timeout expired waiting for volumes to attach or mount for pod "bob"/"app2". list of unmounted volumes=[persistent-storage]. list of unattached volumes=[persistent-storage default-token-v9sdc]
  Warning  FailedMount  39s (x9 over 2m50s)  kubelet, ip-192-168-65-155.us-east-2.compute.internal  MountVolume.SetUp failed for volume "efs-pv" : rpc error: code = Internal desc = Could not mount "fs-8d9789f4:/" at "/var/lib/kubelet/pods/de568a47-3122-11ea-a4ac-0630bc32aff6/volumes/kubernetes.io~csi/efs-pv/mount": mount failed: exit status 1
```
-------Error starts-------------------

**What you expected to happen?**

I expected multiple nodes to be able to use the same PVC, as shown in the demo in the directory, `examples/kubernetes/multiple_pods/specs`.

**How to reproduce it (as minimally and precisely as possible)?**

1. Go to `examples/kubernetes/multiple_pods/specs`
2. Insert `namespace: bob` (or any namespace) into the metadata of `pod1.yaml`, `pod2.yaml`, and `claim.yaml`.
3. Run through the normal example as usual.
4. Only one of the two pods would succeed in starting. The other will fail to mount the EFS drive.

**Anything else we need to know?**:

aws-efs-csi-driver was installed in the `kube-system` namespace.

**Environment**
- Kubernetes version (use `kubectl version`): v1.16.2
- Driver version: v0.2.0
(Installed with kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master")

**Comment by leakingtapan** [comment]
Seems it times out during the mount, do you have the log for the `efs-csi-node-xxx`? Since it is deployed as daemonset, you need to find the log on which node the application pod is scheduled to .

And does the same setup works for you with `default` namespace?

**Comment by FrankieLi** [comment]
Found the problem. It seems that my system was spilling over into a different availability zone, and the EFS was not setup for both zones. Thank you!
