### ISSUE TITLE
vulnerabilities in v2.4.0 reported by Trivy

### ISSUE THREAD

**Issue by serajushsalekin** [kubernetes-sigs/aws-efs-csi-driver#1219]
After scanning the efs-provisoner I found the following securities issue that related to golang package.

Resource  | Resource Path | Type | Version|Format
------------- | ------------- | ------------- | ------------- | ------------- 
github.com/aws/aws-sdk-go | efs-provisioner | PACKAGE | v1.25.8 | go
github.com/gogo/protobuf|efs-provisioner|PACKAGE|v1.2.2-0.20190723190241-65acae22fc9d|go
github.com/miekg/dns|efs-provisioner|PACKAGE|v1.1.22|go
github.com/prometheus/client_golang|efs-provisioner|PACKAGE|v1.1.0|go
golang.org/x/crypto|efs-provisioner|PACKAGE|v0.0.0-20191002192127-34f69633bfdc|go
golang.org/x/net|efs-provisioner|PACKAGE|v0.0.0-20190923162816-aa69164e4478|go
golang.org/x/sys|efs-provisioner|PACKAGE|v0.0.0-20190924154521-2837fb4f24fe|go
golang.org/x/text|efs-provisioner|PACKAGE|v0.3.2|go
gopkg.in/yaml.v2|efs-provisioner|PACKAGE|v2.2.2|go
k8s.io/apimachinery|efs-provisioner|PACKAGE|v0.0.0-20190913080033-27d36303b655|go
k8s.io/client-go|efs-provisioner|PACKAGE|v0.0.0-20191003000419-f68efa97b39e|go

**Comment by mskanth972** [comment]
Hi @serajushsalekin, we have the latest version helm v2.5.2. Can you try using that version.

**Comment by mskanth972** [comment]
Closing the issue as the latest image has no CVEs, please feel free to open if you are facing the issue still
