### ISSUE TITLE
efs csi driver doesn't work with pod having tolerations

### ISSUE THREAD

**Issue by infa-ssaurabh** [kubernetes-sigs/aws-efs-csi-driver#122]
/kind bug

**What happened?**
When pod doesn't have tolerations, the efs is mounted successfully as pvc. But when we have tolerations in pod(for specific reasons) the pod goes in "ContainerCreating" status with error:
driver name efs.csi.aws.com not found in the list of registered CSI drivers

**What you expected to happen?**
Pod should run as expected with efs mounted as pvc when tolerations are added.

**How to reproduce it (as minimally and precisely as possible)?**
add tolerations to pod manifest and it will go in "ContainerCreating" status.

**Anything else we need to know?**: NO

**Environment**
- Kubernetes version (use `kubectl version`):
Client: GitVersion:"v1.15.0"
Server: GitVersion:"v1.14.9-eks-c0eccc
- Driver version:
v0.2.0

**Comment by mikegirard** [comment]
Ran into this same issue. It has to do with the daemonset that is created for the driver:

```
NAME           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
aws-node       7         7         7       7            7           <none>                        561d
ebs-csi-node   7         7         7       7            7           beta.kubernetes.io/os=linux   6d3h
efs-csi-node   5         5         5       5            5           beta.kubernetes.io/os=linux   3h21m
fluentd        5         5         5       5            5           <none>                        372d
kube-proxy     7         7         7       7            7           <none>                        561d
```

Notice that the ebs driver started on all nodes, even though 2 of them have taints on them (used for things like jenkins only) whereas the efs DSet only hits the untainted nodes.

**Comment by mikegirard** [comment]
Workaround until DaemonSet is updated (given standard instructions used with README):

```
$ kubectl edit daemonset efs-csi-node -n kube-system

... scroll down to the tolerations area and modify....
    tolerations:
        - operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
```

and save that. You should see the daemonset update to show a full count of nodes.

**Comment by leakingtapan** [comment]
This is a bug recently fixed on EBS csi driver. Please file a patch for fixing efs driver. Thx

**Comment by mikegirard** [comment]
Thanks @leakingtapan. I had just installed the EFS driver and 'recently' installed the EBS csi driver - but apparently not recently enough.

Re-ran `kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"`  and added that (along with efs version) to my operations stack documentation around checking for upgrades.

**Comment by mach-kernel** [comment]
If you're running a cluster with mixed Fargate and EC2 instances, edit the `efs-csi-node` affinity set to avoid Fargate pods (otherwise, you will get a bunch of noise):

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: eks.amazonaws.com/compute-type
              operator: NotIn
              values:
                - fargate
```
