### ISSUE TITLE
Improve securityContext implementation (Capabilities\Seccomp) 

### ISSUE THREAD

**Issue by YogevMaty** [kubernetes-sigs/aws-efs-csi-driver#1224]
What is this PR about? / Why do we need it?

Implements default securityContext Capabilities and Seccomp profiles for the node pod and all containers (including sidecar containers). Also add the option to manage securityContext Capabilities and Seccomp profiles in the helm chart

**Comment by arnavgup1** [comment]
@YogevMaty Was this supposed to be a PR? Can you open a PR with the changes you implemented?
