### ISSUE TITLE
Add JSON logging via "loggingFormat"

### ISSUE THREAD

**Issue by erulabs** [kubernetes-sigs/aws-efs-csi-driver#1232]
**Is your feature request related to a problem?/Why is this needed**
The EFS CSI driver is extremely verbose and does not log in a digestible format. As a critical system component, it's quite frustrating to not be able to simple query for error level logs. The default logging format is not easily parsable.

**Describe the solution you'd like in detail**
I'd love it if this driver also supported "loggingFormat" similar to how the EBS-CSI driver does: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L184C7-L184C7

**Describe alternatives you've considered**
I've tried parsing the go-logr format and I wanted to cry 😭 

**Additional context**
Thank you!

**Comment by tormodmacleod** [comment]
can this perhaps be re-opened or reconsidered? 1 year on the issue is no less relevant
