### ISSUE TITLE
Values reported for kubelet_volume_stats_capacity_bytes are VERY wrong

### ISSUE THREAD

**Issue by michaelniemand** [kubernetes-sigs/aws-efs-csi-driver#1242]
/kind bug

**What did you do**

opted in to volume metrics by setting the flag `--vol-metrics-opt-in` to `true` and queried metric `kubelet_volume_stats_capacity_bytes`

**What you expected to happen?**

I expected reported metrics to be truthful. `kubelet_volume_stats_used_bytes` seems to be correct, `kubelet_volume_stats_capacity_bytes` is certainly wrong though (9 Exabytes displayed vs 5Gi actual in my case)

**How to reproduce it (as minimally and precisely as possible)?**

1. have any sort of efs volume
2. query the metrics endpoint of the driver for the value of `kubelet_volume_stats_capacity_bytes`
3. compare with actual values

**Anything else we need to know?**:

other flags are: 

```
        - --endpoint=$(CSI_ENDPOINT)
        - --logtostderr
        - --v=2
        - --vol-metrics-opt-in=true
        - --vol-metrics-refresh-period=240
        - --vol-metrics-fs-rate-limit=5
```

**Environment**
- Kubernetes version v1.28.4-eks-8cb36c9
- Driver versions:
   -  csi-node-driver-registrar:v2.8.0-eks-1-27-3
   - aws-efs-csi-driver:v1.7.1
   - csi-provisioner:v3.5.0-eks-1-27-3

**Please also attach debug logs to help us better diagnose**
No logs but screenshots:
the sizes of volumes as defined: (5Gi and 1 Gi):
<img width="1472" alt="Screenshot 2024-01-11 at 10 18 43" src="https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/85166523/27190c53-4b8e-4618-ad57-adc3b18fe278">
Reported volumes sizes are either 9EB or 0:
<img width="1716" alt="Screenshot 2024-01-11 at 10 16 13" src="https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/85166523/e607cddb-02e6-4b64-b52e-33d65eaec15b">

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by OverStruck** [comment]
this is expected, kubernetes requires setting a size, but EFS grows dynamically, if once you hit 1GB you can keep adding data, hence the actual limit is huge as reported, unlike EBS where size is used to give you a volume of a specific size, in other words, this doesn't apply to EBS but still has to be added to comply w/ k8s spec
