### ISSUE TITLE
When mounting two EFS volumes in one deployment, Kubernetes pods get stuck in the Init:0/1 state. 

### ISSUE THREAD

**Issue by lbteam001** [kubernetes-sigs/aws-efs-csi-driver#1243]
The pod becomes stuck in the Init:0/1 state when I try to mount two EFS Volumes in a single deployment. But the Pod starts when I mount just one volume.
I have deployed the Latest version of efs-csi-driver in EKS cluster.

**Comment by gkalwig** [comment]
What version of K8s do you have? Maybe your error is the same as this one #1245  ? I also had deployments with 2 EFs installed on node where sometimes error occured.

**Comment by lbteam001** [comment]
Hi @gkalwig 
K8s Version= 1.28
Actually, neither the app pod nor the efs pod's logs include any errors. The following warning appears when I describe the app pod:
**Error: NodeExpandVolume.NodeExpandVolume failed for volume "pv-logs" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/efs.csi.aws.com to not support node expansion**

**Comment by srujankujmar** [comment]
Even I have faced the same issue 

`Warning  FailedMount  2m58s (x25 over 4m34s)  kubelet            MountVolume.Setup failed while expanding volume for volume "yggdrasil-inbound-pv" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/efs.csi.aws.com to not support node expansion`

Could you please let us know what is the exact issue and what is the ETA for this?

**Comment by mskanth972** [comment]
NodeExpandVolume is a feature, which certain CSI drivers support, which allows customers to expand their volumes. [We do not support this](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/41ddd6ff42f80765bd0efd5a863fc12f69d6e975/pkg/driver/node.go#L285) because it doesn't make sense in our case (EFS doesn't have a size limit). [And we have that listed in our documentation here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/#features).
I think Kubernetes will call this feature if a user tries editing the specification of their Persistent Volume object to increase the size and correct action is taken because it observes that we cannot expand volumes with our driver, and it logs this warning.

**Comment by srujankujmar** [comment]
we havent modified 

> NodeExpandVolume is a feature, which certain CSI drivers support, which allows customers to expand their volumes. [We do not support this](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/41ddd6ff42f80765bd0efd5a863fc12f69d6e975/pkg/driver/node.go#L285) because it doesn't make sense in our case (EFS doesn't have a size limit). [And we have that listed in our documentation here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/#features). I think Kubernetes will call this feature if a user tries editing the specification of their Persistent Volume object to increase the size and correct action is taken because it observes that we cannot expand volumes with our driver, and it logs this warning.

We haven't modified the size of our pv

**Comment by srujankujmar** [comment]
> we havent modified
> 
> > NodeExpandVolume is a feature, which certain CSI drivers support, which allows customers to expand their volumes. [We do not support this](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/41ddd6ff42f80765bd0efd5a863fc12f69d6e975/pkg/driver/node.go#L285) because it doesn't make sense in our case (EFS doesn't have a size limit). [And we have that listed in our documentation here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/#features). I think Kubernetes will call this feature if a user tries editing the specification of their Persistent Volume object to increase the size and correct action is taken because it observes that we cannot expand volumes with our driver, and it logs this warning.
> 
> We haven't modified the size of our pv

**Comment by lbteam001** [comment]
Hi  mskanth972,
Here we are just mounting two EFS Volumes in a single deployment, haven't modified the size of our pv. When we are mounting only one Volume then it's working cool.
