### ISSUE TITLE
Support Pod Identity

### ISSUE THREAD

**Issue by psivananda** [kubernetes-sigs/aws-efs-csi-driver#1257]
/kind bug

**What happened?**
Configured Controller to use Pod Identities an alternative to IRSA

**What you expected to happen?**
Expect the controller to get credentials from the Pod Identity Agent (DaemonSet)

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:
need to update go SDK module to supported versions - https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html 

**Environment**
Kubernetes version (use kubectl version): EKS 1.28
Driver version: v1.7.4-eksbuild.1

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by Indresh-Prakash** [comment]
Do we have any ETA on the above feature?

**Comment by asininemonkey** [comment]
Also waiting on #1254 to be merged.

**Comment by cwichka** [comment]
Same here, waiting for https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1254 to be merged

**Comment by seanzatzdev-amazon** [comment]
Hello all, thank you for bringing this to our attention. We are working on getting https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1254 merged currently

**Comment by arnavgup1** [comment]
Hi folks, we have merged #1254. We will be tagging and releasing a new version of the efs-csi-driver with Pod Identity this week.
