### ISSUE TITLE
Redirect EFS mount logs to stdout

### ISSUE THREAD

**Issue by adammw** [kubernetes-sigs/aws-efs-csi-driver#126]
**Is your feature request related to a problem?/Why is this needed**
EFS mount helper primarily logs to disk at `/var/log/amazon/efs/` inside the container, making it difficult to view.

/feature

**Describe the solution you'd like in detail**
The default entrypoint of the efs plugin docker container should watch/tail for any files in that directory and copy the output to stdout to be picked up by Kubernetes-managed logs.

**Comment by leakingtapan** [comment]
I brought this up with efs team and they should fix this on the efs mounter helper side.

**Comment by jqmichael** [comment]
I think the work-around below isn't too bad an option. And it also keeps the driver plugin log self-contained. The efs-plugin log output is already pretty long. 

```
kubectl exec $(kubectl get po -l app=efs-csi-node -n kube-system -o jsonpath='{.items[0].metadata.name}') -n kube-system -it cat /var/log/amazon/efs/mount.log
```

What do you think? @adammw
