### ISSUE TITLE
v1.7.2 version has memory leakage issues

### ISSUE THREAD

**Issue by A10ss** [kubernetes-sigs/aws-efs-csi-driver#1261]
/kind bug

**What happened?**
Our production environments use the EFS-CSI-driver(chart version: v2.5.2), and we found that the EFS-CSI-driver pod's efs-plugin container was OOM killed many times.

**What you expected to happen?**
When the EFS-CSI-driver's efs-plugin was OOM killed, our application pods were pending, and the error is `Unable to attach or mount volumes`, and then all the pods on this node will throw this exception, we have to re-schedule these pods to another node.
Then we scaled up the efs-plugin's memory resource to 1Gi(from 512Mi), and they still OOM.

**How to reproduce it (as minimally and precisely as possible)?**
Just create a pod that uses EFS PVC, then write logs to the PVC, after a few hours, the EFS-CSI-driver's efs-plugin container will be OOM killed.
**Anything else we need to know?**:
Here are some monitoring charts:
the EFS-CSI-driver's pod memory usage.
<img width="1200" alt="image" src="https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/48682440/8331f823-fe0c-4e2f-ad43-0e2f468f7192">
the efs-plugin OOM killed:
<img width="709" alt="image" src="https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/48682440/23f93194-f135-4077-8433-96046c68f529">
<img width="1124" alt="image" src="https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/48682440/55e837d3-afff-4d9e-bbad-03fd9506734e">

**Environment**
- Kubernetes version (use `kubectl version`): 1.23.5
- Driver version: 
   chart version: v2.5.3
   efs-plugin version: v1.7.2

**Please also attach debug logs to help us better diagnose**
the efs-plugin's crash log:
```shell
❯ kubectl logs efs-csi-node-ccngn -c efs-plugin -n kube-system --previous
I0130 01:47:31.409280       1 config_dir.go:88] Creating symlink from '/etc/amazon/efs' to '/var/amazon/efs'
I0130 01:47:31.410059       1 metadata.go:63] getting MetadataService...
I0130 01:47:34.585970       1 metadata.go:68] retrieving metadata from EC2 metadata service
I0130 01:47:34.586796       1 driver.go:140] Did not find any input tags.
I0130 01:47:34.586967       1 driver.go:113] Registering Node Server
I0130 01:47:34.586976       1 driver.go:115] Registering Controller Server
I0130 01:47:34.586983       1 driver.go:118] Starting efs-utils watchdog
I0130 01:47:34.587043       1 efs_watch_dog.go:221] Skip copying /etc/amazon/efs/efs-utils.conf since it exists already
I0130 01:47:34.587052       1 efs_watch_dog.go:221] Skip copying /etc/amazon/efs/efs-utils.crt since it exists already
I0130 01:47:34.587265       1 driver.go:124] Starting reaper
I0130 01:47:34.587274       1 driver.go:127] Listening for connections on address: &net.UnixAddr{Name:"/csi/csi.sock", Net:"unix"}
W0130 05:03:59.506031       1 reaper.go:105] reaper: failed to wait for process &{737 20 90 737 737 stunnel5}: no child processes
W0130 05:03:59.605544       1 reaper.go:105] reaper: failed to wait for process &{737 20 90 737 737 stunnel5}: no child processes
W0130 05:04:00.108145       1 reaper.go:105] reaper: failed to wait for process &{737 20 90 737 737 stunnel5}: no child processes
W0130 05:04:01.907699       1 reaper.go:105] reaper: failed to wait for process &{737 20 90 737 737 stunnel5}: no child processes
W0130 05:07:01.047432       1 reaper.go:105] reaper: failed to wait for process &{737 20 90 737 737 stunnel5}: no child processes
W0130 05:07:01.107666       1 reaper.go:105] reaper: failed to wait for process &{737 20 90 737 737 stunnel5}: no child processes
```

**Comment by mskanth972** [comment]
Hi @A10ss , can you confirm if the `vol-metrics-opt-in` parameter is enabled in the daemonset, because 
Turning on the `vol-metrics-opt-in` parameter initiates the collection of inode and disk usage information which is updated in the README. And also we recommend to upgrade the version of driver to v1.7.4 which has the side cars updated to mitigate many CVEs.

**Comment by jiangfwa** [comment]
Hi, @mskanth972 , we didn't enable `vol-metrics-opt-in` in daemonset. But the memory needs more than 1GB, very scary.

```yaml
args:
  - '--endpoint=$(CSI_ENDPOINT)'
  - '--logtostderr'
  - '--v=2'
  - '--vol-metrics-opt-in=false'
  - '--vol-metrics-refresh-period=240'
  - '--vol-metrics-fs-rate-limit=5'
```

**Comment by mskanth972** [comment]
Closing the issue as the same problem is being tracked [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1160)
