### ISSUE TITLE
NodeUnpublishVolume error after a pod is force deleted

### ISSUE THREAD

**Issue by sba30** [kubernetes-sigs/aws-efs-csi-driver#1262]
/kind bug

**What happened?**
After a pod has been force deleted, We see system load very high on the eks worker. And in the efs-csi-node logs we see this error below referencing the pod which does not exist anymore.

`NodeUnpublishVolume: called with args volume_id:"fs-xxxxxx::fsap-xxxxx" target_path:"/var/lib/kubelet/pods/xyxxyz/volumes/kubernetes.io~csi/abc-efs/mount"`

**What you expected to happen?**
Load not increase and this NodeUnpublishVolume not in the logs

**How to reproduce it (as minimally and precisely as possible)?**
Force delete a pod which uses a pvc, and review the esf-csi-nodes

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
v1.26.7-eks-8ccc7ba
- Driver version:
aws-efs-csi-driver:v1.5.6
**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by seanzatzdev-amazon** [comment]
Hello @sba30 could you please provide the full debug logs following [this](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting) as well as let us know how you have installed the driver?

**Comment by sba30** [comment]
Hi, so on review off this issue https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/112, we were able to get past the issue, by exec'ing onto the pod reporting the issue, the UID of the pod seems to be an old pod and not the active one, so when we ran 

`unmount -l <target path>`

then the NodeUnpublishVolume does not appear in the efs logs anymore and the load comes down.

unsure if theres a permanent fix here or not, but this workaround has worked for us.
