### ISSUE TITLE
Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.

### ISSUE THREAD

**Issue by manuonda** [kubernetes-sigs/aws-efs-csi-driver#1268]
/kind bug

**What happened?**

# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.

**What you expected to happen?**
Create file.
**How to reproduce it (as minimally and precisely as possible)?**
Execute command : kubectl kustomize \
    "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr/?ref=release-1.7" > private-ecr-driver.yaml

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde

- Driver version:

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by seanzatzdev-amazon** [comment]
Hi @manuonda , I was able to replicate the warning message, although the file creates successfully for me. Could you clarify the issue?
```
[zatzsea@dev-dsk-zatzsea-1a-5f552df4 csi-driver-1268]$ kubectl kustomize "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr/?ref=release-1.7" > private-ecr-driver.yaml
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
[zatzsea@dev-dsk-zatzsea-1a-5f552df4 csi-driver-1268]$ ls
private-ecr-driver.yaml
[zatzsea@dev-dsk-zatzsea-1a-5f552df4 csi-driver-1268]$ cat private-ecr-driver.yaml 
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  name: efs-csi-controller-sa
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  name: efs-csi-node-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
...
```
