### ISSUE TITLE
efs startpuptaint not works correctly

### ISSUE THREAD

**Issue by Mieszko96** [kubernetes-sigs/aws-efs-csi-driver#1273]
/kind bug

**What happened?**
i saw new feature was requested in this ticket
https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1069

I have infrastructure with karpenter as autoscale tool. And we have problem with installing apps using EFS on brand new node.
I added startupTaint to prevent it, but from my POV it looks like is deleting this taint to fast

i made some more steps how i testing this in karpenter ticket https://github.com/aws/karpenter-provider-aws/issues/5691

but it seems to be a problem on EFS side. 

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version 1.2.7
- Driver version: 2.5.5 helmchart

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by mskanth972** [comment]
We released a new version(2.0.6) which has the Fix to GitHub and related [PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1287). ECD for the Addons will be 07/31.
