### ISSUE TITLE
Livenessprobe ignores stderrthreshold flag

### ISSUE THREAD

**Issue by chmielas** [kubernetes-sigs/aws-efs-csi-driver#128]
/kind bug

**What happened?**
Not able to decrease log level for livenessprobe. 
I want to decrease log level for livenessprobe, but it seems that argument `stderrthreshold` is ignored in `DeamonSet` Definiton. After definition update I still see logs on `info` level :

```
I0131 08:33:42.730485       1 main.go:71] Health check succeeded
I0131 08:33:44.730166       1 main.go:53] Sending probe request to CSI driver "efs.csi.aws.com"
I0131 08:33:44.730497       1 main.go:71] Health check succeeded
I0131 08:33:46.730098       1 main.go:53] Sending probe request to CSI driver "efs.csi.aws.com"
I0131 08:33:46.730404       1 main.go:71] Health check succeeded
I0131 08:33:48.730168       1 main.go:53] Sending probe request to CSI driver "efs.csi.aws.com"
I0131 08:33:48.730508       1 main.go:71] Health check succeeded
I0131 08:33:50.730125       1 main.go:53] Sending probe request to CSI driver "efs.csi.aws.com"
I0131 08:33:50.730467       1 main.go:71] Health check succeeded
I0131 08:33:52.730125       1 main.go:53] Sending probe request to CSI driver "efs.csi.aws.com"
I0131 08:33:52.730462       1 main.go:71] Health check succeeded
I0131 08:33:54.730176       1 main.go:53] Sending probe request to CSI driver "efs.csi.aws.com"
I0131 08:33:54.730499       1 main.go:71] Health check succeeded
I0131 08:33:56.730123       1 main.go:53] Sending probe request to CSI driver "efs.csi.aws.com"
I0131 08:33:56.730428       1 main.go:71] Health check succeeded
I0131 08:33:58.730153       1 main.go:53] Sending probe request to CSI driver "efs.csi.aws.com"
I0131 08:33:58.730508       1 main.go:71] Health check succeeded
I0131 08:34:00.730135       1 main.go:53] Sending probe request to CSI driver "efs.csi.aws.com"
I0131 08:34:00.730462       1 main.go:71] Health check succeeded
```

**What you expected to happen?**
To be able to decrease log level from info to error or warning

**How to reproduce it (as minimally and precisely as possible)?**

Update DeamonSet with the following definition

```
- name: liveness-probe
  imagePullPolicy: Always
  image: quay.io/k8scsi/livenessprobe:v1.1.0
  args:
    - --csi-address=/csi/csi.sock
    - --health-port=9809
    - --logtostderr=true
    - -stderrthreshold=error
  volumeMounts:
    - mountPath: /csi
      name: plugin-dir
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
1.14.9-eks
- Driver version:
1.1.0

**Comment by leakingtapan** [comment]
Have you tired reducing the log verbosity using `- --v=4`, something like:

```
- name: liveness-probe
  imagePullPolicy: Always
  image: quay.io/k8scsi/livenessprobe:v1.1.0
  args:
    - --csi-address=/csi/csi.sock
    - --health-port=9809
    - --v=4
  volumeMounts:
    - mountPath: /csi
      name: plugin-dir
```

**Comment by chmielas** [comment]
I tried also with verbosity `- --v=4 ` but log level still remains on the same level.

**Comment by radityasurya** [comment]
+1

Would be good to disable the logs too since it's flooding the logs

**Comment by guitarrapc** [comment]
helm chart also not specifying verbose level for liveness-probe.
It's happy if Values.yaml expose verbosity.
Temporally I'm using custom chart.

> https://github.com/guitarrapc/charts/commit/2d8f11d0e75c983b3710239dc950a48f1679dc7a

**Comment by guitarrapc** [comment]
There's livenessprobe v2.0.0 released and health check begin/success logs are suppressed om default.

> https://github.com/kubernetes-csi/livenessprobe/releases/tag/v2.0.0

if you are using helm, just upgrade sidecar container image version from v1.1.0 to v2.0.0 will address this issue.

> original values.yaml: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/51d19a433dcfc47fbb7b7a0e1c8ff6ab98ce87e9/helm/values.yaml#L15

```yaml
# values.yaml
sidecars:
  livenessProbeImage:
    repository: quay.io/k8scsi/livenessprobe
    tag: "v2.0.0" # <- changed!
```

**Comment by chmielas** [comment]
Thank you, after upgrade yo v2.0.0 issue is fixed.
