### ISSUE TITLE
aws-efs-csi-driver 1.7.6 image is still not avaialble but helm chart 2.5.6 is already released

### ISSUE THREAD

**Issue by sc-yan** [kubernetes-sigs/aws-efs-csi-driver#1282]
/kind bug

**What happened?**
https://gallery.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver  v1.7.6 is not available.
however, helm [chart](https://artifacthub.io/packages/helm/aws-efs-csi-driver/aws-efs-csi-driver) 2.5.6, which is using v1.7.6 image, has been released.
<img width="707" alt="image" src="https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/39505577/2c0f71fa-dcd6-4f7c-855b-69f6b33a7f6c">

**What you expected to happen?**
image should be available.
**How to reproduce it (as minimally and precisely as possible)?**
```
docker pull public.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver:v1.7.6                                                                                                                             
Error response from daemon: manifest for public.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver:v1.7.6 not found: manifest unknown: Requested image not found
```
**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by drzero42** [comment]
It appears that this issue has appeared again. v2.0.1 does not exist on Docker Hub. v2.0.0 is the latest.

**Comment by IamTamika** [comment]
> It appears that this issue has appeared again. v2.0.1 does not exist on Docker Hub. v2
I'm experiencing the same issue
![image](https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/77031428/7a2c5584-a690-4ea3-b0e3-325e64eb6c19)

**Comment by drzero42** [comment]
@sc-yan You are pulling from public.ecr.aws, but the Helm chart is referencing the image om Docker Hub, where it is not available.

![image](https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/1853961/b92a22bc-a463-4fe5-bd37-cb8ff461b138)

**Comment by steffakasid** [comment]
Same happens now with helm chart version 3.0.1 an app version 2.0.1. The image is not available @ https://hub.docker.com/r/amazon/aws-efs-csi-driver/tags?page=&page_size=&ordering=&name=v2.0 but it is on public.ecr.aws...

**Comment by Dbzman** [comment]
Also v2.0.1 on public.ecr.aws is not available as a multiarch image. All previous versions are, though.
![Bildschirmfoto 2024-04-26 um 13 23 17](https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/482264/f08d68e4-19ec-4a9c-ae7d-12363707d53e)

**Comment by sc-yan** [comment]
fixed at here.
https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1330
