### ISSUE TITLE
Support for EFS access point 

### ISSUE THREAD

**Issue by nithu0115** [kubernetes-sigs/aws-efs-csi-driver#131]
**Describe the solution you'd like in detail**

EFS recently released support for IAM authorization and Access points.  

https://aws.amazon.com/blogs/aws/new-for-amazon-efs-iam-authorization-and-access-points/

**Comment by nithu0115** [comment]
I think bumping up the `amazon-efs-utils` version should solve this issue. 

cc: @leakingtapan @wongma7

**Comment by leakingtapan** [comment]
duplicate of https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/124

/close
