### ISSUE TITLE
Releases link still points to v1 changelog

### ISSUE THREAD

**Issue by lumattr** [kubernetes-sigs/aws-efs-csi-driver#1331]
/kind bug

**What happened?**

Just a simple link issue in the description of the releases
https://github.com/kubernetes-sigs/aws-efs-csi-driver/releases/tag/v2.0.1

**Comment by mskanth972** [comment]
Hi @lumattr , thanks for brining here. I created a [PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1334) to update the link.

**Comment by mskanth972** [comment]
PR is merged which now points to the correct link.
