### ISSUE TITLE
Default log configuration is overly verbose

### ISSUE THREAD

**Issue by mikegirard** [kubernetes-sigs/aws-efs-csi-driver#134]
/kind bug

Using published instructions with canned configs for installing the driver and starting the daemonset is VERY chatty. It's flooding my Elasticsearch instance with messages since I've implemented log aggregation across my instance.

Editing the daemonset to turn down the -v level is possible, but the liveness probe still spits out 2 lines on every probe.

I would expect the default config yamls to have logging set to only show ERRORs with some instructions on the README on how to re-enable INFO and DEBUG

To reproduce - just install as documented and tail logs on the different containers in the created pods.

**Environment**
- Kubernetes version 1.14 (EKS us-west-2)
- Installed from Master branch on 2/20/2020.
  Driver Image version: aws-efs-csi-driver:v0.2.0

**Comment by leakingtapan** [comment]
Related to: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/128

**Comment by keifgwinn** [comment]
reopne please
