### ISSUE TITLE
support EFS in china regions

### ISSUE THREAD

**Issue by bnusunny** [kubernetes-sigs/aws-efs-csi-driver#138]
EKS was launched in China regions last week. EFS CSI Driver v0.2.0 docker image contains old version of efs-utils. efs-utils added China region support from v1.19. 

Can you please rebuild v0.2.0 image with the latest amazon linux 2 and release a new docker image?

**Comment by jerry123je** [comment]
+1

**Comment by leakingtapan** [comment]
You could use the docket image with latest tag for the latest rebuild.

**Comment by bnusunny** [comment]
The latest tag does work. But it is built from master branch. Does it suitable to use in production?

**Comment by leakingtapan** [comment]
It runs the same set of e2e tests as any versioned release. At least there is no breaking changes.

**Comment by bnusunny** [comment]
Hope we can have a next release out soon. Some customers are worried about running on the latest tag, which is not pined to a specific version.

**Comment by stevensu1977** [comment]
> EKS was launched in China regions last week. EFS CSI Driver v0.2.0 docker image contains old version of efs-utils. efs-utils added China region support from v1.19.
> 
> Can you please rebuild v0.2.0 image with the latest amazon linux 2 and release a new docker image?

+1

**Comment by stevensu1977** [comment]
@leakingtapan @bnusunny   I try chengpan/aws-efs-csi-driver:latest,  it's still not work :<, this image amazon-efs-utils version is 1.10,   so  I build  my image from master branch , it's use new amazon-efs-utils (1.21), now it's work .  if we can build new image and push to official EKS image ECR, that's great helpful to china user .

chengpan/aws-efs-csi-driver:latest shell information:

bash-4.2# yum info amazon-efs-utils
Loaded plugins: ovl, priorities
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Installed Packages
Name        : amazon-efs-utils
Arch        : noarch
Version     : 1.10
Release     : 1.amzn2
Size        : 41 k
Repo        : installed
From repo   : amzn2-core
Summary     : This package provides utilities for simplifying the use of EFS file systems
URL         : https://aws.amazon.com/efs
License     : MIT
Description : This package provides utilities for simplifying the use of EFS file systems

**Comment by liangruibupt** [comment]
Run on Ningxia region:
"message": "rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/csi-node-driver-registrar/manifests/v1.1.0: no basic auth credentials"

"message": "rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/aws-efs-csi-driver/manifests/latest: no basic auth credentials"

"message": "rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/csi-liveness-probe/manifests/v1.1.0: no basic auth credentials"

**Comment by stevensu1977** [comment]
@liangruibupt  I think you use wrong account id /ecr endpoint , China region EKS service have two official account id , cn-northwest-1 961992271922, cn-north-1 91830976355.

This is my dev kustomization.yaml,  I think chengpan/aws-efs-csi-driver:latest not fix it , so I build my image from master branch (CSI 0.3.0, amazon-eft-utils 1.21), it's work.


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: amazon/aws-efs-csi-driver
  newTag: latest
  newName: stevensu/aws-efs-csi-driver
  #newName: dockerhub.azk8s.cn/chengpan/aws-efs-csi-driver
- name: quay.io/k8scsi/livenessprobe
  newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-liveness-probe
  newTag: v1.1.0
- name: quay.io/k8scsi/csi-node-driver-registrar
  newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-node-driver-registrar
  newTag: v1.1.0

**Comment by bnusunny** [comment]
The current workaround: 

1. use the master branch - docker image "amazon/aws-efs-csi-driver:latest"
2. rebuild the v0.2.0 image with the latest efs-utils - docker image "awsguru/aws-efs-csi-driver:v0.2.1"

**Comment by liangruibupt** [comment]
> @liangruibupt I think you use wrong account id /ecr endpoint , China region EKS service have two official account id , cn-northwest-1 961992271922, cn-north-1 91830976355.
> 
> This is my dev kustomization.yaml, I think chengpan/aws-efs-csi-driver:latest not fix it , so I build my image from master branch (CSI 0.3.0, amazon-eft-utils 1.21), it's work.
> 
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> bases:
> 
> * ../../base
>   images:
> * name: amazon/aws-efs-csi-driver
>   newTag: latest
>   newName: stevensu/aws-efs-csi-driver
> * name: quay.io/k8scsi/livenessprobe
>   newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-liveness-probe
>   newTag: v1.1.0
> * name: quay.io/k8scsi/csi-node-driver-registrar
>   newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-node-driver-registrar
>   newTag: v1.1.0

Your are right, I have change to use the 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn

- name: amazon/aws-efs-csi-driver
  newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/aws-efs-csi-driver
  newTag: v0.2.0
- name: quay.io/k8scsi/livenessprobe
  newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-liveness-probe
  newTag: v1.1.0
- name: quay.io/k8scsi/csi-node-driver-registrar
  newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-node-driver-registrar
  newTag: v1.1.0

Then, I update each efs-csi-node amazon-efs-utils version >1.19, then everything work properly
kubectl exec -ti efs-csi-node-5jtlc -n kube-system -- /bin/bash
yum update -y amazon-efs-utils && mount.efs --version

**Comment by leakingtapan** [comment]
/close
as v0.3.0 is released: https://github.com/kubernetes-sigs/aws-efs-csi-driver/releases/tag/v0.3.0

**Comment by bnusunny** [comment]
Thanks a lot!

**Comment by vishal-swarankar-sdl** [comment]
@leakingtapan can you please update https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/deploy/kubernetes/overlays/stable/kustomization.yaml as well with latest version?
