### ISSUE TITLE
Incorrect StorageClass apiVersion in statefulset example.yaml

### ISSUE THREAD

**Issue by bbensky** [kubernetes-sigs/aws-efs-csi-driver#1399]
/kind bug

**What happened?**

The apiVersion for the StorageClass in the statefulset [example.yaml](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/statefulset/specs/example.yaml#L1) is currently `v1` and should be `storage.k8s.io/v1`. It looks like all of the other examples have the correct apiVersion for the StorageClass.

**What you expected to happen?**

Change the apiVersion for the StorageClass.

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by seanzatzdev-amazon** [comment]
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1400
