### ISSUE TITLE
Increase PID Range in EFS CSI Driver

### ISSUE THREAD

**Issue by mskanth972** [kubernetes-sigs/aws-efs-csi-driver#1403]
**Is your feature request related to a problem? Please describe.**
**Description:**
By default, we specify the range for PIDs in the `efs-utils` config file within EFS Utils and the CSI Driver. This ensures that any new stunnel/efs-proxy PID falls within this range. Currently, in the EFS CSI driver, the range is set to 20049 - 20449, covering 400 ports.

**Describe the solution you'd like in detail**
Increase Port Range:
Update the PID range in the EFS CSI Driver from 20049 - 20449 (400 ports) to 20049 - 21049 (1000 ports).

**Comment by mskanth972** [comment]
Have this PR out, will merge in the next release.
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1402

**Comment by rshiva777** [comment]
@mskanth972 , Why dont you provide end users the flexibility to dynamically update the port range instead of hard-coding ?

**Comment by mskanth972** [comment]
@rshiva777 that's a good option for customers. I can create this as a feature request and let the team know so that someone from can work on it.
