### ISSUE TITLE
health should be configurable in the helm chart

### ISSUE THREAD

**Issue by nwsparks** [kubernetes-sigs/aws-efs-csi-driver#1411]
the efs-plugin is frequently failing it's liveness probe on startup. I believe the current configuration in the helm chart is set to check too frequently (period: 2)

it would be simple to change this to allow configuration via helm values. to keep it in line with the existing `healthPort` I would propose adding the following to the controller and node sections.

```
  healthInitialDelaySeconds: 10
  healthTimeoutSeconds: 3
  healthPeriodSeconds: 10
  healthFailureThreshold: 5
```

I can raise a PR.

**Comment by seanzatzdev-amazon** [comment]
Can you provide logs & raise that PR?

**Comment by nwsparks** [comment]
sorry for the delay. I can. 

logs generally look like this. a bit tough to determine exactly what's happening here, my initial thought was looking at raising the initialdelay which brought me here.


![image](https://github.com/user-attachments/assets/fd28fb3a-9476-48fb-b96a-83abffa3c273)

**Comment by nwsparks** [comment]
pr is open https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1428
