### ISSUE TITLE
The endpoints in China region are different from others.

### ISSUE THREAD

**Issue by leeeboo** [kubernetes-sigs/aws-efs-csi-driver#142]
The endpoints in China region are different from others.
It is end by "amazonaws.com.cn"

So, I got the error in pod event: Failed to resolve "fs-XXXXX.efs.cn-northwest-1.amazonaws.com" - check that your file system ID is correct.

**Comment by wongma7** [comment]
What version of the driver are you using? This should be fixed in v0.3.0 via an update of aws-sdk-go.
