### ISSUE TITLE
Issue Encountered After Upgrading AWS EFS CSI Driver to Version 3.0.7

### ISSUE THREAD

**Issue by chinni92** [kubernetes-sigs/aws-efs-csi-driver#1437]
After upgrading the AWS EFS CSI Driver from version 2.5.1 to 3.0.7, we encountered a deployment failure due to an unsupported flag: --leader-election-renew-deadline.

Error Message:
unknown flag: --leader-election-renew-deadline

Affected Chart:
apiVersion: v2  
name: aws-efs-csi-driver  
version: 3.0.7  
kubeVersion: ">=1.17.0-0"
Could you please advise on how to resolve this issue?

**Comment by anthotse** [comment]
Could you provide some additional logs for this issue that you are encountering?

https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting

**Comment by mskanth972** [comment]
Closing this issue, please feel free to reopen and provide the additional logs if you are facing the issue still.
