### ISSUE TITLE
Mounting subpaths does not work

### ISSUE THREAD

**Issue by avbenavides** [kubernetes-sigs/aws-efs-csi-driver#145]
/kind bug

**What happened?**

Fails to mount EFS sub paths

**What you expected to happen?**
Mounting fails. Apparently the mount command is malformed (adds an extra ":" ) at the end.
Extract of Volume deployment descriptor
`        volumeHandle: fs-abc1234:/dir1
`

Becomes (from EFS CSI logs):

```logs
 I0326 08:59:33.273868       1 node.go:49] NodePublishVolume: called with args volume_id:" fs-abc1234:/dir1" target_path:"/var/lib/kubelet/pods/fd4f7a8a-ca04-4f77-8a0f-b2764c1aad51/volumes/kubernetes.io~csi/efs-pv1/mount" volume_capability:<mount:<> access_mode:<mode:MULTI_NODE_MULTI_WRITER > > 
I0326 08:59:33.273942       1 node.go:103] NodePublishVolume: creating dir /var/lib/kubelet/pods/fd4f7a8a-ca04-4f77-8a0f-b2764c1aad51/volumes/kubernetes.io~csi/efs-pv1/mount
I0326 08:59:33.273971       1 node.go:108] NodePublishVolume: mounting fs-c748929f:/walrus:/ at /var/lib/kubelet/pods/fd4f7a8a-ca04-4f77-8a0f-b2764c1aad51/volumes/kubernetes.io~csi/efs-pv1/mount with options []
I0326 08:59:33.273983       1 mount_linux.go:146] Mounting cmd (mount) with arguments ([-t efs  fs-abc1234:/dir1:/ /var/lib/kubelet/pods/fd4f7a8a-ca04-4f77-8a0f-b2764c1aad51/volumes/kubernetes.io~csi/efs-pv1/mount]) 
 E0326 08:59:33.521382       1 mount_linux.go:151] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t efs fs- fs-abc1234:/dir1 /var/lib/kubelet/pods/fd4f7a8a-ca04-4f77-8a0f-b2764c1aad51/volumes/kubernetes.io~csi/efs-pv1/mount
Output: mount.nfs4: mounting fs-abc1234.efs.eu-central-1.amazonaws.com:/dir1:/ failed, reason given by server: No such file or directory
E0326 08:59:33.521812       1 driver.go:71] GRPC error: rpc error: code = Internal desc = Could not mount "fs-abc1234:/dir1:/" at "/var/lib/kubelet/pods/fd4f7a8a-ca04-4f77-8a0f-b2764c1aad51/volumes/kubernetes.io~csi/efs-pv1/mount": mount failed: exit status 32
```

**How to reproduce it (as minimally and precisely as possible)?**
Try the mount sub path example
 
**Anything else we need to know?**:
These variations wont work either
```yaml 
          volumeHandle: fs-abc1234:dir1
          volumeHandle: fs-abc1234:/dir1/
          volumeHandle: fs-abc1234:dir1/
```

**Environment**
- Kubernetes version (use `kubectl version`): 
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- Driver version:

602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v0.2.0
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v1.1.0
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-liveness-probe:v1.1.0

**Comment by tclh123** [comment]
After hours struggling, I find they didn't upgrade the stable yaml file. So the issue is because we are still using v0.2.0 instead of v0.3.0
Just use the base one, we should be fine.
```
kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/base/?ref=master"
```

**Comment by Luwdo** [comment]
Using the base would mean you always get the latest tag. This is essentially the same as using the dev overlay.

A better option might be to make a new Kustomization resource that bases off of the base and just change the image Tag for aws-efs-csi-driver.

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/base/?ref=master
images:
  - name: amazon/aws-efs-csi-driver
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver
    newTag: v0.3.0
  - name: quay.io/k8scsi/livenessprobe
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-liveness-probe
    newTag: v1.1.0
  - name: quay.io/k8scsi/csi-node-driver-registrar
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar
    newTag: v1.1.0
```
Then apply the folder you have this file in
```
kubectl apply -k .
```

I tried to do a bases on
```
github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master
```
but what I ran into is that an overlay of an overlay requires a different syntax, I will have to do some research to see what Kustomization syntax needs to be to be able to stack them like that.

Issue: #100 is probably related because I ran into a same problem following the example here: 
https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/volume_path
