### ISSUE TITLE
Publish Helm Chart to Repo 

### ISSUE THREAD

**Issue by snithish** [kubernetes-sigs/aws-efs-csi-driver#146]
**Is your feature request related to a problem?/Why is this needed**
Publish Helm chart as a repo, as this would make it easier to add it as a dependency in application 
charts, reducing the amount of work that will need to be done in a script.

/feature

**Describe the solution you'd like in detail**
Chart published using Github Pages using [Chart Releaser](https://github.com/helm/chart-releaser)

**Comment by leakingtapan** [comment]
Good idea! Let me know who want to help

**Comment by zxkane** [comment]
There is an AWS managed charts repo(https://github.com/aws/eks-charts). It would be nicer to consolidate all charts related to EKS in same repo.

**Comment by kferrone** [comment]
I whipped up a quick index.yaml simply using `helm repo index`. The repo will be available as soon as PR is merged. However a maintainer of this project will have to make the docs folder public on Github Pages.

**Comment by leakingtapan** [comment]
Index file is published: https://kubernetes-sigs.github.io/aws-efs-csi-driver/index.yaml
