### ISSUE TITLE
Latest version in releases vs in changelog

### ISSUE THREAD

**Issue by rubroboletus** [kubernetes-sigs/aws-efs-csi-driver#1501]
/kind bug

**What happened?**

In "releases" latest mentioned version is 2.0.7, in CHANGELOG 2.1.0

**What you expected to happen?**

See all releases in releases and not just in CHANGELOG.

**How to reproduce it (as minimally and precisely as possible)?**

check releases and check CHANGELOG

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): n/a
- Driver version: n/a

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by owengo** [comment]
The helm repo also is not updated also since chart version 3.0.8

**Comment by mskanth972** [comment]
Thanks for bringing here, seems like GitHub token got expired, will check this.
https://github.com/kubernetes-sigs/aws-efs-csi-driver/actions/runs/11555346532/job/32160534954

**Comment by mskanth972** [comment]
Raised PR to give permissions for the GitHub actions.
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1508

**Comment by mskanth972** [comment]
Merged the PR.
