### ISSUE TITLE
High priority CVEs in v2.1.0

### ISSUE THREAD

**Issue by vadasambar** [kubernetes-sigs/aws-efs-csi-driver#1503]
<img width="1460" alt="image" src="https://github.com/user-attachments/assets/256fac69-ed30-456c-95cd-53a992ba39d7">

All of them can be fixed by using a more recent version of golang. We are using v1.22.5 right now: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/dad9553f87db843b5f0ee7fe19aa547d439b3351/go.mod#L154

**Comment by vadasambar** [comment]
One more
<img width="1447" alt="image" src="https://github.com/user-attachments/assets/8bf289ed-ec8c-4a17-bd5b-ad976f89b883">

**Comment by mskanth972** [comment]
Thanks for bringing here @vadasambar, will bring this to the team to work on the release soon.

**Comment by andrewjamesbrown** [comment]
Maybe addressed by https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1514 and https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1513 ?
