### ISSUE TITLE
Request ability to specify different path to kubelet

### ISSUE THREAD

**Issue by tomkivlin** [kubernetes-sigs/aws-efs-csi-driver#163]
**Is your feature request related to a problem? Please describe.**
When using some Kubernetes distributions e.g. RKE, the path to kubelet isn't always `/var/lib/kubelet` and so it would be nice for either the documented installation steps to include the steps to modify that path, or for the installation to automatically detect the path (or be told the path without needing to modify the node.yaml artefact).

**Describe the solution you'd like in detail**
Installation guide including the steps to modify the kubelet path (I am more than happy to contribute), or installation artefacts that automatically detect the path for the deployed cluster.

**Describe alternatives you've considered**
I have forked the repository and made the changes here: https://github.com/tomkivlin/aws-efs-csi-driver/blob/master/deploy/kubernetes/base/node.yaml

**Additional context**
This is the error that is seen when the path to kubelet is incorrectly set in node.yaml:
```
  Warning  FailedMount  27s (x8 over 90s)  kubelet, ip-10-0-2-213.eu-west-3.compute.internal  MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory
```

**Comment by jpmolinamatute** [comment]
hey @tomkivlin  were you able to solve this issue? (I'm having the same problem)

**Comment by tomkivlin** [comment]
> hey @tomkivlin were you able to solve this issue? (I'm having the same problem)

Well, I have a workaround - I forked the repo, and created modifications of the [node.yaml](https://github.com/tomkivlin/aws-efs-csi-driver/blob/master/deploy/kubernetes/base/node.yaml#L38) file - link takes you to an example of the path that needs changing.  I then just deployed from that repo instead of the one in the instructions.

**Comment by jpmolinamatute** [comment]
Hey @tomkivlin thanks so much for the help! it worked as charm! :-)
