### ISSUE TITLE
tag 0.3.0 seems to deploy version 0.2.0

### ISSUE THREAD

**Issue by wreed4** [kubernetes-sigs/aws-efs-csi-driver#172]
/kind bug

**What happened?**
Reading the manifests, https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/deploy/kubernetes/overlays/stable/kustomization.yaml points to v0.3.0, but the _tag_ v0.3.0 does not: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v0.3.0/deploy/kubernetes/overlays/stable/kustomization.yaml

This seems like a bug

**What you expected to happen?**
Tag v0.3.0 should actually deploy v0.3.0 :)

**Comment by leakingtapan** [comment]
Yes. the release in the ECR is a bit delayed than the actual driver release, that's one of the reason we switched to use dockerhub post 0.3 release for kustomize. Feel free to submit a patch to release-0.3 branch if this matters to u

**Comment by jqmichael** [comment]
It's a bug and it won't be fixed ever given tag is supposed to be immutable. 

We will make ECR image available before any future releases (and we have one coming up soon).

**Comment by leakingtapan** [comment]
We can still release v0.3.1 though

**Comment by jqmichael** [comment]
> We can still release v0.3.1 though

True. That's the same as releasing v0.4.0 or v1.0.0. 

We will get the tag match in our next release.

**Comment by leakingtapan** [comment]
/milestone-0.4
