### ISSUE TITLE
Unable to mount EFS volume inside EKS when using access points

### ISSUE THREAD

**Issue by holypriest** [kubernetes-sigs/aws-efs-csi-driver#177]
/kind bug

**What happened?**

Tried the example available at `examples/kubernetes/multiple_pods/specs` updating `pv.yaml` to include `accesspoint` field:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - tls
    - accesspoint=fsap-XXX
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-XXX
```

Running `kubectl apply -f specs`, the pods `app1` and `app2` get stuck at `ContainerCreating` state due to a mount error:

```
Mounting command: mount
Mounting arguments: -t efs -o tls,accesspoint=fsap-XXX fs-XXX:/ /var/lib/kubelet/pods/<pod-id>/volumes/kubernetes.io~csi/efs-pv/mount
Output: Traceback (most recent call last):
  File "/sbin/mount.efs", line 1375, in <module>
    main()
  File "/sbin/mount.efs", line 1369, in main
    mount_tls(config, init_system, dns_name, path, fs_id, mountpoint, options)
  File "/sbin/mount.efs", line 1302, in mount_tls
    with bootstrap_tls(config, init_system, dns_name, fs_id, mountpoint, options) as tunnel_proc:
  File "/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/sbin/mount.efs", line 705, in bootstrap_tls
    security_credentials, ap_id=ap_id, base_path=state_file_dir)
  File "/sbin/mount.efs", line 848, in create_certificate
    private_key = check_and_create_private_key(base_path)
  File "/sbin/mount.efs", line 911, in check_and_create_private_key
    do_with_lock(generate_key)
  File "/sbin/mount.efs", line 894, in do_with_lock
    return function()
  File "/sbin/mount.efs", line 907, in generate_key
    subprocess_call(cmd, 'Failed to create private key')
  File "/sbin/mount.efs", line 970, in subprocess_call
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True)
  File "/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
**What you expected to happen?**

The pods `app1` and `app2` should start normally.

**How to reproduce it (as minimally and precisely as possible)?**
- Create an EFS access point at `/test` (with or without specifying user/group)
- Update `pv.yaml` to include the access point ID
- Run `kubectl apply -f specs`

**Anything else we need to know?**:
- That's all OK network-wise. I could make it work flawlessly without access points.
- I tried to specify different POSIX users/groups such as 0 (root), 1000 (ec2-user), but to no avail.
- I tried to set different permissions (777, 755, etc), but to no avail.

**Environment**
- Kubernetes version (use `kubectl version`): 1.15
- Driver version: 0.3.0

**Comment by ZhangSIming-blyq** [comment]
Hello, I met the same problem, did you fix it?

**Comment by farshad-hobsons** [comment]
I see you are using 0.3.0 version of the driver
> * Driver version: 0.3.0

The [EFS Access Points documentation](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/0ae998c5a95fe6dbee7f43c182997e64872695e6/examples/kubernetes/access_points#efs-access-points) says:

> Note: Because access point mounts require TLS, this is not supported in driver versions at or before 0.3.

The above worked for me with `image: amazon/aws-efs-csi-driver:latest`

**Comment by holypriest** [comment]
@ZhangSIming-blyq I will try with the new version, as suggested by @farshad-hobsons . I'll leave my comments here after testing.

**Comment by xposix** [comment]
I had the same problem and updating to 1.0.0 worked! Access points are only supported on this version.
