### ISSUE TITLE
Upgrading CSI driver broke all existing mounts (at least the non-tls ones)

### ISSUE THREAD

**Issue by jqmichael** [kubernetes-sigs/aws-efs-csi-driver#183]
/kind bug

**What happened?**
If I upgrade CSI driver, say from v0.2.0 to v0.3.0, or simply delete the CSR driver pod and let it get replaced, all my existing mounts (tested non-tls mounts) hang indefinitely. 

**What you expected to happen?**
Existing mounts remain functioning after a new driver is in place. 

**How to reproduce it (as minimally and precisely as possible)?**
Deploy the v0.2.0 driver, and launch a pod using the static provision example. Deploy the v0.3.0 driver and watch the output of `kubectl exec -ti efs-app -- tail -f /data/out.txt`. It will hang indefinitely. 

**Anything else we need to know?**:
I observed the same behavior by simply deleting the CSI driver pod and let it get replaced. 

```
[ec2-user@ip-192-168-73-239 ~]$ mount |grep nfs
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
fs-b6654c1c.efs.us-west-2.amazonaws.com:/ on /var/lib/kubelet/pods/0d39b3ce-81f3-4542-8abd-4b158834c082/volumes/kubernetes.io~csi/efs-pv/mount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.79.46,local_lock=none,addr=192.168.134.20)
```

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by jqmichael** [comment]
From the output of `mount`, 
`clientaddr=192.168.79.46,local_lock=none,addr=192.168.134.20`

`192.168.79.46` is the driver pod IP, `192.168.134.20` is the mount target IP.

**Comment by farshad-hobsons** [comment]
I consistently can reproduced and experienced the same kind of problem when I intentionally tried bouncing the `efs-csi-node` pods by running `kubectl -nops delete po -l app=efs-csi-node` as a test.

### How to reproduce this:
- Use kustomize to deploy csi driver in a namespace called `ops` in a cluster version `v1.15.11-eks-af3caf` with `kustomize/v3.5.4`:

Bases File:`k8s/kustomize/bases/aws-efs-csi-driver/kustomization.yaml`
```yaml
resources:
  - github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master
patches:
- target:
    kind: DaemonSet
    name: efs-csi-node
    namespace: kube-system
  patch: |-
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: efs-csi-node
      namespace: ops
    spec:
      template:
        spec:
          priorityClassName: ""
```

Overlay File: `k8s/kustomize/overlays/sandbox/aws-efs-csi-driver/kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "ops"
bases:
- ../../../bases/aws-efs-csi-driver
images:
- name: amazon/aws-efs-csi-driver
  newTag: latest
- name: quay.io/k8scsi/livenessprobe
  newTag: v2.0.0
- name: quay.io/k8scsi/csi-node-driver-registrar
  newTag: v1.3.0
```

- Deploy csi driver using:
```bash
# kustomize build k8s/kustomize/overlays/sandbox/aws-efs-csi-driver/ | kubectl apply -f -
daemonset.apps/efs-csi-node created
csidriver.storage.k8s.io/efs.csi.aws.com created
```

- Test the multiple pod access example at https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/multiple_pods by doing the following:
_Note: replace `YOUR_EFS_ID` by your efs fs-id_
```bash
# kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-efs-csi-driver/master/examples/kubernetes/multiple_pods/specs/storageclass.yaml
storageclass.storage.k8s.io/efs-sc created

# kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-efs-csi-driver/master/examples/kubernetes/multiple_pods/specs/pv.yaml -oyaml --dry-run | sed 's/volumeHandle:.*/volumeHandle: fs-YOUR_EFS_ID/
' | kubectl apply -f -
persistentvolume/efs-pv created

# kubectl -ntest-namespace apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-efs-csi-driver/master/examples/kubernetes/multiple_pods/specs/claim.yaml
persistentvolumeclaim/efs-claim created

# kubectl -ntest-namespace apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-efs-csi-driver/master/examples/kubernetes/multiple_pods/specs/pod1.yaml -f https://raw.githubusercontent.com/kubernetes-sigs/aws-efs-csi-driver/master/examples/kubernetes/multiple_pods/specs/pod2.yaml
pod/app1 created
pod/app2 created
```

- Test pods accessing efs by tailing
```bash
# kubectl -nops-managed exec -ti app1 -- tail -f /data/out1.
Wed Jun 24 12:42:31 UTC 2020
Wed Jun 24 12:42:36 UTC 2020
Wed Jun 24 12:42:41 UTC 2020 <-tailing stops updating at this time point when csi-node pods are killed

# kubectl -nops-managed exec -ti app2 -- tail -f /data/out2.txt
Wed Jun 24 12:42:31 UTC 2020
Wed Jun 24 12:42:36 UTC 2020
Wed Jun 24 12:42:41 UTC 2020  <-tailing stops updating at this time point when csi-node pods are killed
```

- Test the killing of the csi pods and wait for them to be recreated
```bash
# date; kubectl -nops delete po -l app=efs-csi-node
Wed Jun 24 12:42:41 UTC 2020
pod "efs-csi-node-8b6g6" deleted
pod "efs-csi-node-klvjp" deleted
pod "efs-csi-node-qgp4p" deleted
```

**Comment by farshad-hobsons** [comment]
@leakingtapan @wongma7 - The changes from from "gitCommit": "c6082e582166cc85b9d9761b7e5b0546f7fd153c"("buildDate": "2020-06-24T19:51:36Z") to "gitCommit": "8cfff11b09ed1f1d3a3e5c1bd20ce79b262b0805"("buildDate": "2020-06-25T02:43:16Z") seem to have fixed the issue. I cannot reproduce it anymore.

From the [changeset](https://github.com/kubernetes-sigs/aws-efs-csi-driver/compare/c6082e582166cc85b9d9761b7e5b0546f7fd153c..8cfff11b09ed1f1d3a3e5c1bd20ce79b262b0805), was this only related to setting `hostNetwork: true` or were the changes to `pkg/driver/node.go` the main fix?

If we can get a versioned tag on the current state(8cfff11b09ed1f1d3a3e5c1bd20ce79b262b0805) then that would be awesome

This is exciting. Thanks again.

**Comment by wongma7** [comment]
@farshad-hobsons it was the hostNetwork: true change. Yes I want to make a tagged release for 0.4.0, takes a bit of coordination.

**Comment by wongma7** [comment]
(we need https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/196 as well before a release IMO)

**Comment by farshad-hobsons** [comment]
Also, noting that when I test the https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/access_points/specs/example.yaml , the mount hangs only for the duration of the time during which aws-efs-csi-driver Pod is down, when the driver pod recovers the hanged-mount recovers meaning that application recovers automatically when driver pod recovers. I assume this is expected functionality.

**Comment by wongma7** [comment]
I don't think that is expected. If it's specific to when you use access points or tls (access points implies tls) then it is probably a variation of this issue https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/178 where the driver cannot access the private key for encryption/decryption

**Comment by farshad-hobsons** [comment]
ok, fyi, I tested the tls-only example (https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/encryption_in_transit/specs) and the behavior of the issue is same i.e. mountpoints hang only during the time the csi-driver is down. Mountpoints recover when driver pod becomes available.
