### ISSUE TITLE
EFS mount issue with efs csi driver latest image tag

### ISSUE THREAD

**Issue by sansarsankhyan2391** [kubernetes-sigs/aws-efs-csi-driver#198]
/kind bug

i have tried efs csi driver with the latest image tag as the tag 0.3.0 was giving errors.
but i am getting the below errror with the latest image tag now:

 **driver name efs.csi.aws.com not found in the list of registered CSI drivers**

**Comment by wongma7** [comment]
You may be experiencing this issue: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/191 . The command `kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"` was broken for some time but it should be fixed now.
