### ISSUE TITLE
Delete/Clean filesystem/access point on PV deletion

### ISSUE THREAD

**Issue by galindro** [kubernetes-sigs/aws-efs-csi-driver#201]
Would be nice if the filesystem or access point be cleaned after PV deletion to avoid trash or unintentional behaviors with stateful applications that uses EFS (for example, databases, etc...)

**Comment by wongma7** [comment]
This will follow from implementing dynamic provisioning tracked here: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/6 . The driver will create access points on PVC creation and delete them on PVC deletion (if the ReclaimPolicy of the PV is Delete).

Going to close as duplicate

/close
