### ISSUE TITLE
PVC stuck in pending state: ExternalExpanding' Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC

### ISSUE THREAD

**Issue by GJKrupa** [kubernetes-sigs/aws-efs-csi-driver#203]
/kind bug

**What happened?**

I followed the examples for setting up a PV and PVC with in-flight TLS. I removed the PV and PVS and re-created them. The PVC became permanently stuck with the following in the events:

ExternalExpanding' Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC

**What you expected to happen?**

The PVC should have become bound

**How to reproduce it (as minimally and precisely as possible)?**

Create an example PV and PVC accessing the root of a pre-created EFS volume
Delete the PV and PVC
Re-create the PV and PVC

**Anything else we need to know?**:

This only seemed to happen when the PVC was deployed to a node where the EFS volume had already been mounted. The PVC would successfully go to Bound if I saw a new mount being attached in the driver logs.

**Environment**
- Kubernetes version (use `kubectl version`): v1.14.9-eks-f459c0
- Driver version: v0.3.0

**Comment by GJKrupa** [comment]
I should add that both the PV and the PVC have a storage request size of 5Gi so there should be no expansion required.

**Comment by wongma7** [comment]
That ExternalExpanding does not explain why the PVC did not become bound. Please share the output of `kubectl get pvc -o yaml` for the pvc in question before and after recreating it

**Comment by GJKrupa** [comment]
No real differences other than the state and the annotations. The flux annotation was removed because I had to run a `helm upgrade` from the command-line to restore the PVC after deleting it with kubectl.

Before:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    flux.weave.works/antecedent: infra:helmrelease/efs-root-volume
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2020-06-29T16:15:01Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: efs-root-volume
    app.kubernetes.io/component: volume-claim
    app.kubernetes.io/instance: efs-root-volume
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: efs-root-volume
    helm.sh/chart: efs-root-volume
  name: efs-root-volume
  namespace: infra
  resourceVersion: "35756002"
  selfLink: /api/v1/namespaces/infra/persistentvolumeclaims/efs-root-volume
  uid: aefb3825-ba23-11ea-8912-0243ea9ae35c
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs
  volumeMode: Filesystem
  volumeName: efs-root-volume
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  phase: Bound
```

After:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2020-06-30T10:36:29Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: efs-root-volume
    app.kubernetes.io/component: volume-claim
    app.kubernetes.io/instance: efs-root-volume
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: efs-root-volume
    helm.sh/chart: efs-root-volume
  name: efs-root-volume
  namespace: infra
  resourceVersion: "36030435"
  selfLink: /api/v1/namespaces/infra/persistentvolumeclaims/efs-root-volume
  uid: 8eab105f-babd-11ea-8912-0243ea9ae35c
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs
  volumeMode: Filesystem
  volumeName: efs-root-volume
status:
  phase: Pending
```

**Comment by GJKrupa** [comment]
This is the output from describing the PVC:

```
Name:          efs-root-volume
Namespace:     infra
StorageClass:  efs
Status:        Pending
Volume:        efs-root-volume
Labels:        app=efs-root-volume
               app.kubernetes.io/component=volume-claim
               app.kubernetes.io/instance=efs-root-volume
               app.kubernetes.io/managed-by=Tiller
               app.kubernetes.io/name=efs-root-volume
               helm.sh/chart=efs-root-volume
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      0
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason             Age                  From           Message
  ----     ------             ----                 ----           -------
  Warning  ExternalExpanding  93s (x3 over 5m33s)  volume_expand  Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
```

**Comment by GJKrupa** [comment]
At a guess I think what's happening is that I was deleting the PVC but no the PV earlier. When I create a new PVC it assumes that the previous one already consumed all the space in the PV and it's trying to expand it to create more but can't. If I make the PVC smaller than the PV it doesn't help because k8s allocates the full PV to the PVC anyway.

I believe that the k8s NFS driver also has this issue of being unable to expand the file system to support multiple PVCs even though it's meaningless when you're not allocating space in block storage.

**Comment by wongma7** [comment]
If you delete the PVC and not the PV the PV will enter Released state, not Available, and so your PVC will stay Pending even though you intend for it to bind to that same PV again.

The expand error is a bit of a red herring. I'm not sure why it's creating that event but it should not even be handling PVCs that are in state Pending.

**Comment by wongma7** [comment]
To be clear there is a 1:1 mapping between PVC and PV.
