### ISSUE TITLE
MountVolume.SetUp failed.

### ISSUE THREAD

**Issue by GrataHonoria** [kubernetes-sigs/aws-efs-csi-driver#228]
/kind bug

**What happened?**
The pod is stuck on ContainerCreating with the error:
```
Warning  FailedMount  21s (x3 over 4m23s)        kubelet, ip-10-63-253-230.ec2.internal  MountVolume.SetUp failed for volume "efs-pv" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount  <invalid> (x3 over 4m21s)  kubelet, ip-10-63-253-230.ec2.internal  Unable to mount volumes for pod "efs-app-sts-0_jx(6a583676-443c-4f6d-864a-5a2f4b416536)": timeout expired waiting for volumes to attach or mount for pod "jx"/"efs-app-sts-0". list of unmounted volumes=[efs-storage]. list of unattached volumes=[efs-storage default-token-q8zqv]
```

**What you expected to happen?**
The pod to be a in a running state.

**How to reproduce it (as minimally and precisely as possible)?**
Install the driver:
`kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.0"`
 & apply the statefulset example with your EFS filesystem id.
 `kubectl apply -f example.yaml`

**Anything else we need to know?**:
I have made a EFS on the same VPC as my EKS. I have added a security group to the mount targets that allow NFS[TCP/2049] to the whole VPC CIDR.
I also tried changing the version in the deamon set from `v1.0.0` to `master` & the image pull policy to always. I also successfully mounted the EFS  from the node it self using the EFS mount helper to test the security group.

[`kubectl get pods -o=custom-columns=NAME:.metadata.name -nkube-system|grep efs-csi-node|xargs -I{} kubectl logs -nkube-system -cefs-plugin {}`](https://gist.github.com/GrataHonoria/4c15c3ef6e86fc95f8ec91f902b1a5d9)

[`kubectl exec $(kubectl get po -l app=efs-csi-node -n kube-system -o jsonpath='{.items[0].metadata.name}') -n kube-system -it -cefs-plugin -- cat /var/log/amazon/efs/mount-watchdog.log`](https://gist.github.com/GrataHonoria/17f6c48af4ac3d269f49aad4be541284)

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"39a145ca3413079bcb9c80846488786fed5fe1cb", GitTreeState:"clean", BuildDate:"2020-07-16T14:27:30Z", GoVersion:"go1.13.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- Driver version: v1.0.0

**Comment by jqmichael** [comment]
Do you mind checking out this PR to collect more logs for troubleshooting?
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/217/files

**Comment by GrataHonoria** [comment]
https://github.com/GrataHonoria/efs-logs

I unmounted all the old mounts in the efs-plugin container & deleted the files in /var/run/efs. I don't think they get unmounted properly. The statefulset worked after that. 

The python script had to be edit to include the efs-csi pod name. it seems to ignore the argument.
`
kubectl describe po efs-csi-node-5dpc4 -n kube-system

Error from server (NotFound): pods "efs-csi-node-5dpc4" not found


kubectl get po efs-csi-node-5dpc4 -n kube-system -o yaml

Error from server (NotFound): pods "efs-csi-node-5dpc4" not found
`
 I was using python 3.8. I don't think it works on any python version below 3.7.
`python log_collector.py --driver-pod-name efs-csi-node-4pq7n`

**Comment by chinmaychandak** [comment]
@GrataHonoria, were you able to fix this? I'm seeing a similar issue.

**Comment by darwin67** [comment]
Please reopen this issue.
Problem is still occuring on 1.2.0
