### ISSUE TITLE
Update helm chart for 1.0.0 release

### ISSUE THREAD

**Issue by albertmichaelj** [kubernetes-sigs/aws-efs-csi-driver#235]
**Is your feature request related to a problem?/Why is this needed**
I tried to install the helm chart today for the `aws-efs-csi-driver`, but I realized that the helm chart only install version `v0.1.0`. This is a very outdated version given that the current release is `v1.0.0`

**Describe the solution you'd like in detail**
I'd like to see an update to the helm chart so that the helm chart tracks the latest release.

**Comment by Saberos** [comment]
The [index.yaml](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/gh-pages/index.yaml) used by Helm has not yet been updated to point to support the v1.0.0 release.

**Comment by wongma7** [comment]
We are aware, but there is some weird issue with the digest (which I understand is not really used by helm for verification anyway) and I don't have permission to push a new index: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/223 a

**Comment by wongma7** [comment]
By the way, 0.1.0 refers to the version of the helm chart, not the `appVersion` of the CSI driver. Can you double check the version of the driver that was installed by inspecting the aws-efs-csi-driver DaemonSet?

**Comment by albertmichaelj** [comment]
I realized after I opened this issue that the helm chart version did not track with the `appVersion`, but it was an outdated version because it wouldn't let me use TLS encryption. It gave me an error that TLS encryption was not supported on the version. Unfortunately, I don't have it installed anymore, and I am hesitant to put it on my production cluster again. I uninstalled the helm chart and then installed this from just applying the `yaml` files method of installation, and then pods started failing to start, I'm still not sure what that issue was. I've switched back to standard NFS pvs for now.

**Comment by Saberos** [comment]
> By the way, 0.1.0 refers to the version of the helm chart, not the `appVersion` of the CSI driver. Can you double check the version of the driver that was installed by inspecting the aws-efs-csi-driver DaemonSet?

Can confirm that I'm getting v0.3.0 csi driver daemonset containers when using helm chart v0.1.0.

**Comment by arvin6msd** [comment]
Same issue. helm update does not update 0.3 app version to 1.0. Can someone update the chart?

**Comment by antonosmond** [comment]
The helm chart version has not been bumped in the update to appVersion 1.0.0 so helm chart 0.1.0 (if pulling from the helm repo) refers to appVersion 0.3.0 however the [Chart.yaml](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v1.0.0/helm/Chart.yaml) in this repo has appVersion 1.0.0. Chart 0.1.0 cannot be both appVersion 0.3.0 and 1.0.0 so the chart version needs to be bumped e.g. chart 0.1.1 and appVersion 1.0.0.
