### ISSUE TITLE
nodeSelector unused in helm chart

### ISSUE THREAD

**Issue by mmccord-mdbuyline** [kubernetes-sigs/aws-efs-csi-driver#236]
/kind bug

**What happened?**

The `nodeSelector` key in the `values.yaml` is unused by the templates of the chart.

**What you expected to happen?**

`nodeSelector` is used by the charts and subkeys are populated under the `nodeSelector` key of the `DaemonSet`.

**How to reproduce it (as minimally and precisely as possible)?**

Install the chart while specifying nodeSelectors, note they are not populated.

**Anything else we need to know?**:

No

**Environment**
- Kubernetes version (use `kubectl version`): Irrelevant error is in chart template.
- Driver version: v1.0.0

**Supplemental**
Also, latest version of chart does not seem to be deployed to the chart repo at: https://kubernetes-sigs.github.io/aws-efs-csi-driver/index.yaml

**Comment by wongma7** [comment]
I just merged https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/226 to fix this, could you try out the new chart? Please reopen if it's still broken.

Also, I'm aware about the index being broken, it's work in progres shere: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/223
