### ISSUE TITLE
Mounting EFS from a peered VPC

### ISSUE THREAD

**Issue by wgordon17** [kubernetes-sigs/aws-efs-csi-driver#240]
**Is your feature request related to a problem?/Why is this needed**
I'm unable to mount a EFS volume across peered VPCs. The error message is "Failed to resolve "fs-e0fc4798.efs.us-east-2.amazonaws.com" - check that your file system ID is correct." There _is_ a workaround that requires updating the `/etc/hosts` file on each node, however that is not an option for my usage on OpenShift.

/feature

**Describe the solution you'd like in detail**
Please provide the ability to specify the mount IP address instead of relying on DNS resolution. The driver appears to support it (https://docs.aws.amazon.com/efs/latest/ug/wt1-test.html#wt1-mount-fs-and-test)
```
sudo mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport mount-target-ip:/  ~/efs-mount-point
```

**Describe alternatives you've considered**
- Modifying the `/etc/hosts` file on the node (https://docs.aws.amazon.com/efs/latest/ug/manage-fs-access-vpc-peering.html#mount-fs-different-vpc), however this is not an option on OpenShift currently
- Creating a private hosted zone for "efs.us-east-2.amazonaws.com", however that consistently fails with domain clashing errors

**Comment by 2uasimojo** [comment]
Things that come to mind:
- Syntax-wise, allow the fsid chunk of the volumeID to be an IP. But since the volumeID is currently colon-delimited, IPv6 addresses will be a pain.
- How do access points fit in here? Remembering that for [openshift/aws-efs-operator](https://github.com/openshift/aws-efs-operator) we use that to get around default root permissions on base mount points.

:eyes:

**Comment by bysnupy** [comment]
@2uasimojo If `hostAliases` is allowed to configure at `efs-csi-node` DaemonSet on [openshift/aws-efs-operator](https://github.com/openshift/aws-efs-operator) through CR.

**Comment by 2uasimojo** [comment]
@bysnupy Oh, that's cool! @wgordon17 let's play around with this, yeah?

**Comment by wgordon17** [comment]
@bysnupy That's an awesome suggestion!! With @2uasimojo's help (and a modified operator), we were able to confirm that `hostAliases` did _exactly_ what we needed it to! Thanks again 🎉

**Comment by ronlut** [comment]
@bysnupy @wgordon17 
Thanks for the great solution!
Should that work in a multi-az cluster? 
If I add the zone "a" mount target ip to the host aliases for example, and have a node in zone "b", I think it causes "volume node affinity conflict"?
It happens only to pods scheduled on nodes in a different az than the zone of the EFS mount target.

How will you tackle that problem?

**Comment by bysnupy** [comment]
@ronlut This solution is about the VPC peering, so it's available regardless of AZ between EFS and k8s node. Because VPC peering would be controlled by routing table rules(e.g. CIDR network) between VPC peers.

**Comment by raymondsquared** [comment]
Would something like AWS Private Link can be used to resolve the DNS aliases?
