### ISSUE TITLE
Very dirty Helm chart

### ISSUE THREAD

**Issue by gillg** [kubernetes-sigs/aws-efs-csi-driver#243]
Hi,

In the 1.0.0 helm chart release some things are not clean...

* In values.yaml there is a `replicaCount: 2`. This makes no sense for a DaemonSet, and this value is use nowhere.
* In daemonset `securityContext.privileged: true` and `volumes[].hostPath` are use, which needs a specific PSP declaration in a secured cluster. (with a service account attached to pods)
* `podAnnotations` and `tolerations` in values are not used, but `node.podAnnotations` and `node.tolerations` are used... Why prefix them by `node` ?
* `imagePullSecrets`, `affinity` and `resources` in values are not used
* Usual `podLabels` is missing, and could be very important to assign policies / permissions to pod. I'm not sure who calls AWS EFS API, is it kubelet on node or "efs-plugin" container ? If it's efs-plugin, labels are a must-have to use it with Kiam for example.

I could help to clean it if necessary

**Comment by JonathanLachapelle** [comment]
I agree, this need to be improved.

I cannot use this helm chart as of right now because my cluster can only use a private repo and require the use of Image Pull Secrets

**Comment by wongma7** [comment]
Help would be appreciated, the helm chart has not changed much since creation and does not get much attention compared to kustomize

**Comment by quizy101** [comment]
I've submitted PR #279 to address these issues if you want to take a look.
