### ISSUE TITLE
livenessprobe  and csi-node-driver-registrar not from aws ECR .

### ISSUE THREAD

**Issue by Srini-B-GIT** [kubernetes-sigs/aws-efs-csi-driver#244]
**Is your feature request related to a problem?/Why is this needed**
Latest /aws-efs-csi-driver-master/deploy/kubernetes/overlays/stable/kustomization.yaml file pulling images for 
livenessprobe  and csi-node-driver-registrar from quay.io  in most of the client environments they prefer these images directly downloaded for Amazon ECR rather than connecting to private site. so if possible please upload them to amazon ecr.

**Describe the solution you'd like in detail**
please upload livenessprobe  and csi-node-driver-registrar images  to amazon ecr.

**Describe alternatives you've considered**

**Additional context**

**Comment by wongma7** [comment]
There is an ecr kustomize overlay, does that work for you? https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
