### ISSUE TITLE
Image pull error:  Failed to pull image 

### ISSUE THREAD

**Issue by Cuite21** [kubernetes-sigs/aws-efs-csi-driver#245]
/kind bug

**What happened?**
When using the master branch, while creating the deployment pods are in image pull error state

Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driv
er:v1.0.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/aws-efs-csi-driver/manifests/v1
.0.0: no basic auth credentials

**What you expected to happen?**
The pods should have been successfully deployed in running stste

**How to reproduce it (as minimally and precisely as possible)?**

While describing the pods the output is as follows:

Name:                 efs-csi-node-d6sqn
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 ip-x.x.x.x.ec2.internal/x.x.x.x
Start Time:           Tue, 08 Sep 2020 14:10:05 +0000
Labels:               app=efs-csi-node
                      controller-revision-hash=69bd7ff8f4
                      pod-template-generation=1
Annotations:          <none>
Status:               Pending
IP:                   x.x.x.x
Controlled By:        DaemonSet/efs-csi-node
Containers:
  efs-plugin:
    Container ID:
    Image:         602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.0.0
    Image ID:
    Port:          9809/TCP
    Host Port:     9809/TCP
    Args:
      --endpoint=$(CSI_ENDPOINT)
      --logtostderr
      --v=5
    State:          Waiting
      Reason:       ErrImagePull
    State:          Waiting                                                                                                                                    
      Reason:       ErrImagePull
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:healthz/healthz delay=10s timeout=3s period=2s #success=1 #failure=5
    Environment:
      CSI_ENDPOINT:  unix:/csi/csi.sock
    Mounts:
      /csi from plugin-dir (rw)
      /etc/amazon/efs from efs-utils-config (rw)
      /var/lib/kubelet from kubelet-dir (rw)
      /var/run/efs from efs-state-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-ghtjw (ro)
  csi-driver-registrar:
    Container ID:
    Image:         602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v1.3.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
      --v=5
    State:          Waiting
      Reason:       ErrImagePull
    Ready:          False
    Restart Count:  0
    Environment:
      ADDRESS:               /csi/csi.sock
      DRIVER_REG_SOCK_PATH:  /var/lib/kubelet/plugins/efs.csi.aws.com/csi.sock
      KUBE_NODE_NAME:         (v1:spec.nodeName)
    Mounts:
      /csi from plugin-dir (rw)
      /registration from registration-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-ghtjw (ro)
  liveness-probe:
    Container ID:
    Image:         602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.0.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=/csi/csi.sock
    Args:                                                                                                                                                      
      --csi-address=/csi/csi.sock
      --health-port=9809
    State:          Waiting
      Reason:       ErrImagePull
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /csi from plugin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-ghtjw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kubelet-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet
    HostPathType:  Directory
  registration-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/plugins_registry/
    HostPathType:  Directory
  plugin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/plugins/efs.csi.aws.com/
    HostPathType:  DirectoryOrCreate
  efs-state-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/efs
    HostPathType:  DirectoryOrCreate
  efs-utils-config:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/amazon/efs
    HostPathType:  DirectoryOrCreate
  default-token-ghtjw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-ghtjw
    Optional:    false
QoS Class:       BestEffort
    Optional:    false                                                                                                                                         
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/arch=amd64
                 kubernetes.io/os=linux
Tolerations:
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                   From                                 Message
  ----     ------     ----                  ----                                 -------
  Normal   Scheduled  6m18s                 default-scheduler                    Successfully assigned kube-system/efs-csi-node-d6sqn to ip-x.x.x.x.ec2.internal
  Normal   BackOff    6m15s                 kubelet, ip-x.x.x.x.ec2.internal  Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:
v2.0.0"
  Warning  Failed     6m15s                 kubelet, ip-x.x.x.x.ec2.internal  Error: ImagePullBackOff
  Normal   BackOff    6m15s                 kubelet, ip-x.x.x.x.ec2.internal  Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-drive
r-registrar:v1.3.0"
  Warning  Failed     6m15s                 kubelet, ip-x.x.x.x.ec2.internal  Error: ImagePullBackOff
  Warning  Failed     6m15s                 kubelet, ip-x.x.x.x.ec2.internal  Error: ImagePullBackOff
  Warning  Failed     6m4s (x2 over 6m17s)  kubelet, ip-x.x.x.x.ec2.internal  Error: ErrImagePull
  Warning  Failed     6m4s (x2 over 6m17s)  kubelet, ip-x.x.x.x.ec2.internal  Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driv
er:v1.0.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/aws-efs-csi-driver/manifests/v1
.0.0: no basic auth credentials
  Normal   Pulling    6m4s (x2 over 6m17s)  kubelet, ip-x.x.x.x.ec2.internal  Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.0
.0"
  Normal   Pulling    6m4s (x2 over 6m17s)  kubelet, ip-x.x.x.x.ec2.internal  Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registr
ar:v1.3.0"
  Warning  Failed     6m3s (x2 over 6m16s)  kubelet, ip-x.x.x.x.ec2.internal  Error: ErrImagePull
  Warning  Failed     6m3s (x2 over 6m17s)  kubelet, ip-x.x.x.x.ec2.internal  Error: ErrImagePull
  Normal   Pulling    6m3s (x2 over 6m17s)  kubelet, ip-x.x.x.x.ec2.internal  Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.0.0"
  Warning  Failed     6m3s (x2 over 6m17s)  kubelet, ip-x.x.x.x.ec2.internal  Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-
registrar:v1.3.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/csi-node-driver-registra
r/manifests/v1.3.0: no basic auth credentials
  Warning  Failed     6m3s (x2 over 6m16s)  kubelet, ip-x.x.x.x.ec2.internal  Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2
.0.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/livenessprobe/manifests/v2.0.0: no b
asic auth credentials
  Normal   BackOff    66s (x20 over 6m15s)  kubelet, ip-x.x.x.x.ec2.internal  Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-dr
iver:v1.0.0"
 
Is some image changed? Or some configurations that need to be done?

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): v1.16.8
- Driver version:

**Comment by mssachan** [comment]
Hitting same issue.
```
Normal   Pulling    82s (x2 over 98s)  kubelet, 172.31.73.109  Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.0.0"
  Warning  Failed     81s (x2 over 97s)  kubelet, 172.31.73.109  Error: ErrImagePull
  Normal   Pulling    81s (x2 over 97s)  kubelet, 172.31.73.109  Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.0.0"
  Normal   Pulling    81s (x2 over 97s)  kubelet, 172.31.73.109  Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v1.3.0"
  Warning  Failed     81s (x2 over 97s)  kubelet, 172.31.73.109  Error: ErrImagePull
  Warning  Failed     81s (x2 over 97s)  kubelet, 172.31.73.109  Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.0.0": rpc error: code = Unknown desc = Error reading manifest v1.0.0 in 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver: unauthorized: authentication required
  Warning  Failed     81s (x2 over 97s)  kubelet, 172.31.73.109  Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v1.3.0": rpc error: code = Unknown desc = Error reading manifest v1.3.0 in 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar: unauthorized: authentication required
  Warning  Failed     80s (x2 over 96s)  kubelet, 172.31.73.109  Error: ErrImagePull
  Warning  Failed     80s (x2 over 96s)  kubelet, 172.31.73.109  Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.0.0": rpc error: code = Unknown desc = Error reading manifest v2.0.0 in 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe: unauthorized: authentication required
  Normal   BackOff    66s (x2 over 96s)  kubelet, 172.31.73.109  Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.0.0"

```

**Comment by wongma7** [comment]
/lifecycle frozen

I think that if you are using the ECR overlay, to pull from ECR there has to be a Policy attached to the kubernetes node EC2 instance allowing pull from ecr

See also https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/294, I want to provide alternative push destination besides this ECR and docker hub

**Comment by KlockiLego** [comment]
In my case AWS SCP was blocking traffic to the ECR in us-west-2 from eu-central-1

```
# aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 602401143452.dkr.ecr.us-west-2.amazonaws.com

An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:sts::<your_account_number>:assumed-role/<role_name>/<instance_id> is not authorized to perform: ecr:GetAuthorizationToken on resource: * with an explicit deny in a service control policy

# docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.2.0
```
change daemonset container image from:
image: 602401143452.dkr.ecrus-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.2.0
to 
image: 602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/aws-efs-csi-driver:v1.2.0


similar problem:
https://github.com/aws/amazon-vpc-cni-k8s/issues/1217
