### ISSUE TITLE
create directory when volume path is not found

### ISSUE THREAD

**Issue by jurgenweber** [kubernetes-sigs/aws-efs-csi-driver#248]
**Is your feature request related to a problem?/Why is this needed**

as per https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/239
when a pod is attempting to mount a volume path, if the directory does not already exist it fails with a 'no such file or directory' error. My expectation would be that the directory is created.

/feature

**Describe the solution you'd like in detail**
I would like it, that if a PV with a mount path is created.. If the directory is not found, it is created.

**Describe alternatives you've considered**
Mounting it manually and creating.
Use accesspoints, but maybe not necessary all the time.

**Additional context**
If the solution is to use mount targets then I think this feature should be deprecated.

**Comment by wongma7** [comment]
I don't think the driver should touch anything in your volume or create access points unless explicitly asked to. There is a little bit of overlap with this request and the dynamic provisioning feature which I think is in progress of being designed still.

**Comment by wongma7** [comment]
We are discussing this a little bit in FSx and I would like the solution to be consistent for all drivers, please join https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/162#discussion_r513098426, 


When I say in the above comment "unless explicitly asked to", that could mean a new volumeAttribute to toggle behavior between "Fail if directory does not exist" and "Create the directory does not exist" like hostPath's Directory and DirectoryOrCreate respectively https://kubernetes.io/docs/concepts/storage/volumes/

**Comment by jurgenweber** [comment]
Ok, I kinda of agreed' with your first post and it doesn't really belong here. I figured the best way to move forward would be to reomve the feature all together and force access points, etc.

**Comment by wongma7** [comment]
Yeah, so I backtracked alittle bit because for FSx they don't have a concept of access points to abstract paths, so if we end up adding this feature to FSx then I figured we could consider porting it to EFS.  THe problem is then we are increasing EFS's api surface and that could be more confusing than useful if folks have to figure out path, access point, subpath....etc.

**Comment by moorthy156** [comment]
accesspoint limitation are hurting for switching to dynamic provisioning, looking forward to this future as well
