### ISSUE TITLE
Add documentation about amazon-efs-utils depencency

### ISSUE THREAD

**Issue by emanuelr93** [kubernetes-sigs/aws-efs-csi-driver#249]
The need to have the amazon-efs-utils binary is not clearly specified in the current version of the README.
From the tests I performed, the binary is mandatory for this driver to work. Shouldn't that be clarified in the documentation?

**Comment by wongma7** [comment]
We assume that you are running it containerized with the binary installed. Still I agree it is worth calling out this dependency, since technically you can mount EFS without it if you use vanilla NFS.
