### ISSUE TITLE
Can different PV be associated to same EFS volume

### ISSUE THREAD

**Issue by kamit78** [kubernetes-sigs/aws-efs-csi-driver#254]
**Current Setup**
Right now we created a PV with EFS volume id that bound to pvc in a namespace as N1 wherein pods mounts this pvc to read and write data to EFS

Scenario
Now create a another PV resource with volume id of same EFS, would it bind to PVC in some different namespace(N2) ? 

To be concise following is my query--

Can different PV connect same EFS, which further bound to different PVC's in different namespaces ?

**Comment by wongma7** [comment]
Yes!
