### ISSUE TITLE
Update AL2 Image Version

### ISSUE THREAD

**Issue by PatrickXYS** [kubernetes-sigs/aws-efs-csi-driver#264]
**Is your feature request related to a problem?/Why is this needed**
Update AL2 Image version which serves as Base Image of EFS Image

/feature

**Describe the solution you'd like in detail**
Change [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v1.0.0/Dockerfile#L27)
From 
```
amazonlinux:2.0.20200602.0
```
to 
```
amazonlinux:2.0.20200722.0
```

What's the whole test process in order to publish new EFS image?

**Comment by wongma7** [comment]
/assign

https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/290

also need to update efs-utils

**Comment by PatrickXYS** [comment]
Checked latest v1.1.1, it's already been updated

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v1.1.1/Dockerfile#L34

/close
