### ISSUE TITLE
Add AWS EKS 1.18 support for Helm Chart

### ISSUE THREAD

**Issue by xposix** [kubernetes-sigs/aws-efs-csi-driver#267]
/kind bug

**What happened?**
Helm Chart installation fails with the following message when used against a new AWS EKS 1.18 cluster:
```
$ helm install aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CSIDriver "efs.csi.aws.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-efs-csi-driver"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
```

**What you expected to happen?**
To finish installation without any problem

**How to reproduce it (as minimally and precisely as possible)?**
Create an empty new cluster and try to install this CSI driver with Helm
```
helm install aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver
```
**Anything else we need to know?**:
After installing a cluster from scratch this is what I find:
```
$ kubectl get CSIDriver 
NAME              ATTACHREQUIRED   PODINFOONMOUNT   MODES        AGE
efs.csi.aws.com   false            false            Persistent   9m19s
```

More detailed:
```
$ k get CSIDriver/efs.csi.aws.com -o yaml 
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"CSIDriver","metadata":{"annotations":{},"name":"efs.csi.aws.com"},"spec":{"attachRequired":false}}
  creationTimestamp: "2020-10-18T14:56:47Z"
  managedFields:
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:attachRequired: {}
        f:podInfoOnMount: {}
        f:volumeLifecycleModes:
          .: {}
          v:"Persistent": {}
    manager: kubectl
    operation: Update
    time: "2020-10-18T14:56:47Z"
  name: efs.csi.aws.com
  resourceVersion: "168"
  selfLink: /apis/storage.k8s.io/v1/csidrivers/efs.csi.aws.com
  uid: 0081d765-cd95-40e0-adf9-19b71cfa2294
spec:
  attachRequired: false
  podInfoOnMount: false
  volumeLifecycleModes:
  - Persistent
```

If I disable the `helm/templates/csidriver.yaml` the installation is finished successfully.

**Environment**
- Kubernetes version (use `kubectl version`): EKS 1.18
- Driver version: 1.0.0

**Comment by maateen** [comment]
It seems that EKS 1.18 comes with built-in (probably in-tree, please lemme know if I'm wrong here) `efs.csi.aws.com` **CSIDriver**. This helm chart wants to install its own version of the **CSIDriver** which actually triggers the error.

```shell
$ kubectl describe CSIDriver efs.csi.aws.com
```

**So, what is the fix?**

Simply delete the built-in **CSIDriver**:

```shell
$ kubectl delete CSIDriver efs.csi.aws.com
```

**Comment by xposix** [comment]
Alright, but that's hardly a fix, right? The Helm should decide if it needs to install or not the CSI driver depending on the version.

**Comment by maateen** [comment]
@xposix it's a way around actually. But I am wondering how it is possible for Helm to identify already installed components.

**Comment by Klohto** [comment]
@maateen I don't have a EKS 1.18 cluster on hand to test the CSIDriver issue, but there isn't a way how to get Helm to "appropriate" a resource that wasn't created by Helm. Atleast not automatically.
The _correct_ way is to document the need for deletion or use an in-place approach of labelling and annotating the resource before installing the Helm chart.

I have recently log similar issue againts stakater/reloader here - https://github.com/stakater/Reloader/issues/173.
That should help you in documenting a workaround for this.

One other method would be to use in-built Helm Capabilites variable https://helm.sh/docs/chart_template_guide/builtin_objects/ to determine if CSIDriver should be installed or use some Chart variable that will control this. Althrough this way is getting very close to "patchworking" territory and the whole Chart configuration could end up with a bunch of "turn this on if...", etc.

By the way, the described problem in the linked issue affects aws-efs-csi-driver as well. The _helpers.tpl file is outdated and CSIDriver isn't even tagged at all.

**Comment by mteodori** [comment]
I see the same issue on clusters created with 1.17 and specifically the issue appears on newly created ones that have version v1.17.9-eks-a84824 while the issue was not present in the former ones I created that have version v1.17.9-eks-4c6976, is there a CHANGELOG with release notes where it's documented what changed between these two versions?

**Comment by jwesolowski-rms** [comment]
@mteodori I've not been able to find this mentioned anywhere in a CHANGELOG for EKS (which is quite frustrating), but I think it is related to this: https://aws.amazon.com/blogs/aws/new-aws-fargate-for-amazon-eks-now-supports-amazon-efs/
> We released a generally available version of the Amazon EFS CSI driver for EKS in July 2020. The Amazon EFS CSI driver makes it easy to configure elastic file storage for both EKS and self-managed Kubernetes clusters running on AWS using standard Kubernetes interfaces. If a Kubernetes pod is terminated and relaunched, the CSI driver reconnects the EFS file system, even if the pod is relaunched in a different AWS Availability Zone.​ **When using standard EC2 worker nodes, the EFS CSI driver needs to be deployed as a set of pods and DaemonSets. With this new update, for Fargate this step is not required and you do not need to install the EFS CSI driver, as it is installed in the Fargate stack and support for EFS is provided out of the box.** Customers can use EFS with Fargate for EKS without spending the time and resources to install and update the CSI driver.

> For now you need to add the EFS CSIDriver object shown above to your cluster so Kubernetes can discover the driver that Fargate automatically installs. **In the future, this manifest will be added by default to EKS clusters.**

I'm assuming we are sufficiently *in the future* and that is why this is happening. I tested changing the CSIDriver resource to a `pre-install` hook with `"helm.sh/hook-delete-policy": before-hook-creation`. It will delete the default EKS-provisioned CSIDriver on first install and recreate it from the Helm spec (I also added some logic to better support 1.18 since CSIDriver is now GA):

```
{{- if .Capabilities.APIVersions.Has "storage.k8s.io/v1/CSIDriver" }}
apiVersion: storage.k8s.io/v1
{{- else }}
apiVersion: storage.k8s.io/v1beta1
{{- end }}
kind: CSIDriver
metadata:
  name: efs.csi.aws.com
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  attachRequired: false
```

@leakingtapan Do you think this would be an acceptable way forward to support EKS 1.17 and EKS 1.18?

**Comment by vothanhbinhlt** [comment]
I have had same issue when I created new AWS EKS version 1.17

**Comment by zxkane** [comment]
Any official solution/to do action for this problem, the built-in efs csi driver breaks [the installation guide](https://github.com/kubernetes-sigs/aws-efs-csi-driver#installation).

Why closed the issue without resolving the problem?

**Comment by zxkane** [comment]
Sorry for the noise.

I see the fix for helm chart already is ready. Any plan to release a new helm chart version(still pin the efs-csi-driver image to v1.0.0) to resolve the installation problem in newly created EKS cluster via Helm?
