### ISSUE TITLE
How does the driver know which PV to bind to any given PVC?

### ISSUE THREAD

**Issue by duncangrist** [kubernetes-sigs/aws-efs-csi-driver#277]
I'm confused as to how the driver knows which PV to bind to any given PVC.

e.g. if you look at the following example which maps two volumes into a specific pod:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/volume_path/specs/example.yaml
there's nothing that I can see which connects each PVC to the specific PV. 

Obviously both the PVC and PV share the same StorageClass, but this is the same across both volumes so I can't see how this could be being used to match everything up.

Who someone be so kind as to let me know what I'm missing?!

Thanks, Duncan

**Comment by wongma7** [comment]
It creates the PV with claimRef already set https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/master/controller/controller.go#L1422. you can read more about claimref here: https://kubernetes.io/docs/concepts/storage/persistent-volumes/

BTW, technically it is not the driver but the external-provisioner sidecar container that handles ensuring the PVC and PV bind. driver doesn't know PVs exist

**Comment by duncangrist** [comment]
Hi @wongma7 - thanks get getting back to me - I think I understand this now.

My confusion stemmed from the fact that in the example that I linked it appears important that PV `efs-pv1` is eventually mounted at `/data-dir1` and that PV `efs-pv2` is mounted at `/data-dir2` but there is nothing in the yaml that explicitly connects each claim to the correct volume to ensure this.

Whilst it appears important that that binding is set explicitly, what I now realise is that it doesn't *initially* matter which PVC binds to which PV, as long as that binding is remembered or *retained* through multiple instances of the pod - for example if it was managed by a replicaset.

Thanks for your help - and please correct me if I'm still incorrect!!

**Comment by wongma7** [comment]
hmm yes so the example is a bit flawed because there is technically no guarantee efs-pv1 gets bound to efs-claim1, without claimRef being set.

> but there is nothing in the yaml that explicitly connects each claim to the correct volume to ensure this.

You have to go from volumeMounts to volumes to PVC to PV.

e.g. the first volumeMount entry refers to volume `name: efs-volume-1`. Then if you scroll down to the volumes entries, you can see that efs-volume-1 refers to pvc efs-claim1.

  - name: efs-volume-1
    persistentVolumeClaim:
      claimName: efs-claim1
