### ISSUE TITLE
Allow Mounting via IP

### ISSUE THREAD

**Issue by afrazkhan** [kubernetes-sigs/aws-efs-csi-driver#285]
**Is your feature request related to a problem?/Why is this needed**

It is not possible to mount a share from a different VPC, since DNS resolution for the share will not be available. Using this driver results in:

```
Output: Failed to resolve "[FS-ID].efs.[REGION].amazonaws.com" - check that your file system ID is correct
```

/feature

**Describe the solution you'd like in detail**

It would be great if we could specify an IP instead, since this mounting via IP works manually.

**Describe alternatives you've considered**

The IP could be added to the machine's `/etc/hosts` file, but that seems hacky and unnecessary.

**Comment by mi5key** [comment]
We are also unable to mount EFS in K8s due to the fact that we have DNS Hostnames turned off in our AWS VPC as we use our own internal DNS.

**Comment by 037g** [comment]
We also need IP based mounting. Modifying the `/etc/hosts` files on the nodes failed to work.

```
Events:
  Type     Reason       Age                From                                               Message
  ----     ------       ----               ----                                               -------
  Normal   Scheduled    27s                default-scheduler                                  Successfully assigned default/efs-app to ip-10-220-7-159.FQDN.com
  Warning  FailedMount  10s (x6 over 26s)  kubelet, ip-10-220-7-159.FQDN.com  MountVolume.SetUp failed for volume "efs-pv" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = Could not mount "[FS-ID]:/" at "/var/lib/kubelet/pods/21fbc032-c788-4445-886c-23061346cae2/volumes/kubernetes.io~csi/efs-pv/mount": mount failed: exit status 1
Mounting command: mount
Mounting arguments: -t efs -o tls [FS-ID]:/ /var/lib/kubelet/pods/21fbc032-c788-4445-886c-23061346cae2/volumes/kubernetes.io~csi/efs-pv/mount
Output: Failed to resolve "[FS-ID].efs.us-east-1.amazonaws.com" - check that
```

**Comment by chrishenzie** [comment]
Brainstorming an implementation idea, is it reasonable to allow users to supply an IPv4 / IPv6 for `PersistentVolume.spec.csi.volumeHandle`, and then adjust the arguments we supply to the mounter?

**Comment by tegataiprime** [comment]
We're facing the same issue.  Being able to provide an IP Address for the EFS Filesystem would be a great help.  We're especially interested in using the AWS EFS CSI Driver to provide support for encryption-in-transit and IAM for access control.

**Comment by wongma7** [comment]
That error is coming from efs-utils and efs-utils seems to expect that whatever IP/DNSname/FSID you give it can somehow be linked back to the FSID: https://github.com/aws/efs-utils/blob/master/src/mount_efs/__init__.py#L1518
Of course the simplest thing to pass to efs-utils is the FSID itself which is what we are currently doing/expecting.

To be more flexible, first step is to remove this check here https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/aad2f30e0624ccdfcaaa98b1f86ae5d88c711f48/pkg/driver/node.go#L338, but given all the checks in efs-utils I doubt it will be enough, it might require changes in efs-utils.

The doc page for mounting via IP address says to use mount.nfs and in that case efs-utils isn't even involved:https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-ip-addr.html. If you use mount.nfs then you lose tls

/help-wanted

**Comment by tsarna** [comment]
I also run my own DNS within AWS, but have it configured to forward amazonaws.com to 169.254.169.253 so that I can use these kinds of internal AWS hostnames. Perhaps this is useful to you as a workaround.

**Comment by maxc0c0s** [comment]
Would also be great for us. Our containers in one VPC need access to an EFS through VPC Peering

**Comment by maxc0c0s** [comment]
> I also run my own DNS within AWS, but have it configured to forward amazonaws.com to 169.254.169.253 so that I can use these kinds of internal AWS hostnames. Perhaps this is useful to you as a workaround.

Can you give a bit more details on how you did it. I tried a lot of things with Route53 Resolvers but without success.

Thanks!

**Comment by tegataiprime** [comment]
PodSpec HostAliases looks promising:
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#hostalias-v1-core
The Helm Chart for AWS EFS CSI Driver does present a host aliases map:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml

**Comment by chrishenzie** [comment]
I have a working solution of mounting by IP in this PR: https://github.com/aws/efs-utils/pull/87. Please see the description for the approach.

An advantage of this solution is the user does not need to manage IP addresses; so long as they have a mount target in the same subnet as the instance (and security groups configured for access) it will work.

In order to use this solution:
- The image will need to install the `botocore` python library
- The container will need access to the [`elasticfilesystem:DescribeMountTargets`](https://docs.aws.amazon.com/efs/latest/ug/API_DescribeMountTargets.html) API

On the CSI driver side, the plan is to pass this `dnshostnamesdisabled` flag as a mount option in the PV spec, which will get passed to the `mount.efs` command installed by the efs-utils package.

**Comment by calebplum** [comment]
For anyone else trying to use the efs-csi driver in a VPC where DNS Hostnames is disabled (such as when using your own DNS servers), you can force the driver's deployment to use the default VPC resolver by adding the following configuration to `daemonset/efs-csi-node.spec.template.spec`. `169.254.169.253` is the VPC's default resolver, which from my testing is available by IP even when it's disabled in the VPC.

```yaml
hostNetwork: true
dnsPolicy: "None"
dnsConfig:
  nameservers:
    - 169.254.169.253
```

No manual editing of hosts files or maintaining hardcoded IPs required :)

Source: #129
