### ISSUE TITLE
Generate kustomize from helm 

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-efs-csi-driver#287]
**Is your feature request related to a problem?/Why is this needed**
Manual mirroring kustomize and helm to keep them in sync is impossible

/feature

**Describe the solution you'd like in detail**
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/Makefile#L124

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by krmichel** [comment]
@yashvardhan-kukreja Are you actively working on adding this change?  If not I can do it.  I made the change for the ebs driver.

**Comment by yashvardhan-kukreja** [comment]
> @yashvardhan-kukreja Are you actively working on adding this change?  If not I can do it.  I made the change for the ebs driver.

I was about to look into this by 5th Jan.

**Comment by yashvardhan-kukreja** [comment]
@wongma7  sorry for the late reply (was swamped previously). I have raised a PR solving solving this issue .
PTAL. If it looks good, then I'll add the corresponding documentation accordingly.
Thanks!
