### ISSUE TITLE
release helm chart to be able to deploy to EKS 1.17+

### ISSUE THREAD

**Issue by zxkane** [kubernetes-sigs/aws-efs-csi-driver#289]
/kind bug

**What happened?**

The bug of helm chart has been fixed in https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/267. But there is no new release helm chart to pick up the fix.

See below error when following the readme of this project to install EFS CSI driver to EKS 1.18,

```
❯ helm install aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CSIDriver "efs.csi.aws.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-efs-csi-driver"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
```

**What you expected to happen?**

It’s the official doc to suggestion how deploying EFS CSI driver to EKS, but it does NOT work! Pls fix it soon!

**How to reproduce it (as minimally and precisely as possible)?**

Following your doc to deploy to EKS 1.17+.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.19
- Driver version: v1.0.0

**Comment by terraform-class** [comment]
Getting the same error. Any fix for this?

**Comment by wongma7** [comment]
I'll release 0.3.1 this week, I'm also looking at https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/265, https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/288 and https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/291.

**Comment by emmaroberts-nbs** [comment]
Do you have any further updates on this? 

I'm experiencing the same problem which is causing a blocker for me using EFS in EKS.

I'm using terraform with the helm provider as follows:
```hcl
resource "helm_release" "aws_efs_cis_driver" {
  name            = "aws-efs-csi-driver"
  repository    = "https://kubernetes-sigs.github.io/aws-efs-csi-driver"
  chart            = "aws-efs-csi-driver"
  namespace  = "kube-system"
}
```

**Comment by emmaroberts-nbs** [comment]
My workaround is to use the kustomize terraform provider, see below

```hcl
terraform {
  required_providers {
    kustomization = {
      source = "kbst/kustomization"
      version = "0.3.0"
    }
  }
}
provider "kustomization" {
  kubeconfig_raw = local.kubeconfig
}

data "kustomization_build" "aws_efs_csi_driver" {
  path = "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.0"
}

resource "kustomization_resource" "aws_efs_csi_driver" {
  for_each = data.kustomization_build.aws_efs_csi_driver.ids

  manifest = data.kustomization_build.aws_efs_csi_driver.manifests[each.value]
}
```

Hope this helps while the helm chart isn't working

**Comment by vothanhbinhlt** [comment]
I got the same issue. Any update?

**Comment by wongma7** [comment]
After https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/292 merges, I will make a new helm chart release to include all the recent helm chart changes like https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/260, https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/261, #267, https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/288, etc.

See also https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/265.

Apologies that the helm chart hasn't been updated in so long, it will be fully automated soon.

**Comment by maateen** [comment]
This could be a quick workaround:

```
$ kubectl delete CSIDriver efs.csi.aws.com
```

**Comment by qwinkler** [comment]
@wongma7 Sir, could you please tell, what is the expected completion date (like a few weeks, or a few years)?

**Comment by wongma7** [comment]
ETA is end of this week. The main blocker is https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/296 to disable controller component (dynamic provisionig is not ready for release so this controller would not do anything) and upgrade test (i.e. if i do helm upgrade from current chart release 0.1.0 to the new 1.0.0 nothing breaks)

**Comment by wongma7** [comment]
Chart 1.0.0 has been released.  The driver version (appVersion) is still 1.0.0, so it does NOT include the recent driver changes like dynamic provisioning or config dir location change. It works for me even if EFS csidriver is on the cluster. 
```
helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver/
helm install aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver

NAME              	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                   	APP VERSION
aws-efs-csi-driver	default  	1       	2021-01-14 14:02:37.161235851 -0800 PST	deployed	aws-efs-csi-driver-1.0.0	1.0.0 
```
---
Details:

This was a manual release since #296 and #291 were delayed too much. I really wanted it to be automated to avoid the issues of manual release that messed up our index.yaml in the first place, but I think this one was done correctly:
```
git checkout 9c4d851c1ecebf1d3e2a44c2585426496e4de484
helm package --version 1.0.0 --app-version 1.0.0 ./helm/
cr upload --release-name-template "helm-chart-{{ .Name }}-{{ .Version }}" --commit 9c4d851c1ecebf1d3e2a44c2585426496e4de484 --owner kubernetes-sigs --git-repo aws-efs-csi-driver --token $TOKEN -p ./
cr index --release-name-template "helm-chart-{{ .Name }}-{{ .Version }}" --owner kubernetes-sigs --git-repo aws-efs-csi-driver --token $TOKEN --charts-repo https://kubernetes-sigs.github.io/aws-efs-csi-driver/ -i ./index.yaml -p ./ --push
```
