### ISSUE TITLE
Upgrade to efs-utils v1.28.2

### ISSUE THREAD

**Issue by dahu33** [kubernetes-sigs/aws-efs-csi-driver#290]
**Is your feature request related to a problem?/Why is this needed**
IAM auth doesn't work in my environment where only IMDSv2 is enabled, most likely because `efs-utils` version is a bit behind. [v1.28.2](https://github.com/aws/efs-utils/releases/tag/v1.28.2) seems to fix the issue so it would be nice to upgrade.

/feature

**Describe the solution you'd like in detail**
Upgrade to efs-utils v1.28.2

**Comment by wongma7** [comment]
/assign

the PR https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/268 is lacking CLA, but I will ensure we have a more recent version in time for next release.

**Comment by wongma7** [comment]
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/Dockerfile#L35 1.2 will have 1.28.2
