### ISSUE TITLE
Dynamic PV tests flaky

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-efs-csi-driver#303]
/kind bug
https://testgrid.k8s.io/provider-aws-efs-csi-driver#e2e-test&width=20

for example, README fix failing tests: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/301

**Comment by wongma7** [comment]
@kbasv will have to fix before releasing

**Comment by wongma7** [comment]
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/296#issuecomment-759789559

Here is one where on a fresh deploy driver on a specific node the first two mount.nfs calls hanged and all subsequent calls hanged. More logs available on request.

I0113 21:37:11.503578       1 mount_linux.go:146] Mounting cmd (mount) with arguments (-t efs -o accesspoint=fsap-03916e91c53b60b26,tls fs-67749663:/ /var/lib/kubelet/pods/ccf9b03a-e22e-4751-b55c-26e664e039ed/volumes/kubernetes.io~csi/pvc-817d4636-19c4-4aa1-9376-1004dda3ea95/mount)
I0113 21:39:12.028120       1 mount_linux.go:146] Mounting cmd (mount) with arguments (-t efs -o accesspoint=fsap-03916e91c53b60b26,tls fs-67749663:/ /var/lib/kubelet/pods/ccf9b03a-e22e-4751-b55c-26e664e039ed/volumes/kubernetes.io~csi/pvc-817d4636-19c4-4aa1-9376-1004dda3ea95/mount)

**Comment by duncangrist** [comment]
Hi there.

Am I right in thinking that this is the issue holding up the release of dynamic provisioning?
Looks to me that the feature [is merged](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/312) but the (currently) latest Helm chart (1.1.0) doesn't install a version with the feature enabled.

We're currently waiting on dynamic provisioning support being available before we roll out our next generation of EKS-based k8s clusters onto which we want to dynamically-provision EFS storage.
Given this feature doesn't seem to have moved anywhere for over month now, I thought it would be good to see what the latest is with the aim of trying work out whether it is worth us waiting for this feature or trying to find an alternative instead.

Any light you can shed on the subject and its timeline would be much appreciated :)

Duncan

**Comment by wongma7** [comment]
@duncangrist this is one issue, I'll try to add blocking issues/PRs to project/milestone for more transparency.

I can't share an ETA at this time. Personally I can say that this issue hasn't been solved and I'm hesitant to release the feature with this bug since it seems to require a node restart to fix, driver restart is not enough, which is of course disruptive

**Comment by wongma7** [comment]
/reopen

not sure if fixed yet

**Comment by wongma7** [comment]
Seems fine now after I updated the scripts. The tests themselves have not changed but the version under test went from 1.17.0 to 1.18.10 so it might have been a kubernetes/kubelet side bug. I checked changelog and didn't find anything. Anyway, we should be running the upstream 1.18.x tests against 1.18.x clusters so any other configuration you could argue is invalid.

**Comment by duncangrist** [comment]
> @duncangrist this is one issue, I'll try to add blocking issues/PRs to project/milestone for more transparency.
> 
> I can't share an ETA at this time. Personally I can say that this issue hasn't been solved and I'm hesitant to release the feature with this bug since it seems to require a node restart to fix, driver restart is not enough, which is of course disruptive

Thanks for the update.
Unfortunately in the preceding days I've had to make a decision to unblock these new environments and have gone with [nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) instead. This seems to already work fine with EFS and dynamic provisioning.

I would definitely be interested to know the essential differences between "aws-efs-csi-driver" and "nfs-subdir-external-provisioner"? Do you have  a view on that?

**Comment by wongma7** [comment]
@duncangrist the main difference is that you will not benefit from EFS specific features like encryption in transit or access points. Otherwise, mounting EFS as NFS PVs via nfs-subdir-external-provisioner is a totally valid use-case and the fundamental functionality of reading/writing to shared filesystems will work exactly the same.
