### ISSUE TITLE
missing latest helm chart version

### ISSUE THREAD

**Issue by dsaydon90** [kubernetes-sigs/aws-efs-csi-driver#307]
/kind bug

**What happened?**
the version in the helm repo `aws-efs-csi-driver` is not include that latest changes for the `serviceaccount` creation and for the `conroller` creation support:

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/dfab8556194671bbd00b41d3ed2738701ac3484e/helm/values.yaml#L74-L84

```
helm search repo aws-efs-csi-driver
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                        
aws-efs-csi-driver/aws-efs-csi-driver   1.0.0           1.0.0           A Helm chart for AWS EFS CSI Driver
```

**Comment by renanqts** [comment]
Please, provide a new release.

**Comment by wongma7** [comment]
This is intentional, there is still a bunch of documentation and security related fixes that need to go in
