### ISSUE TITLE
Does this driver work on vanilla k8s? (lack of docs)

### ISSUE THREAD

**Issue by moonek** [kubernetes-sigs/aws-efs-csi-driver#317]
Can I use this driver on my own k8s cluster in AWS other than EKS nodes?
The credential management method(secrets) used by the general csi driver and the efs driver look different.
I can't find anything about credential in the installation documentation.

/triage support

**Comment by wongma7** [comment]
Yes you can, our docs should call out EKS specific features like IAM ofr service accounts and if not that's a bug.

Do you mean credentials for the controller?

**Comment by moonek** [comment]
@wongma7 Yes. I'm curious about how to set credentials to provisioner to create efs volume using aws api.

**Comment by moonek** [comment]
I confirmed that it only supports static provisioning.
I understood that there is no credentails setting.
In the vanailla k8s the current driver is expected to work well.
