### ISSUE TITLE
helm chart 1.1.0 has breaking changes

### ISSUE THREAD

**Issue by dsaydon90** [kubernetes-sigs/aws-efs-csi-driver#335]
/kind bug

**What happened?**
on the new helm release `1.1.0` there is no way to provide `serviceAccount`

**What you expected to happen?**
I'm using [iam-roles-for-service-accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) so I really need the ability to attach `serviceAccount`for the `efs-csi-node` pod

**Anything else we need to know?**:
compare:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L74-L81
with
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v1.1.0/helm/values.yaml

**Comment by wongma7** [comment]
master is newer, technically nothing has broken. Also that serviceAccount is referring to the controller component which is only in master, not in v1.1.0 yet.
I think this would be a feature request like  https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/316

**Comment by diranged** [comment]
This should be a super simple issue to fix - the node pods definitely need to use their own service account as a default behavior. This is already how the EBS driver works, and is the standard behavior for almost all helm charts. Being forced to grant the `default` ServiceAccount in our namespace with host level privileges is not a good security practice.
