### ISSUE TITLE
CSIDriver missing after upgrading helm chart

### ISSUE THREAD

**Issue by agrahamlincoln** [kubernetes-sigs/aws-efs-csi-driver#338]
/kind bug

**What happened?**

Upgrading helm chart to 1.0.0+ causes CSIDriver to not be registered

**What you expected to happen?**

the CSIDriver should be registered after doing a helm upgrade

**How to reproduce it (as minimally and precisely as possible)?**

Install v0.1.0 of the helm chart
`kubectl get CSIDriver` - see that it's listed
Install v1.0.0 of the helm chart
`kubectl get CSIDriver` - it's missing!

**Anything else we need to know?**:

I am happy to help provide logs or other relevant details, but I couldn't find any smoking guns. Help me help you :)

I did see these logs in kubelet, but they seem to show up regardless of the version and I don't think they're relevant or a problem:
```
Feb 12 18:24:03 ip-172-60-0-231.ec2.internal kubelet[3811]: I0212 18:24:03.364064    3811 csi_plugin.go:178] kubernetes.io/csi: registrationHandler.DeRegisterPlugin request for plugin efs.csi.aws.com
Feb 12 18:24:04 ip-172-60-0-231.ec2.internal kubelet[3811]: I0212 18:24:04.327567    3811 csi_plugin.go:99] kubernetes.io/csi: Trying to validate a new CSI Driver with name: efs.csi.aws.com endpoint: /var/lib/kubelet/plugins/efs.csi.aws.com/csi.sock versions: 1.0.0
Feb 12 18:24:04 ip-172-60-0-231.ec2.internal kubelet[3811]: I0212 18:24:04.327599    3811 csi_plugin.go:112] kubernetes.io/csi: Register new plugin with name: efs.csi.aws.com at endpoint: /var/lib/kubelet/plugins/efs.csi.aws.com/csi.sock
Feb 12 18:24:04 ip-172-60-0-231.ec2.internal kubelet[3811]: E0212 18:24:04.352485    3811 nodeinfomanager.go:567] Invalid attach limit value 0 cannot be added to CSINode object for "efs.csi.aws.com"
```

**Environment**
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version:

```
$ kubectl get daemonset -n kube-system efs-csi-node -o jsonpath="{..image}"
amazon/aws-efs-csi-driver:v1.0.0 quay.io/k8scsi/csi-node-driver-registrar:v1.3.0 quay.io/k8scsi/livenessprobe:v2.0.0
```

these image versions don't seem to change when going from the helm chart version 0.1.0 to 1.0.0
1.1.0 and 1.1.1 have the same issue.

**Comment by wongma7** [comment]
Yes, I have to backport the fix https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/324 into release-1.1 and release a new helm chart.

**Comment by agrahamlincoln** [comment]
helm chart 1.1.2 looks to resolve this issue for me. Thanks!

**Comment by yemkay** [comment]
We had same issue and had to specify volumeHandle in our PVC after creating accesspoint in the EFS file system. It solved the issue.
