### ISSUE TITLE
GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v1.Controller

### ISSUE THREAD

**Issue by okt2019** [kubernetes-sigs/aws-efs-csi-driver#342]
1、An error is reported when installing EFS controller by EKS in China, as follows:

$ kubectl get pod -n kube-system
NAME                                            READY   STATUS             RESTARTS   AGE
aws-load-balancer-controller-75dc47d495-vxnmv   1/1     Running            0          12d
aws-node-hgc44                                                       1/1     Running            0          12d
aws-node-n8smr                                                       1/1     Running            0          40d
coredns-58d46ddb7f-6mxgp                                    1/1     Running            0          12d
coredns-58d46ddb7f-pw8ts                                      1/1     Running            0          12d
ebs-csi-controller-b87964fbc-2nwhf                         4/4     Running            13         40d
ebs-csi-controller-b87964fbc-lmmdx                        4/4     Running            14         40d
ebs-csi-node-499l9                                                    3/3     Running            0          12d
ebs-csi-node-d8tfw                                                   3/3     Running            4          40d
efs-csi-controller-7fcbcbb5b8-4v4xs                        2/3     CrashLoopBackOff   9          25m
efs-csi-controller-7fcbcbb5b8-nqn98                       2/3     CrashLoopBackOff   9          25m
efs-csi-node-nfd54                                                   3/3     Running            0          25m
efs-csi-node-p2wsc                                                  3/3     Running            0          25m
filebeat-nchc4                                                           1/1     Running            0          12d
filebeat-sl485                                                            1/1     Running            0          17d
ingress-merge-76dc689d9c-9m2bf                          1/1     Running            0          12d
kube-proxy-8r2lv                                                      1/1     Running            0          12d
kube-proxy-zpcz2                                                     1/1     Running            0          41d

$ kubectl logs pod/efs-csi-controller-7fcbcbb5b8-nqn98 -n kube-system -c csi-provisioner
I0222 08:07:01.919174       1 csi-provisioner.go:121] Version: v2.0.2
I0222 08:07:01.919247       1 csi-provisioner.go:135] Building kube configs for running in cluster...
I0222 08:07:01.928755       1 connection.go:153] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I0222 08:07:01.929150       1 common.go:111] Probing CSI driver for readiness
I0222 08:07:01.929170       1 connection.go:182] GRPC call: /csi.v1.Identity/Probe
I0222 08:07:01.929176       1 connection.go:183] GRPC request: {}
I0222 08:07:01.931292       1 connection.go:185] GRPC response: {}
I0222 08:07:01.931341       1 connection.go:186] GRPC error: <nil>
I0222 08:07:01.931350       1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I0222 08:07:01.931354       1 connection.go:183] GRPC request: {}
I0222 08:07:01.931756       1 connection.go:185] GRPC response: {"name":"efs.csi.aws.com","vendor_version":"v1.1.1-dirty"}
I0222 08:07:01.931807       1 connection.go:186] GRPC error: <nil>
I0222 08:07:01.931817       1 csi-provisioner.go:182] Detected CSI driver efs.csi.aws.com
W0222 08:07:01.931824       1 metrics.go:142] metrics endpoint will not be started because `metrics-address` was not specified.
I0222 08:07:01.931833       1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0222 08:07:01.931845       1 connection.go:183] GRPC request: {}
I0222 08:07:01.932189       1 connection.go:185] GRPC response: {}
I0222 08:07:01.932241       1 connection.go:186] GRPC error: <nil>
I0222 08:07:01.932250       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0222 08:07:01.932255       1 connection.go:183] GRPC request: {}
I0222 08:07:01.932645       1 connection.go:185] GRPC response: {}
I0222 08:07:01.932703       1 connection.go:186] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v1.Controller
F0222 08:07:01.932721       1 csi-provisioner.go:188] Error getting CSI driver capabilities: rpc error: code = Unimplemented desc = unknown service csi.v1.Controller

2、eks version:

Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

3、Use kubectl apply to install, the yaml file is as follows:

more stable/kustomization.yaml 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: xxxx.dkr.ecr.cn-northwest-1.amazonaws.com.cn/amazon/aws-efs-csi-driver 
    newTag: v1.1.1   #（I tried both v1.0.0 and v1.1.0, and the same error occurred）
  - name: xxxx.dkr.ecr.cn-northwest-1.amazonaws.com.cn/quay.io/k8scsi/livenessprobe
    newTag: v2.0.0
  - name: xxxx.dkr.ecr.cn-northwest-1.amazonaws.com.cn/quay.io/k8scsi/csi-node-driver-registrar
    newTag: v1.3.0

4、What are the special settings for installing EFS in EKS in Ningxia, China?

**Comment by okt2019** [comment]
5、error:
$  kubectl logs pod/efs-csi-controller-7fcbcbb5b8-nqn98 -n kube-system -c efs-plugin
I0222 08:05:35.105658       1 config_dir.go:62] Mounted directories do not exist, creating directory at '/etc/amazon/efs'
I0222 08:05:35.108302       1 driver.go:83] Node Service capability for Get Volume Stats Not enabled
I0222 08:05:35.112947       1 mount_linux.go:173] Cannot run systemd-run, assuming non-systemd OS
I0222 08:05:35.112956       1 mount_linux.go:174] systemd-run failed with: exit status 1
I0222 08:05:35.112966       1 mount_linux.go:175] systemd-run output: Failed to create bus connection: No such file or directory
I0222 08:05:35.113098       1 driver.go:114] Starting watchdog
I0222 08:05:35.113172       1 efs_watch_dog.go:174] Copying /etc/amazon/efs/efs-utils.conf since it doesn't exist
I0222 08:05:35.113247       1 efs_watch_dog.go:174] Copying /etc/amazon/efs/efs-utils.crt since it doesn't exist
I0222 08:05:35.114474       1 driver.go:120] Staring subreaper
I0222 08:05:35.114484       1 driver.go:123] Listening for connections on address: &net.UnixAddr{Name:"/var/lib/csi/sockets/pluginpro

**Comment by varunpalekar** [comment]
We are also facing same problem when deploying controller

**Comment by wongma7** [comment]
you need newer driver version 1.2 or 1.3 for dynamic provisioning

/remove-lifecycle stale
