### ISSUE TITLE
Update AL2 glibc / python packages

### ISSUE THREAD

**Issue by ccucui** [kubernetes-sigs/aws-efs-csi-driver#343]
**Is your feature request related to a problem?/Why is this needed**
We found that the docker image has vulnerabilities in the packages glibc and python.

/feature

**Describe the solution you'd like in detail**
We just update the Dockerfile adding this new line after installing the amazon-efs-utils:
`RUN yum update glibc python -y`

**Comment by wongma7** [comment]
In next 1.2 release, AL2 will be bumped to amazonlinux:2.0.20210219.0 and the packages will be 
python: Release     : 1.amzn2.0.3
glibc: Release     : 41.amzn2
