### ISSUE TITLE
Reduce scope of default tolerations

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-efs-csi-driver#363]
/kind bug

**What happened?** Exists is too much, we should tone it down in next helm chart release: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/758#issuecomment-786792738

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by wongma7** [comment]
/remove-lifecycle stale

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L105 still relevant

**Comment by sziegler-skyhook** [comment]
This is a major issue that prevents the EFS CSI pods from being evicted when a node is scaled down by the Kubernetes cluster-autoscaler. 

Allowing the pod to tolerate all taints seems to be in direct opposition to the way NotReady and NoExecute taints are designed in kubernetes and effects the operation of other Kubernetes system pods.

**Comment by sziegler-skyhook** [comment]
It looks like the default toleration was removed as part of Release v1.3.1 - this issue can likely be closed.

https://github.com/kubernetes-sigs/aws-efs-csi-driver/commit/494d75e7b1983774a6360d3fb330396a5f60ef85#diff-5d40e4554aa98fe9c294f9ad03acc2e515a612f31678f3c2282d6c8f19415b51

**Comment by wongma7** [comment]
yes it should be fixed by latest driver + helm chart
