### ISSUE TITLE
unrecognized volume context properties cause NodePublish to fail: volumes provisioned by 1.2 controller cannot be mounted by 1.1 nodes: 

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-efs-csi-driver#376]
/kind bug

**What happened?** I installed the 1.2 controller and then manually installed my daemonset at 1.1 and saw the following error:

  Warning  FailedMount  26s (x7 over 58s)  kubelet, ip-192-168-98-140.us-west-2.compute.internal  MountVolume.SetUp failed for volume "pvc-a137a207-bdc3-4f0c-a593-6966238451c1" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = InvalidArgument desc = Volume context property storage.kubernetes.io/csiProvisionerIdentity not supported

**What you expected to happen?** Volumes should be backwards compatible. Open to debate on this. Spec says nothing about how strict to be wrt parsing volume context, it's totally up to us.

**How to reproduce it (as minimally and precisely as possible)?** helm install everything at 1.2. downgrade daemonset to 1.1

**Anything else we need to know?**:

It's impossible to arrive at this scenario if you just follow the recommended install instructions. But I think it's worth treating as a bug since it's not obvious that this will happen.

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by v-sag** [comment]
Did you find any solution on this? I have the same error "kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = InvalidArgument desc = Volume context property storage.kubernetes.io/csiProvisionerIdentity"

**Comment by miketexas007** [comment]
I had similar issue. Any solutions for this please
