### ISSUE TITLE
Dynamic provisioning error. Says AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by azzy123** [kubernetes-sigs/aws-efs-csi-driver#392]
/triage support

**Comment by azzy123** [comment]
Trying to test dynamic provisioning with aws-efs-csi driver v1.2 . Have the necessary service account created with the IAM role and trust relationship.
Getting this error in the events://
5m20s       Warning   ProvisioningFailed     persistentvolumeclaim/efs-claim   failed to provision volume with StorageClass "efs-sc": rpc error: code = Internal desc = Failed to fetch File System info: describe File System failed: WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity

**Comment by azzy123** [comment]
Issue was in the IAM role and trust relationship specified

**Comment by oguzhanaygn** [comment]
hi @azzy123 , what's the problem exactly? I'm suffering the same problem right now.

**Comment by retraut** [comment]
I had the same problem. 
I was trying to set up EFS CSI charts with **kube2iam** and `node.podAnnotations`. No luck.
After that - I attached the IAM role **directly** to the worker IAM role - everything went smooth

**Comment by azzy123** [comment]
> hi @azzy123 , what's the problem exactly? I'm suffering from the same problem right now.

@oguzhanaygn  I was facing this issue because my IAM role(used by efs-csi-driver) did not specify the service account correctly in the trust relationship.

So two things are important here:
1. Make sure you have properly created the IAM role with appropriate policy and trust relationship.
2. The service account used by aws-efs-csi-driver pod is properly annotated with the IAM role arn . This IAM role will be used by the efs-csi-driver to connect and talk to aws EFS.

**Comment by holmesb** [comment]
Error "Failed to fetch File System info: Describe File System failed" when trying to provision dynamically on private EKS is fixed by my PR #585 that I submitted a week ago. Be great if someone could review\merge.

**Comment by Ropes** [comment]
For context of @azzy123's solution. The documentation to correctly create a the EBS-CSI Role can be found here: https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html

After creating the role, you'll need to select it when initializing the EBS-CSI Add-On, or edit the Add-On's settings to use the new role on a per cluster basis.

**Comment by qhyun2** [comment]
After fixing the role, I had to uninstall then reinstall the add-on for it to work for me.

**Comment by monikasinghrajput** [comment]
> Trying to test dynamic provisioning with aws-efs-csi driver v1.2 . Have the necessary service account created with the IAM role and trust relationship. Getting this error in the events:// 5m20s Warning ProvisioningFailed persistentvolumeclaim/efs-claim failed to provision volume with StorageClass "efs-sc": rpc error: code = Internal desc = Failed to fetch File System info: describe File System failed: WebIdentityErr: failed to retrieve credentials caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity

I am also facing the same issue how to fix it please help me

**Comment by adanecki** [comment]
I faced the same issue, when used terraform module **terraform-aws-iam/iam-role-for-service-accounts-eks** to create IAM Role.
For EBS, VPC and others it worked fine. but seems EFS-CSI doesn't like it

Trusts were defined as 
            "Condition": {
                "StringEquals": {
                    "oidc.eks.region-code.amazonaws.com/id/XXXXXX:aud": "sts.amazonaws.com",
                    "oidc.eks.region-code.amazonaws.com/id/XXXXXX:sub": "system:serviceaccount:*"
                }
            }
and it works for other , but for EFS had to explicit define the service account:
            "Condition": {
                "StringEquals": {
                    "oidc.eks.region-code.amazonaws.com/id/XXXXXX:aud": "sts.amazonaws.com",
                    "oidc.eks.region-code.amazonaws.com/id/XXXXXX:sub": "system:serviceaccount:kube-system:efs-csi-controller-sa"
                }
            }
After changing role trust condition, restarted EFS controller and all worked fine. 
Dynamic provisioning does it's job.

**Comment by monikasinghrajput** [comment]
I ve solve it
My problem was different

Monika Singh
