### ISSUE TITLE
Daemonset is using the default service account 

### ISSUE THREAD

**Issue by pre** [kubernetes-sigs/aws-efs-csi-driver#397]
The DaemonSet defined `privileged:true` and uses `hostPath` which require these permissions granted by a Pod Security Policy.

However, the DaemonSet does not use an explicit `serviceAccount` which means that the `default` service account of its namespace is implicitly used.

In order use this Helm chart with PSPs, as a workaround, the aws-efs-csi-driver needs to deployed into a k8s namespace of its own and the grant the `default` service account these permissions. 

It would be neat if an explicit `serviceAccount` could be configured for both the Deployment and the DaemonSet. This would allow using the same PodSecurityPolicy or different (depending on the level of folio hat). 

/bug

Related: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/243

**Comment by joelthompson** [comment]
This looks to be a duplicate of #316 / #335
