### ISSUE TITLE
driver name efs.csi.aws.com not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by discourseai** [kubernetes-sigs/aws-efs-csi-driver#399]
/kind bug

**What happened?**

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by GuiTeK** [comment]
We have the same issue when a new node is provisioned and added to the cluster. However, it seems there is a retry mechanism and the error goes away after a few minutes.
