### ISSUE TITLE
Failed to create newCsiDriverClient

### ISSUE THREAD

**Issue by Talkmapops** [kubernetes-sigs/aws-efs-csi-driver#400]
I am running efs driver version 1.0 on an EKS cluster with Kubernetes version 1.17. Occasionally on the cluster inconsistently. Typically, between a few weeks, and a few months I get the following error:

`Warning  FailedMount  36s (x25 over 46s)  kubelet, ip-10-34-161-32.us-east-2.compute.internal  MountVolume.MountDevice failed for volume "<pvcName>" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name efs.csi.aws.com not found in the list of registered CSI drivers`

The only temporary that has worked for me thus far is to uninstall the CSI driver on the cluster, and then re-install the csi driver using `kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr/?ref=release-1.0"
`

Any ideas on what could be causing this?

**Comment by wongma7** [comment]
/remove-lifecycle stale

If the driver is not registered then it probably crashed, you can check if it is running, got restarted, etc. There is a memory leak issue which could explain why it's erroring after x time https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/474

kubectl get po -n kube-system -o wide -l app=efs-csi-node
