### ISSUE TITLE
Dynamic Provisioner: Pods are getting stuck Terminating

### ISSUE THREAD

**Issue by darrenfurr** [kubernetes-sigs/aws-efs-csi-driver#401]
/kind bug

**What happened?**
We replaced our efs-provisioner with the aws-efs-csi-driver with dynamic provisioning. Pods would come up with no problems, but when scaling down via the HPA, they would hang in Terminating status. Eventually we would receive this message:

```
error killing pod: failed to "KillContainer" for "alpine-pvctest" with KillContainerError: "rpc error: code = Unknown desc = operation timeout: context deadline exceeded"
```

We reverted back to the efs-provisioner & the pods scaled down without error in ~30 seconds.

**What you expected to happen?**
The pods to scale down correctly.

**How to reproduce it (as minimally and precisely as possible)?**
- EKS 1.18 (m5a ec2 nodes), cluster-autoscaler, aws-efs-csi-driver v1.2
- kubectl apply deployment.yaml
[deployment.yaml.txt](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/6250006/deployment.yaml.txt)
- Change anything that requires the pod to scale down & back up. (I changed the image tag)
- You should see the new pod deploy successfully, but the previous pod will stay stuck in Terminating.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: 1.2

**Comment by haarchri** [comment]
we see the same issue in our installation - bump

**Comment by GuiTeK** [comment]
We also see the same issue intermittently! Sometimes they disappear after a few minutes, but sometimes they're really stuck for **hours** (if not days). We have to `--force --grace-period=0` to make the pods go away.

**Comment by stevenuray** [comment]
We're experiencing this as well

**Comment by spanktar** [comment]
Our error:

`Operation for "{volumeName:kubernetes.io/csi/efs.csi.aws.com^fs-6eb645da::fsap-0c53641ae55621a9a podName:18e11690-30
0a-4d6a-9926-47f6a00e648b nodeName:}" failed. No retries permitted until 2021-06-17 17:56:54.85433328 +0000 UTC m=+5085175.187850396 (durationBeforeRetry 4s). Error: "UnmountVolume.TearDown failed for volume "FOO" (Uni
queName: "kubernetes.io/csi/efs.csi.aws.com^fs-6eb645da::fsap-0c53641ae55621a9a") pod "18e11690-300a-4d6a-9926-47f6a00e648b" (UID: "18e11690-300a-4d6a-9926-47f6a00e648b") : kubernetes.io/csi: mounter.TearDownAt fai
led: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
`

**Comment by wongma7** [comment]
does this issue happen with 1.2.1 or 1.3.x? We identified a bug in efs-utils that could cause mounts to get 'stuck' in this state, it has been fixed in these versions. Sorry for the late update on this.

**Comment by spanktar** [comment]
We have recently upgraded to 1.3.2 in hopes it would solve the issue and we haven't seen any pods stuck in terminating.  We just released this change to production, so I'll keep an eye out for it there, where we have the most traffic and where we saw this most often.  Thanks for the update.

**Comment by hrzbrg** [comment]
We experience the problem in 1.3.2 as well unfortunately.

**Comment by spanktar** [comment]
Haven't seen any pods stuck in Terminating in 2 weeks.

**Comment by hrpatel** [comment]
We are seeing the same issue with pod termination. 

Versions:
- EKS 1.18
- EFS CSI driver 1.3.0

We have multiple deployments and cron jobs that mount the same volume. 

Errors:
```
Aug 11 20:11:11 ip-172-16-2-115 kubelet: E0811 20:11:11.074943    5409 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/efs.csi.aws.com^fs-c84ad83d::fsap-004ae325b9b83b9c4 podName:c306da3e-6556-4ddc-88f3-54d3e8944051 nodeName:}" failed. No retries permitted until 2021-08-11 20:13:13.074907525 +0000 UTC m=+2173574.647363502 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"haystack\" (UniqueName: \"kubernetes.io/csi/efs.csi.aws.com^fs-c84ad83d::fsap-004ae325b9b83b9c4\") pod \"c306da3e-6556-4ddc-88f3-54d3e8944051\" (UID: \"c306da3e-6556-4ddc-88f3-54d3e8944051\") : kubernetes.io/csi: mounter.TearDownAt failed: rpc error: code = DeadlineExceeded desc = :Timeout, server 54.167.101.55 not responding.
```

```
0492c784ba282f203\") pod \"wsgi-job-hourly-1628530920-8zqt4\" (UID: \"ab84182c-75aa-40a4-8618-d49c5c2b0f56\") : rpc error: code = Internal desc = Could not mount \"fs-54ac3ea1:/\" at \"/var/lib/kubelet/pods/ab84182c-75aa-40a4-8618-d49c5c2b0f56/volumes/kubernetes.io~csi/efs-wsgi-pv1/mount\": mount failed: wait: no child processes\nMounting command: mount\nMounting arguments: -t efs -o accesspoint=fsap-0492c784ba282f203,tls fs-54ac3ea1:/ /var/lib/kubelet/pods/ab84182c-75aa-40a4-8618-d49c5c2b0f56/volumes/kubernetes.io~csi/efs-wsgi-pv1/mount\nOutput: Could not start amazon-efs-mount-watchdog, unrecognized init system \"aws-efs-csi-dri\"\n"
```

I was also able to correlate these log lines to an increase in load average (but NOT CPU) on an affected node. The load average resolved itself at exactly midnight in one case but errors continued to show up in logs
