### ISSUE TITLE
Add arm64 images in ECR

### ISSUE THREAD

**Issue by walkley** [kubernetes-sigs/aws-efs-csi-driver#405]
/kind bug

**What happened?**
The container image in ECR(602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.2.0) does not support arm64 architecture:
```
$ docker manifest inspect 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.2.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1369,
         "digest": "sha256:a0d8703bd16188f029decf50bcae4688a3795e9d5d4ef180b9f23e88a0b824c3",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```

While the image in Docker Hub does support arm64 architecture:
```
$ docker manifest inspect amazon/aws-efs-csi-driver:v1.2.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1369,
         "digest": "sha256:419b780504600cbd826f0c103ce6745367681617e48066533910f5231210ff50",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1369,
         "digest": "sha256:b77af21223905299abcfcee332f37840efd179b3361d649a810dbfbfd02c9c33",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

**What you expected to happen?**
Add arm64 images in ECR repository to support Graviton2 instances.

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version: 1.2.0

**Comment by wongma7** [comment]
1.3.2 should point to an arm64 image:

docker manifest inspect 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.3.2
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1582,
         "digest": "sha256:3d70b76c6f38e4638437779d9123be7b7db42591d8f4a233e0e3db2a2d5f1a0a",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1582,
         "digest": "sha256:b00b742e145acc115fb0c464f5aa55ddf73437b6d66047a24727b5c109d3355f",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
