### ISSUE TITLE
Helm chart: nodeSelector behaviour is the same for controller & driver

### ISSUE THREAD

**Issue by ZF-fredericvanlinthoudt** [kubernetes-sigs/aws-efs-csi-driver#420]
/kind bug

**What happened?**
I've added this nodeSelector to the Helm chart values:
```yaml
    nodeSelector:
      dedicated: "infra"
```
The nodeSelector is being set for both the CSI controller AND the driver (daemonset).
Which prevents driver pods from being scheduled on ALL nodes.
At this moment both the controller & driver helm templates are looking at the `.Values.nodeSelector` value which makes it impossible to have a different value for them.

I only want to restrict the CSI controller to run on my dedicated infra nodes but the driver needs to run on all nodes.

**What you expected to happen?**
The nodeSelector only being set for the CSI controller.
There should be a separate nodeSelector for the driver under `node` values of the Helm chart.
This is already the case for the [EBS CSI driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/96c3c59f41e864a0ed1f14f5e220eb8db5529ac6/charts/aws-ebs-csi-driver/values.yaml#L116).

**How to reproduce it (as minimally and precisely as possible)?**
N/A

**Anything else we need to know?**:
N/A

**Environment**
- Kubernetes version (use `kubectl version`): `v1.19.8-eks-96780e`
- Driver version: `1.2.0`
- Helm chart version: `1.2.2`

**Comment by wongma7** [comment]
I think https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/406/, which is a major refactoring of the chart, will fix it
