### ISSUE TITLE
Dynamic Provisioning: Add PV/PVC identifying tags to the Access Points created by the csi

### ISSUE THREAD

**Issue by noamles** [kubernetes-sigs/aws-efs-csi-driver#446]
Hello,

its currently hard to identify which EFS Access Point is related to which pvc when looking at the EFS conosole.
I think that by adding a few tags to the Access Point resources created by the csi this issue can be easily resolved.
For example you can see the tags that are added to EBS volumes created by cloud provider:

- kubernetes.io/created-for/pv/name
- kubernetes.io/created-for/pvc/name
- kubernetes.io/created-for/pvc/namespace

Thank you.

**Comment by diranged** [comment]
This would be great - especially if we can also add in our own tags for billing purposes.

**Comment by pierluigilenoci** [comment]
Requested also for EBS: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180#issuecomment-861496799

**Comment by pierluigilenoci** [comment]
Maybe with an option like the one used in the "twin" chart: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L49

**Comment by pierluigilenoci** [comment]
I did a PR https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/494
