### ISSUE TITLE
Helm chart uses node.podAnnotations for controllers

### ISSUE THREAD

**Issue by akunszt** [kubernetes-sigs/aws-efs-csi-driver#457]
/kind bug

**What happened?**
I'm deploying `aws-efs-csi` to our cluster. I set the `podAnnotations` but it was ignored. The chart uses the `.Values.node.podAnnotations` in the `controller-deployment.yaml` file too. I assumed that `podAnnotation` is for the controller and `node.podAnnotations` is for the DaemonSet.

**What you expected to happen?**
Use the annotations I set in the `values.yaml`.

**How to reproduce it?**
Change the `podAnnotations` like this.
```yaml
podAnnotations:
  foo: bar
```

Deploy the chart or just generate a template locally. Check the annotations on the `efs-csi-controller`.

**Anything else we need to know?**:
Nope.

**Environment**
Doesn't relevant. It just typo in the chart or I misread the intention of the `podAnnotations` and `node.PodAnnotations` values.

**Comment by akunszt** [comment]
The same is true for the `tolerations`/`node.tolerations`.

**Comment by akunszt** [comment]
And the `affinity` isn't used at all in the chart.

**Comment by wongma7** [comment]
controller/node.tolerations, controller/node.podAnnotations and controller.affinity will be fixed in upcoming 2.0.0 chart release, there was a big cleanup. https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/controller-deployment.yaml#L22

**Comment by retraut** [comment]
Seems like fixed with https://github.com/kubernetes-sigs/aws-efs-csi-driver/releases/tag/helm-chart-aws-efs-csi-driver-2.0.0
