### ISSUE TITLE
Feature: Add Helm Chart to ArtifactHub.io

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes-sigs/aws-efs-csi-driver#471]
**Is your feature request related to a problem? Please describe.**
Make it easier to find the chart. 

**Describe the solution you'd like in detail**
Adding the chart on https://artifacthub.io/ gives a lot of visibility 

**Describe alternatives you've considered**
No alternative 

**Additional context**
Not relevant

**Comment by pierluigilenoci** [comment]
I can understand the lack of contributors but this, not such demanding stuff, allows to give visibility to the project.

**Comment by pierluigilenoci** [comment]
@kbasv @wongma7 could you please take a look?

**Comment by pierluigilenoci** [comment]
@kbasv @wongma7 @gezb @jsafrane @nckturner could you please take a look?

**Comment by pierluigilenoci** [comment]
@kbasv @wongma7 @gezb @jsafrane @nckturner could you please take a look?

**Comment by pierluigilenoci** [comment]
@kbasv @wongma7 @gezb @jsafrane @nckturner could you please take a look?

**Comment by pierluigilenoci** [comment]
@kbasv @wongma7 @gezb @jsafrane @nckturner could you please take a look?

**Comment by mskanth972** [comment]
**@pierluigilenoci**, Thank you for providing your valuable feedback on the service. I have raised a feature request with the service team on your behalf. While I am unable to comment on if/when this feature may get released. I'll comment out here when the feature is released.

**Comment by omidraha** [comment]
Is this helm chart of `https://github.com/kubernetes-sigs/aws-efs-csi-driver` in `artifacthub`?
https://artifacthub.io/packages/helm/aws-efs-csi-driver/aws-efs-csi-driver
Could you please update documentation of this helm chart.

**Comment by pierluigilenoci** [comment]
@omidraha, the entry you linked in ArtifactHub is not an official AWS entry.

**Comment by pierluigilenoci** [comment]
🤦🏻

**Comment by pierluigilenoci** [comment]
@seanzatzdev-amazon, why not planned?
