### ISSUE TITLE
EFS AccessPoint Mount fails on Fargate pod after period of time

### ISSUE THREAD

**Issue by hardillb** [kubernetes-sigs/aws-efs-csi-driver#472]
/kind bug

**What happened?**
I mount EFS access point into my pod, I write/read from the location at regular intervals (e.g. every 5mins). The mount point then becomes unresponsive after a few days (at the moment I can't pin it down to a hard time limit, it appears to not be consistent).

As an aside, the app is NodeJS based so ends up stopping responding to HTTP requests, the ingress controller times the route out but the pod can stay up for a few hour because the process is blocking on the File IO, it also looks to prevent the K8s control from taking the pod down cleanly when it marks it as failed.

**What you expected to happen?**

The mount to stay live for the lifetime of the pod (this is expected to be a long lived process)

**How to reproduce it (as minimally and precisely as possible)?**

- Create a PV pointing at EFS access point
- Create PVC bound to previous PV in fargate namespace
- Create a Pod that mounts the PVC
- Read/write to file on the mounted volume once every 5mins
- Wait for it to fail

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Driver version:
Not sure how to determine  the version deployed, best guess based on `kubectl describe pod/efs-csi-node-5r6r8 -n kube-system` Will update if you can provide instructions to get better information.
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.0.0

**Comment by kbasv** [comment]
@hardillb Would you be able to run [log collector](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting) and provide it us for analysis?

**Comment by hardillb** [comment]
I can but I don't know which pod name to pass as the argument since it doesn't look like the efs-csi pods run on the fargate nodes

e.g.
```
$ kubectl get pods -n kube-system
NAME                                            READY   STATUS    RESTARTS   AGE
aws-load-balancer-controller-6f866fffbd-4tlnz   1/1     Running   1          41d
aws-node-kcmkr                                  1/1     Running   0          41d
aws-node-tfmbk                                  1/1     Running   0          41d
aws-node-w98pd                                  1/1     Running   0          41d
coredns-66bc8b7b7b-gcx87                        1/1     Running   0          41d
coredns-66bc8b7b7b-zht7g                        1/1     Running   0          41d
efs-csi-node-5r6r8                              3/3     Running   0          41d
efs-csi-node-bqfxp                              0/3     Pending   0          108m
efs-csi-node-fnd62                              0/3     Pending   0          7d1h
efs-csi-node-h725s                              3/3     Running   0          41d
efs-csi-node-kzz8l                              3/3     Running   0          41d
efs-csi-node-xl7qh                              0/3     Pending   0          108m
kube-proxy-7vc64                                1/1     Running   0          41d
kube-proxy-jgg6s                                1/1     Running   0          41d
kube-proxy-spnmc                                1/1     Running   0          41d

$ kubectl get nodes
NAME                                                    STATUS   ROLES    AGE    VERSION
fargate-ip-192-168-101-79.us-east-2.compute.internal    Ready    <none>   109m   v1.18.9-eks-866667
fargate-ip-192-168-124-146.us-east-2.compute.internal   Ready    <none>   110m   v1.18.9-eks-866667
fargate-ip-192-168-148-197.us-east-2.compute.internal   Ready    <none>   7d1h   v1.18.9-eks-866667
ip-192-168-60-193.us-east-2.compute.internal            Ready    <none>   41d    v1.18.9-eks-d1db3c
ip-192-168-89-174.us-east-2.compute.internal            Ready    <none>   41d    v1.18.9-eks-d1db3c
ip-192-168-9-128.us-east-2.compute.internal             Ready    <none>   41d    v1.18.9-eks-d1db3c

```

How do I know which of the 3 that is running you want the logs from  (I assume the pending ones are not scheduled because they can't run on the fargate nodes?)

**Comment by kbasv** [comment]
Can you run the script against all the 3 pods which are in the `running` state since we do not know which pod mounted the access point?

**Comment by hardillb** [comment]
Here are all 3 running pods
[efs-csi-node-5r6r8-results.tar.gz](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/6634644/efs-csi-node-5r6r8-results.tar.gz)
[efs-csi-node-h725s-results.tar.gz](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/6634645/efs-csi-node-h725s-results.tar.gz)
[efs-csi-node-kzz8l-results.tar.gz](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/6634646/efs-csi-node-kzz8l-results.tar.gz)

**Comment by hardillb** [comment]
Email sent with correct data and a fixed version of the script.
