### ISSUE TITLE
helm chart example missing or incorrect

### ISSUE THREAD

**Issue by kgk** [kubernetes-sigs/aws-efs-csi-driver#491]
/kind bug

**What happened?**
Tried to use the helm chart based on example here: https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/

I believe the ordering of the values has changed:
serviceAccount.controller.name -- > controller.serviceAccount.name 

**What you expected to happen?**

Change the service account name 

**How to reproduce it (as minimally and precisely as possible)?**

helm install --debug --dry-run aws-efs-csi-driver . --set serviceAccount.controller.name=aa 
# Source: aws-efs-csi-driver/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-csi-controller-sa
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by MerreM** [comment]
My workaround at the moment is install it as per the example - then replace the service account with a working one created manually. 

The helm values don't appear to be able to prevent the service account from being created at the moment.
