### ISSUE TITLE
using EFS Access Point, pod failed to come up, remains in Status: ContainerCreating 

### ISSUE THREAD

**Issue by JingCTyagi** [kubernetes-sigs/aws-efs-csi-driver#505]
/kind bug

**What happened?**
using EFS Access Point, pod failed to come up, remains in Status: ContainerCreating 
**What you expected to happen?**
pods starts
**How to reproduce it (as minimally and precisely as possible)?**
1. created EFS using AWS EFS console and created two access points for the created efs. 
2. following the instructions from the link(https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/access_points/README.md), tried two access points or one access points, both are same results. 
**Anything else we need to know?**:
efs id using the long id fs-17digigs.
**Environment**
- Kubernetes version (use `kubectl version`): 1.19
- 
- Driver version:
helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver/
helm repo update
helm upgrade --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver

**Comment by edoardo-c** [comment]
Hi @JingCTyagi ,

Did you have a look at my [issue](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/504)?

I had to create the directories I was mounting with Access Points in the root of the EFS volume.

So if you have an AP with a path /dir1, you will need to mount the EFS volume root and create that directory before you can use your defined AP.

Hope this helps.

**Comment by JingCTyagi** [comment]
HI @edoardo-c , 
Thanks for your reply. I just took a look at your issue, mine is worse than yours. I couldn't even mount on the EFS volume root. I'm not sure if I installed the csi driver correctly.  Below is what I did...
1. Create an EFS volume fs-xxxx(17 digits) using efs console
2. Create an Access Point fsap-zzzz with a path "/dir1"  and fsap-yyyy with a path "/dir2" using efs console
3. kubectl apply -f deploy/kubernetes/base/controller-serviceaccount.yaml
4. Install the driver using helm:
helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver/
helm repo update
helm upgrade --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver...
5. $ kubectl apply -f examples/kubernetes/access_points/specs/example.yaml with fs and fsap modified to mine.
 and I also tried the efs root $ kubectl apply -f examples/kubernetes/static_provisioning/specs/pv.yaaml claim.yaml and pod.yaml, got same error for the pod...

**Comment by edoardo-c** [comment]
I think what you should do is post logs so that others can help. Could you get the events of the pod that is failing so that we know what the problem might actually be?

`kubectl describe mypod`

At the bottom there should be some events. If you post these I can try and help.
