### ISSUE TITLE
Persistent Volume not getting deleted(AWS permissions: Access denied)

### ISSUE THREAD

**Issue by subhankarpati95** [kubernetes-sigs/aws-efs-csi-driver#522]
Persistent volume is not getting deleted after deleting the persistent volume claim.

Kubectl get pv:

       NAME          CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS            CLAIM            STORAGECLASS   REASON   AGE
       pvc-xxxxxxx  1Gi                        RWX            Delete                 Released   default/efs-claim         efs-sc                                93m

kubectl describe pv pvc-xxxxx:

```
  Type     Reason              Age   From                                                                                Message
  ----     ------              ----  ----                                                                                -------
  Warning  VolumeFailedDelete  34m   efs.csi.aws.com_ip-xxxxxxxxxx.ec2.internal_e1c6ad54-5d48-4eac-a06f-d18efcdb9798  rpc error: code = Internal desc = Could not unmount "/var/lib/csi/pv/fsap-xxxxxxxxxxxx93d951c": **unmount failed: wait: no child processes**
Unmounting arguments: /var/lib/csi/pv/fsap-xxxxxxxxxxxx93d951c
Output:
  Warning  VolumeFailedDelete  31m  efs.csi.aws.com_ip-xxxxxxxxx.ec2.internal_acaa6d51-2f03-4e08-8b35-948b43f37891  rpc error: code = Internal desc = Could not unmount "/var/lib/csi/pv/fsap-xxxxxxxxxxx93d951c": **unmount failed: wait: no child processes**
Unmounting arguments: /var/lib/csi/pv/fsap-xxxxxxxxxxx93d951c
Output:
  Warning  VolumeFailedDelete  3m3s (x15 over 33m)  efs.csi.aws.com_ip-xxxxxxxxxxxx.ec2.internal_acaa6d51-2f03-4e08-8b35-948b43f37891  rpc error: code = **Unauthenticated desc = Access Denied. Please ensure you have the right AWS permissions: 
Access denied**
```

Below IAM policy is attached to the IAM role which is used by the Service Account **efs-csi-controller-sa**

IAM Policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "elasticfilesystem:DescribeFileSystems",
                "elasticfilesystem:DescribeAccessPoints"
            ],
            "Resource": "*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "elasticfilesystem:CreateAccessPoint",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/efs.csi.aws.com/cluster": [
                        "true"
                    ]
                }
            }
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "elasticfilesystem:DeleteAccessPoint",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/efs.csi.aws.com/cluster": [
                        "true"
                    ]
                }
            }
        }
    ]
}
```

**Comment by vglen** [comment]
I am running into the same issue. If I find a solution or what I misconfigured, I will report back.

**Comment by vglen** [comment]
If I remove the conditional on the the deletion sid, it works.
``` hcl
        {
            "Sid": "efsDdeleteAccessPoint",
            "Effect": "Allow",
            "Action": "elasticfilesystem:DeleteAccessPoint",
            "Resource": "*"
        }
```

Not optimal. More digging.

**Comment by vglen** [comment]
I figured it out, I made the same mistake @subhankarpati95. Simply change the `elasticfilesystem:DeleteAccessPoint` statement conditional to not use a list of strings. I also had to flip  my policy creation from a data block in terraform to `jsonencode` inline as it would only let me use a list.

Also the example policy uses `StringLike` on the `elasticfilesystem:CreateAccessPoint` statement.

**Comment by sgardnerdell** [comment]
The problem is due to a mistake in the IAM policy provided by the OP.

The conditional for elasticfilesystem:DeleteAccessPoint should be **aws:ResourceTag**/efs.csi.aws.com/cluster not **aws:RequestTag**/efs.csi.aws.com/cluster.

Also as @vglen already pointed out the documentation states that you should use `StringLike` on the `elasticfilesystem:CreateAccessPoint`, however contrary to his post this works fine in a terraform `aws_iam_policy_document` data block which only allows an array of values for the condition.

**Comment by andyguwc** [comment]
Using this new policy fixed the issue, as OP mentioned earlier, the old policy had the condition filtering wrong. 
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/d8bc07389b00821f1c6f2dde9e37dda9c29a2385/docs/iam-policy-example.json

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "elasticfilesystem:DescribeAccessPoints",
        "elasticfilesystem:DescribeFileSystems",
        "elasticfilesystem:DescribeMountTargets",
        "ec2:DescribeAvailabilityZones"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "elasticfilesystem:CreateAccessPoint"
      ],
      "Resource": "*",
      "Condition": {
        "StringLike": {
          "aws:RequestTag/efs.csi.aws.com/cluster": "true"
        }
      }
    },
    {
      "Effect": "Allow",
      "Action": "elasticfilesystem:DeleteAccessPoint",
      "Resource": "*",
      "Condition": {
        "StringEquals": {
          "aws:ResourceTag/efs.csi.aws.com/cluster": "true"
        }
      }
    }
  ]
}

```

**Comment by McMac** [comment]
@andyguwc, thank you for this comment. Had issues for over a week now and your suggestion helped solve the permission denied problem I was seeing.
