### ISSUE TITLE
Failing to pull image due to Rate Limit

### ISSUE THREAD

**Issue by vigneshraaj** [kubernetes-sigs/aws-efs-csi-driver#526]
/kind bug

**What happened?**
When upgraded to the latest version, the pods are not getting started

**What you expected to happen?**
efs-csi-node Pods are running successfully.

**How to reproduce it (as minimally and precisely as possible)?**
```
helm -n kube-system upgrade aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver
kubectl -n kube-system get pods -l "app=efs-csi-node"
```

**Anything else we need to know?**:
We have around 20+ nodes running on that cluster.
It's throwing the following error.
```
  Normal   Pulling    3m39s (x3 over 4m24s)  kubelet            Pulling image "amazon/aws-efs-csi-driver:v1.3.2"
  Warning  Failed     3m39s (x3 over 4m24s)  kubelet            Failed to pull image "amazon/aws-efs-csi-driver:v1.3.2": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning  Failed     3m39s (x3 over 4m24s)  kubelet            Error: ErrImagePull
  Normal   BackOff    3m14s (x5 over 4m23s)  kubelet            Back-off pulling image "amazon/aws-efs-csi-driver:v1.3.2"
  Warning  Failed     3m14s (x5 over 4m23s)  kubelet            Error: ImagePullBackOff
```
https://www.docker.com/increase-rate-limit - Is this a free account?

**Environment**
- Kubernetes version (use `kubectl version`): v1.21
- Driver version: 1.3.2
- Helm Chart version: aws-efs-csi-driver-2.1.4

**Comment by kbasv** [comment]
@vigneshraaj Docker requires you to login/authenticate, otherwise you will be rate limited. Alternatively, feel free to pull it from Amazon's ECR repo for EFS-csi-driver. Here is an example on how to install -  https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html#efs-install-driver
