### ISSUE TITLE
Tags with colons 

### ISSUE THREAD

**Issue by hemandee** [kubernetes-sigs/aws-efs-csi-driver#533]
/kind bug

**What happened?**
Trying to limit EFS Actions using IAM tags. Following "eks:cluster-name: mycluster" tags schema to match EKS Managed Nodes groups tagging of EC2 instances.

...
  {
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:cluster-name": "myfirstcluster"
                }
            },
            "Action": "elasticfilesystem:CreateAccessPoint",
            "Resource": "*",
            "Effect": "Allow"
        }
...
using tags: eks:cluster-name : myfirstcluster passed to EFS controller splits on ":"
Logs (efs-csi-controller):
 Tags: [{
      Key: "eks",
      Value: "cluster-name"
    },{
      Key: "efs.csi.aws.com/cluster",
      Value: "true"
    }]
}
**What you expected to happen?**
I expect CreateAccessPoint API calls to parse tags with mutiple ":" in the string. Maybe related to [this](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/388c3f90f21f9c550935815bc8af25ddce4c7f32/pkg/driver/driver.go#L145)?

**How to reproduce it (as minimally and precisely as possible)?**
Install Helm chart version 2.1.4 with tags configurations:
eks:cluster : myfirstcluster. 

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version: 1.3.2

**Comment by wongma7** [comment]
"Allowed characters can vary by AWS service. For information about what characters you can use to tag resources in a particular AWS service, see its documentation. In general, allowed characters in tags are letters, numbers, spaces representable in UTF-8, and the following characters: _ . : / = + - @ . " https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html#tag-conventions

have to allow another character to be used as delimiter besides : like sed. Or even better offer an alternative syntax that mimics the aws cli syntax `Key=asdf,Value=qwer` https://docs.aws.amazon.com/cli/latest/reference/efs/create-access-point.html
