### ISSUE TITLE
Delete access point root dir via pod in user cluster

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes-sigs/aws-efs-csi-driver#537]
**Is your feature request related to a problem? Please describe.**
When using `--deleteAccessPointRootDir=true`, the EFS CSI driver controller mounts the file system locally, removes the root directory, and unmounts it.

In order for this feature to work, the nodes running the EFS CSI driver controller must have network access (security groups) configured to access the elastic file system.

However, if users run the EFS CSI driver controller on a separate set of control plane nodes running only control plane components, they may not want to allow network access from these nodes for user data privacy reasons, which means this feature will not work with this architecture.

**Describe the solution you'd like in detail**
During volume deletion, the EFS CSI driver controller creates a pod in the user cluster that performs the cleanup and stops. This allows the EFS CSI driver controller to be deployed alongside other control plane components on dedicated nodes.

**Describe alternatives you've considered**
Users can run the EFS CSI driver controller in the user cluster (which presumably already has network access). For some managed Kubernetes distros, this will require manual work by the user to set up.

Another alternative is to support root directory cleanup on deletion as part of the EFS API, which would remove the need to do any manual cleanup, but would likely take longer to implement and roll out.

**Comment by chrishenzie** [comment]
@kbasv @wongma7 @msau42

**Comment by msau42** [comment]
I guess one challenge would be how this Pod would be implemented. It wouldn't be able to mount the PVC because the PVC is in terminating state.
