### ISSUE TITLE
Controller pod still trying to use OIDC even though kube2iam annotation is provided

### ISSUE THREAD

**Issue by FarhanKhan-sains** [kubernetes-sigs/aws-efs-csi-driver#539]
/kind bug

**What happened?**

Unable to use kube2iam to grant the necessary permissions to the controller pod. The pod still tries to use the service account which doesn't work as I don't have an OIDC provider in the cluster. If I disable the service account creation, it complains that there is no service account. It seems like we are forced to use OIDC?

**What you expected to happen?**

The controller pod uses the IAM role specified in the pod annotation `iam.amazonaws.com/role`

**How to reproduce it (as minimally and precisely as possible)?**

Deploy kube2iam

Create a role and attach a policy with the following permissions:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "EFSProvisioner",
      "Action": [
        "elasticfilesystem:*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
```

Use the official efs csi driver helm chart with the following values:

```
controller:
      podAnnotations:
        iam.amazonaws.com/role: <NameOfTheRoleWithAbovePolicy>
```

Then create a test volume claim and watch the efs csi driver controller logs. The following line appears:

```
I0820 10:42:12.348145       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"perf", Name:"test-shared-pvc", UID:"1a3b7bc4-cbbf-4d6f-a72a-8c79dfc0176a", APIVersion:"v1", ResourceVersion:"693228150", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "efs-sc": rpc error: code = Unauthenticated desc = Access Denied. Please ensure you have the right AWS permissions: Access denied
```

If I add the OIDC permissions to the role and to the service account I get OIDC related errors as I don't have an OIDC provider set up in the cluster. I used to use efs-provisioner before it was deprecated and it would work fine using the credentials provided by kube2iam.

**Environment**
- Kubernetes version (use `kubectl version`): v1.20
- Driver version: v1.3.3

**Comment by sudermanjr** [comment]
@FarhanKhan-sains were you able to get this working with KIAM using that workaround? We're running into this right now.

**Comment by FarhanKhan-sains** [comment]
@sudermanjr Hi, I just created the OIDC provider in AWS so haven't tried the workaround.

**Comment by callum-p** [comment]
I can confirm that the workaround does indeed work.

**Comment by darlaig** [comment]
The work around doesn't seem to work for me. I'm getting an STS assume role ( our eks worker role) not authorized to perform sts: AssumeRole on the resource "iam:role" which has all the required access to the elasticfilesystem resource

**Comment by darlaig** [comment]
@callum-p were you able to dynamically create a PV using the work around? IRSA isn't enabled in my cluster yet.

**Comment by callum-p** [comment]
@darlaig yes I can dynamically create PVs.

Sounds like your eks worker role doesn't have sts:AssumeRole granted for the iam role that has the EFS permissions.
