### ISSUE TITLE
Support ReadWriteOncePod (kube v1.22+)

### ISSUE THREAD

**Issue by Ashtonian** [kubernetes-sigs/aws-efs-csi-driver#540]
**Is your feature request related to a problem?/Why is this needed**
The new ReadWriteOncePod access mode will be added to PVC, not sure what needs to change if much at all. 

[KEP-2485: ReadWriteOncePod PersistentVolume AccessMode](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2485-read-write-once-pod-pv-access-mode#csi-specification-changes-volume-capabilities
)

https://github.com/kubernetes/enhancements/issues/2485 

/feature

**Describe the solution you'd like in detail**

The driver to support ReadWriteOncePod. 

**Describe alternatives you've considered**
Not using ReadWriteOncePod. 

**Additional context**

**Comment by chrishenzie** [comment]
/remove-lifecycle stale

I'm planning on graduating the feature to beta in 1.27. I'll want to update here before then.

**Comment by chrishenzie** [comment]
/remove-lifecycle stale

This feature is being moved to beta (in k8s) in 1.27.

To support this feature, technically nothing needs to change other than [updating your CSI drivers](https://kubernetes.io/blog/2021/09/13/read-write-once-pod-access-mode-alpha/#update-your-csi-sidecars). If you want to strictly enforce this access mode in the CSI driver, then [see this PR](https://github.com/kubernetes-csi/csi-driver-host-path/pull/381) as an example. You can also test this driver using the CSI sanity utility. Once [this PR](https://github.com/kubernetes-csi/csi-test/pull/421) is merged you will be able to test this using the tool.

**Comment by chrishenzie** [comment]
ReadWriteOncePod is now [graduated to beta](https://kubernetes.io/blog/2023/04/20/read-write-once-pod-access-mode-beta/) as of K8s v.127.

This feature does not require any extra changes to the AWS EFS CSI driver to work. The only thing users need to do is update their CSI sidecars [to these versions or greater](https://kubernetes.io/blog/2023/04/20/read-write-once-pod-access-mode-beta/#how-can-i-start-using-readwriteoncepod).

(Not required) You may update the AWS EFS CSI driver to advertise the new `SINGLE_NODE_SINGLE_WRITER` CSI access mode. See [the above comment](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/540#issuecomment-907507472) for more context.

**Comment by Ashley-wenyizha** [comment]
Thanks @chrishenzie  for the info! 

/kind feature
