### ISSUE TITLE
Dynamic basePath

### ISSUE THREAD

**Issue by wolffberg** [kubernetes-sigs/aws-efs-csi-driver#543]
**Is your feature request related to a problem? Please describe.**
When working with multi tenant clusters where each tenant can provision x amount of PVCs, identifying files for cleanup, restoration, etc. Becomes hard as directories can only be identified by the PVC id.

The built-in option to delete data with access points is too risky for our use case.

**Describe the solution you'd like in detail**
We would like a way of defining a path per namespace/tenant e.g. `/basePath/namespace/pvc-id` through annotations or other attributes in the `PersistentVolumeClaim` resource or define a dynamic `basePath` format in the `StorageClass` resource.

If attributes in the `PersistentVolumeClaim` is a posibility, correct values can be enforced with the use of [OPA Gatekeeper](https://github.com/open-policy-agent/gatekeeper) or similar.

This way you could easily create cleanup logic for deleted namespaces and copy files to new PVC volumes if required.

**Additional context**
Looking through [controller.go](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/pkg/driver/controller.go) I haven't been able to identify whether the controller actually get data related to the `PersistentVolumeClaim` used to generate access points.

I'm hoping I have either missed something or it can be easily implemented.

**Comment by wongma7** [comment]
the controller does have access to the PVC namespace so this is theoretically possible. otherwise the storageclass parameter idea also sounds reasonable to me.

**Comment by richerve** [comment]
I also have a need for this, what I'm thinking is having an admission controller that will add a `/<namespace>` prefix to any PVC using storageClass `efs-<something>` or whatever I use as storageClass name. But this is an extra step.

Having said that it seems that this kind of behaviour is better handled by an operator than by a csi driver but in this specific case it'd probably be just an extra flag in the StorageClass, something like `prefixNamespaceInPath` or something similar, or maybe a templatized value like: `pathPrefix: "$namespace"`.

@wongma7 I can have a go in adding this feature, is there interest in it?
