### ISSUE TITLE
Using access points still requires dynamic provisioning setup

### ISSUE THREAD

**Issue by dhuang** [kubernetes-sigs/aws-efs-csi-driver#556]
/kind bug

**What happened?**
I'm trying to use an access point created in EFS, essentially just like the [access points example](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/access_points). However, I'm struggling to even create the storage class using the config below.

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
```  

It gives me the following error in the `efs-csi-controller` logs:

```
controller.go:981] error syncing claim "...": failed to provision volume with StorageClass "efs-storage-class": rpc error: code = InvalidArgument desc = Missing provisioningMode parameter    
```

Which I can see that is a required parameter for [dynamic provisioning](https://github.com/kubernetes-sigs/aws-efs-csi-driver#storage-class-parameters-for-dynamic-provisioning).

**What you expected to happen?**
I can add the required parameters (`provisioningMode`, `fileSystemId`, `directoryPerms`), but then creating it requires setting up additional IAM policy/role, which I don't think should be necessary for static provisioning? I'm pretty certain I had this working on an older driver, but presumably that was before dynamic provisioning support. Perhaps the requirement is very much intentional, but then the example should probably be updated.

**How to reproduce it (as minimally and precisely as possible)?**
Just try to create the storage class in https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/access_points/specs/example.yaml.

**Anything else we need to know?**:
I did see the [static provisioning example](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/static_provisioning) does not create a storage class and leaves it blank. But I am looking to use access points from multiple pods if possible, so not sure this is sufficient?

**Environment**
- Kubernetes version (use `kubectl version`): 1.21.0
- Driver version: 1.3.3

**Comment by wongma7** [comment]
Plus, to avoid storageclasses altogether you can set them to empty string ("").

This is NOT the same thing as not setting them at all (nil). Because when you set the PVC to have nil, storageclass, kubernetes tries to use the default storage class

**Comment by mimmus** [comment]
> it shouldn't be necessary to create a StorageClass for static provisioning. The key is to create a PV with the syntax in the example spec like " volumeHandle: [FileSystemId]::[AccessPointId]" . This PV doesn't need to have storageClassName "efs-sc" set. But if it does have storageClassName set, then when you create a PVC requesting that storage class "efs-sc", kubernetes should try to bind your PVC with that PV instead of trying to dynamically provision another one, provided the PV satisfies your PVC's requirements.
> 
> I'll try to clarify the example, maybe it should be split up into two examples, one static and one dynamic

As dynamic provisioning has a limit of 120 access points under one filesystem, I'm trying static provisioning, with volume path _volumeHandle: [FileSystemId]:[Path]_ but it's not clear if I still need a PVC with a Storage Class or I need only to define a PV.
