### ISSUE TITLE
Integrate e2e test with prow

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-efs-csi-driver#56]
**Is your feature request related to a problem? Please describe.**
Integrate e2e test with prow

**Comment by wongma7** [comment]
I had https://github.com/wongma7/test-infra/commit/49949ee679107503333526f8024bf5d45d18e26d#diff-f48e4b4f752ddaa4f1a9f7f939db0e3b WIP feel free to pick it up (I just copied the EBS one...)

**Comment by leakingtapan** [comment]
ah, feel free to pick it up if you started already.
/assign @wongma7
