### ISSUE TITLE
iam-policy-example.json are missing policies

### ISSUE THREAD

**Issue by heitorrbarros** [kubernetes-sigs/aws-efs-csi-driver#570]
During the deployment of the helm chart on this repo. I received an unauthorized exception from the IAM because the role policy mentioned [iam-policy-example.json](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json) are missing two policies. It frustrated me :(

I'm using the static provisioning without the access point.

I would like to add the missing policies on the documentation to help the other users.

**Comment by kafteji** [comment]
which policies are you missing ? Just tried it and it works for me with helm...
