### ISSUE TITLE
Disable encryptInTransit for PVC

### ISSUE THREAD

**Issue by Kuzbekov** [kubernetes-sigs/aws-efs-csi-driver#586]
Sometimes we want to disable encryption in transit for some volumes.
Currently if you are using Persistent Volume Claim there is no way to change attribute encryptInTransit: "false" in PV.

It would be great to have a new field in the storage class that will reflect this parameter in resulting PV.

**Comment by pkit** [comment]
I'm in awe that it's not working yet

**Comment by jonathanrainer** [comment]
See PR #687 for a solution to this
