### ISSUE TITLE
What is the allow logLevel verbosity range

### ISSUE THREAD

**Issue by tanvp112** [kubernetes-sigs/aws-efs-csi-driver#588]
May I know what is the allow value and their level of verbosity for `logLevel` in the helm values?

Thanks!

**Comment by nwithers-ecr** [comment]
I was looking for this too. It appears to be going from `0` which is the least verbose, to `6` which is the most verbose. 
On github if you go to a line such as, https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/release-1.3/pkg/driver/controller.go#L251 click on `klog.V(#)` then click references it will show you all the defined levels, and I couldn't find any outside the ranged mentioned above.

**Comment by tanvp112** [comment]
Ok, will try that. This configurable value should be document in the Helm documentation, if not at least state the range in the values.yaml itself.
