### ISSUE TITLE
Decouple dynamic PVs from dynamic access points

### ISSUE THREAD

**Issue by droctothorpe** [kubernetes-sigs/aws-efs-csi-driver#594]
**Is your feature request related to a problem?/Why is this needed**
I want to be able to dynamically provision PVs using a _static_ access point.

Currently, it appears that dynamic PVs are _coupled_ with dynamic access points. I want to use these capabilities in a decoupled way. Based on the docs, that does not appear to be possible. 

/feature

**Describe the solution you'd like in detail**
The ability to create and consume a storage class that lets you dynamically generate PVs (in response to creation of PVCs) that consumes a static access point instead of _also_ dynamically generating an access point.

**Comment by paalkr** [comment]
Ref: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/538
