### ISSUE TITLE
Bug on identifying tags to the Access Points created by the csi dynamically 

### ISSUE THREAD

**Issue by delc006** [kubernetes-sigs/aws-efs-csi-driver#596]
/kind bug

**What happened?**
We have configured a flag to tags efs access points at efs controller charts level `extraCreateMetadata=true`
As explain in this PR #494 

In the create volume request we saw the right parameters:

```
...
csi.storage.k8s.io/pv/name:pvc-c048a913-xxxx-xxxx-9be9-3a5eec87eeb7 csi.storage.k8s.io/pvc/name:nginx-logs csi.storage.k8s.io/pvc/namespace:64d49d-nonproduction-development
...
```

```
I1207 19:47:26.207062       1 controller.go:58] CreateVolume: called with args {Name:pvc-c048a913-xxxx-xxxx-9be9-3a5eec87eeb7 CapacityRange:required_bytes:10485760  VolumeCapabilities:[mount:<mount_flags:"tls" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > ] Parameters:map[basePath:/dynamic_provisioning csi.storage.k8s.io/pv/name:pvc-c048a913-xxxx-xxxx-9be9-3a5eec87eeb7 csi.storage.k8s.io/pvc/name:nginx-logs csi.storage.k8s.io/pvc/namespace:64d49d-nonproduction-development directoryPerms:700 fileSystemId:fs-01d5faa637xxxxxx gidRangeEnd:2000 gidRangeStart:1000 provisioningMode:efs-ap] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1207 19:47:26.207150       1 cloud.go:218] Calling DescribeFileSystems with input: {
  FileSystemId: "fs-01d5faa637xxxxxx"
}
I1207 19:47:26.289617       1 gid_allocator.go:52] Recieved getNextGid for fsId: fs-01d5faa637xxxxxx, min: 1000, max: 2000
I1207 19:47:26.289642       1 gid_allocator.go:55] FS Id doesn't exist, initializing...
I1207 19:47:26.289668       1 cloud.go:157] Calling Create AP with input: {
  ClientToken: "pvc-c048a913-xxxx-xxxx-9be9-3a5eec87eeb7",
  FileSystemId: "fs-01d5faa637xxxxx",
  PosixUser: {
    Gid: 1000,
    Uid: 1000
  },
  RootDirectory: {
    CreationInfo: {
      OwnerGid: 1000,
      OwnerUid: 1000,
      Permissions: "700"
    },
    Path: "/dynamic_provisioning/pvc-c048a913-xxxx-xxxx-9be9-3a5eec87eeb7"
  },
  Tags: [{
      Key: "efs.csi.aws.com/cluster",
      Value: "true"
    }]
}
```

**What you expected to happen?**
We expected the tags to be set according to create volume requests parameter on the efs access point.
But as you can see tags array does not contain values for those keys : 

- csi.storage.k8s.io/pvc/name
- csi.storage.k8s.io/pvc/namespace
- csi.storage.k8s.io/pv/name

**How to reproduce it (as minimally and precisely as possible)?**
Create dynamically an access point using aws efs csi provisioner. 

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 
    Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
- Driver version:
    csiProvisioner 3.0.0 (we also tried with 2.1.1)
    aws-efs-csi-driver 1.3.4
    chart aws-efs-csi-driver 2.2.0

**Comment by edanc** [comment]
We also ran into this issue. I opened a pull request in the past but was not able to sign the CLA https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/349/files 

Passing the flag was not enough. We had to get the tags from the request

**Comment by jonathanrainer** [comment]
This PR https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/689 adds support for these tags

**Comment by Cushdrive** [comment]
What's it going to take to get some focus on the PR? Without this implementation, we have to associate overly permissive IAM policies to the node or pod. We would like to use ABAC based on request and resource tags.

**Comment by bcbrockway** [comment]
Hey we're really interested in this. We're currently figuring out what our DR process for a region outage looks like using EFS replication but we have no way of knowing what each of the access points in the replicated region contain without access to the original Kubernetes cluster (or manually mounting each one to see what files are inside!).

**Comment by dyferx** [comment]
Bug still exist in current stable version...
