### ISSUE TITLE
Error on efs-csi-driver-registrar 

### ISSUE THREAD

**Issue by abramovi** [kubernetes-sigs/aws-efs-csi-driver#60]
/kind bug

**What happened?**
When new node is starting - I am getting the following error from the efs-csi-node pod:

> Show log entriesMatch expression
Filter
 I0724 08:34:46.315856       1 main.go:138] Version: v0.4.2-2-ga8fd229d
I0724 08:34:46.315904       1 main.go:145] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0724 08:34:46.315912       1 connection.go:69] Connecting to /csi/csi.sock
I0724 08:34:46.316091       1 connection.go:96] Still trying, connection is CONNECTING
I0724 08:34:46.316214       1 connection.go:93] Connected
I0724 08:34:46.316225       1 main.go:153] Calling CSI driver to discover driver name.
I0724 08:34:46.316232       1 connection.go:137] GRPC call: /csi.v0.Identity/GetPluginInfo
I0724 08:34:46.316237       1 connection.go:138] GRPC request: {}
I0724 08:34:46.317465       1 connection.go:140] GRPC response: {}
I0724 08:34:46.317955       1 connection.go:141] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
E0724 08:34:46.317970       1 main.go:158] rpc error: code = Unimplemented desc = unknown service csi.v0.Identity

**This is happening only in latest version of aws-efs-csi-driver docker, when I changed it back to v0.1.0 everything back to normal**

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
- Driver version:
uay.io/k8scsi/driver-registrar:v0.4.2

**Comment by tomerb78** [comment]
same here...

**Comment by wongma7** [comment]
README was just updated, the latest build from `master` won't work with kubernetes versions below 1.14. In particular the error you're seeing is incompatibility between CSI 0.3 and CSI 1.0. Please use v0.1.0 of the driver instead, it will continue to work.

**Comment by leakingtapan** [comment]
Yep. See [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver#kubernetes-version-compability-matrix) for driver compatibility matrix.
