### ISSUE TITLE
Host on public amazon ECR to get around docker throttling

### ISSUE THREAD

**Issue by cep21** [kubernetes-sigs/aws-efs-csi-driver#603]
**Is your feature request related to a problem? Please describe.**
We are being throttled fetching the image from docker hub

**Describe the solution you'd like in detail**
AWS has official verified accounts that they use to mirror things like the `aws-ebs-csi-driver`.  One of these for the efs one would be great.

**Describe alternatives you've considered**
Hosting it ourselves.  But I imagine amazon is happy with people using Amazon's public ECR for the Amazon drivers.

**Comment by cep21** [comment]
![image](https://user-images.githubusercontent.com/20358/146433766-647a0ca0-d4cb-4dfa-a6c2-2e3772f11b38.png)

**Comment by jbg** [comment]
FYI the images are available on ECR (not ECR Public, but it still solves the throttling):

`602401143452.dkr.ecr.${data.aws_region.current.name}.amazonaws.com/eks/aws-efs-csi-driver:${var.image_tag}`
