### ISSUE TITLE
Please help to setup efs access from redhat OCP

### ISSUE THREAD

**Issue by okeedookee** [kubernetes-sigs/aws-efs-csi-driver#620]
Can someone provide some steps to configure ocp to create dynamic provision PVC to AWS EFS? I ran through the process of https://github.com/openshift/aws-efs-csi-driver/blob/master/examples/kubernetes/dynamic_provisioning/README.md. It ends up with errors like following:
```
E0121 01:10:00.861902       1 controller.go:981] error syncing claim "6a328ab7-9001-4138-bcd8-6d9e2a4132ea": failed to provision volume with StorageClass "efs-sc1": rpc error: code = Unauthenticated desc = Access Denied. Please ensure you have the right AWS permissions: Access denied
I0121 01:10:00.861935       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"cp4waiops", Name:"efs-claim1", UID:"6a328ab7-9001-4138-bcd8-6d9e2a4132ea", APIVersion:"v1", ResourceVersion:"168627", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "efs-sc1": rpc error: code = Unauthenticated desc = Access Denied. Please ensure you have the right AWS permissions: Access denied
```
I also tried to follow https://github.com/openshift/aws-efs-csi-driver#installation, but it is specific for EKS while I am running purely Redhat OCP 4.8 and 4.9.  The interesting part is https://github.com/openshift/aws-efs-csi-driver/blob/master/examples/kubernetes/static_provisioning/README.md is working, but not the dynamic approach.

Hope anybody can give me some help set it up. Thanks in advance.

/triage support

**Comment by wongma7** [comment]
the "Set up driver permission:" is the crucial part. while the first option is specific to EKS, the second option 'Using IAM instance profile -' is generic, have you tried that? Essentially you want the Pod to have access to AWS credentials so it can make AWS API calls, this is a problem for all AWS-based distributions and ocp might have a recommendation about that

**Comment by wongma7** [comment]
by 'Pod' I mean the "csi controller" pod, i.e. this one https://github.com/openshift/aws-efs-csi-driver/blob/master/deploy/kubernetes/base/controller-deployment.yaml#L7

**Comment by okeedookee** [comment]
Got it.. Thank you very much!
