### ISSUE TITLE
Add Extra Pod Labels to Helm Chart

### ISSUE THREAD

**Issue by vinayan3** [kubernetes-sigs/aws-efs-csi-driver#627]
**Is your feature request related to a problem?/Why is this needed**
The cluster that the EFS driver is installed in via Helm has pod labeling requirements. To comply with this policy I'd like to be able to add labels to 
* [Controller - Deployment](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/release-1.3/charts/aws-efs-csi-driver/templates/controller-deployment.yaml#L21)
* [Node Dameonset](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/release-1.3/charts/aws-efs-csi-driver/templates/node-daemonset.yaml#L19)

/feature

**Describe the solution you'd like in detail**
See Above

**Describe alternatives you've considered**
No alternatives are available.

**Additional context**
N/A

**Comment by JordyWTC** [comment]
I second this, in AWS EKS Fargate the coredns is setup with the k8s-app = "kube-dns". As it's not possible now to add extra labels, the pod is not getting a node assigned.

**Comment by sppwf** [comment]
Hi Guys,

Is it possible to work a little bit on this Issue?

Thanks
Sergiu Plotnicu

**Comment by qoehliang** [comment]
/reopen, it'd be great to see the ability to add labels to the pod spec. We just need to expose podLabels via values.yaml here
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/controller-deployment.yaml#L22

Similar config to what is already there for podAnnotations:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/controller-deployment.yaml#L26
