### ISSUE TITLE
Is there a way to specify the `Provisioned Throughput` mode for a PVC?

### ISSUE THREAD

**Issue by aperepel** [kubernetes-sigs/aws-efs-csi-driver#628]
I can't seem to find options to configure the performance mode for the claim. Is there a reason or can we add a property to choose between `Bursting Throughput (current default)` and `Provisioned Throughput`?

**Comment by SbgMartin** [comment]
Hi @aperepel ,

the performance mode is defined on AWS EFS itself (bursting, provisioned IOPS) and is used for all volumes using this EFS FileSystem. If you are using bursting mode then you need to have a look at your bursting credits (AWS CloudWatch metrics).

If you need different performance modes available on your K8s cluster using K8s StorageClass with different AWS EFS FileSystems might be a solution for you.

Kind regards
Martin

**Comment by aperepel** [comment]
Thank you, Martin. The use case is a dynamically provisioned EFS file system volume. I don't think I saw any way to specify options there or a generic parameter pass through object in the docs. E.g. there is a lot of flexibility in how one can provision Azure Files (EFS analogue), I hoped to find something similar for the EFS.

Or, if I misunderstood something basic and this is possible for a dynamically provisioned volume (vs pre-creating the EFS), let me know, please.

**Comment by SbgMartin** [comment]
As per my knowledge, only pre-created AWS EFS FileSystems are supported right now. Maybe someone from AWS EFS CSI Driver team could tell about the roadmap towards a dynamic approach.

**Comment by aperepel** [comment]
Would like to convert this question to a feature request to be able to configure the EFS and provision dynamically, I guess.
