### ISSUE TITLE
cluster autoscaler and EFS driver

### ISSUE THREAD

**Issue by satra** [kubernetes-sigs/aws-efs-csi-driver#630]
/kind bug

**What happened?**
cluster autoscaler is not scaling down some groups with the following message: `Fast evaluation: node ip-*.compute.internal is not suitable for removal: failed to find place for kube-system/efs-csi-controller-*`

**What you expected to happen?**

that the csi controller terminates and scales down.

**How to reproduce it (as minimally and precisely as possible)?**

I'm spinning up my own k8s on aws, so minimal is a little tricky to do in this context. 

**Anything else we need to know?**:

my autoscaling groups have minSize zero.

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"202

- Driver version: 1.3 deployed with kubectl apply

**Comment by SbgMartin** [comment]
Hi @satra ,

this looks more like a scheduling issue than an EFS driver issue itself . Do you use node labels, affinities or tolerations to place the controller as well as the DaemonSet on nodes?

**Comment by satra** [comment]
@SbgMartin - thank you. i haven't used an labels/affinities/tolerations. the setup seemed simple. 
```
kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.3"
kubectl apply -f /home/ec2-user/{{ namespace }}/storageclass.yaml
kubectl --namespace={{ namespace }} apply -f /home/ec2-user/{{ namespace }}/pv_efs.yaml
kubectl --namespace={{ namespace }} apply -f /home/ec2-user/{{ namespace }}/pvc_efs.yaml
```
the pvc then gets used by the pods (jupyterhub in this case) when they are spun up on a node. the files are [here](https://github.com/ABCD-ReproNim/reprohub/tree/20c2f6ba4f75911a57038a5c11d92d70e4fd31cc/dandi-info) if interested. once the pod is gone, normally the node would scale down after a while. now it doesn't and i get the message that the efs-controller cannot be placed elsewhere. (ps. i wasusing the master branch but just switched to 1.3 as i started debugging this.)

and my previous renditions of all of this was working till i went to `mixedinstancepolicy` for my spot autoscaling group, and then things seemed to be a lot more fluid in terms of where the pods went and these weirdnesses started with scale down behavior.
