### ISSUE TITLE
[FR] efs-csi-node DaemonSet UpdateStrategy configuration

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes-sigs/aws-efs-csi-driver#634]
**Is your feature request related to a problem? Please describe.**

In clusters with a very high number of nodes the rollout of the efs-csi-node daemonset is very slow and slows down the package upgrade substantially.

**Describe the solution you'd like in detail**
The simplest solution would be to let the updateStrategy be defined at the chart level.

**Describe alternatives you've considered**
None

**Additional context**
Not relevant

**Comment by pierluigilenoci** [comment]
@wongma7 @Ashley-wenyizha could you please take a look?

**Comment by jonathanrainer** [comment]
This is being addressed in #615 :)

**Comment by pierluigilenoci** [comment]
@jonathanrainer #615 seems to be quite stranded. 😢

**Comment by pierluigilenoci** [comment]
@jonathanrainer maybe #740 maybe the 740 has better luck.

**Comment by pierluigilenoci** [comment]
Two PRs have tried to solve this thing, but for now, there is no news. #615 and #740

**Comment by mskanth972** [comment]
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/740 has been merged successfully.
/close
