### ISSUE TITLE
Backup and Restore a Access Point ID

### ISSUE THREAD

**Issue by vakkursw** [kubernetes-sigs/aws-efs-csi-driver#641]
We are using an EKS cluster with an EFS driver to persist the data from statefulset. 

There are several access points that use the same EFS to mount the data from different Statefulsets. 
I  would like to back up the data from one of these access points which is referenced by one of the PVs and restore the content in a different EKS cluster. I have seen EBS driver has the snapshot feature, looking for some guidance on how this can be achieved using EFS CSI drivers.
<img width="1444" alt="2022-02-23_11-49-32" src="https://user-images.githubusercontent.com/95715828/155378131-c321730c-88a5-4db2-a035-4750aa9f4822.png">

**Comment by ganesh-katakam-T18451** [comment]
Any update?
