### ISSUE TITLE
Feature Suggestion: Multiple EFS volumes per storage class (example implementation done)

### ISSUE THREAD

**Issue by artificial-aidan** [kubernetes-sigs/aws-efs-csi-driver#642]
**Is your feature request related to a problem? Please describe.**
The limit of 120 access points per EFS means there is a max number of PVCs per storage class

**Describe the solution you'd like in detail**
Allow multiple EFS volumes per storage class

I took a stab at this and it's working in my test environment. I accepted a comma separated list of EFS Filesystem Ids, and then check to see if they have the max number of access points before using one.

Is this something that would be considered? Here is the branch in my fork that contains the changes: https://github.com/artificial-aidan/aws-efs-csi-driver/tree/aidan/multi-efs

Possible improvements:
* Query the quota for max number of APs per filesystem instead of hardcoding it. Or at least take it in as an argument.

**Comment by djmcgreal-cc** [comment]
I'd love to see >120 AP supported, and this seems like a compelling approach from a usability perspective. Would be great if the MR get some attention to inform whether it's a goer from a technical or roadmap approach?

**Comment by artificial-aidan** [comment]
FWIW I've been using this implementation since March without issues.

**Comment by 617m4rc** [comment]
The limit of 120 APs is a major issue for us, so I'd love to see this flexibility added to the driver. What needs to be done to get #761 reviewed?

**Comment by artificial-aidan** [comment]
Still running this in production. It seems to be working well still.

**Comment by 617m4rc** [comment]
With the increase of the maximum number of APs per file system from 120 to 1000 in January, this feature request is most likely becoming obsolete.

**Comment by techdragon** [comment]
Given its been made to work already, it seems silly to let this rot.

/remove-lifecycle rotten
