### ISSUE TITLE
Do we support to configure "Path" in static mode?

### ISSUE THREAD

**Issue by zhushendhh** [kubernetes-sigs/aws-efs-csi-driver#649]
I see the files are created in the root path of EFS, do we support to use specified paths? 
Or do we support to directly use EFS without CSI?

Thank you.

**Comment by Ashley-wenyizha** [comment]
Do you mean 'basePath'?

basePath (Optional) - Path on the file system under which access point root directory is created. If path is not provided, access points root directory are created under the root of the file system.

https://github.com/kubernetes-sigs/aws-efs-csi-driver#readme
