### ISSUE TITLE
Allow volume expansion / resizing an in-use pvc

### ISSUE THREAD

**Issue by Anticom** [kubernetes-sigs/aws-efs-csi-driver#668]
**Is your feature request related to a problem? Please describe.**
When trying to change the requested storage of a PVC I'm getting:
```console
Error from server (Forbidden): persistentvolumeclaims "my-example-pvc" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```

Since the EFS SC is dynamically provisioning volumes I am assuming that resizing volumes is supported as well. Neither the [aws efs csi driver docs](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html) nor this repo does document the current state of being able to dynamically resize volumes anywhere.  
Hence I'm not even entirely sure whether aws-efs-csi-driver is supposed to support this right now and I'm having issues due to miss configuration or whether the driver currently does not support dynamic resizing of PVs.

**Describe the solution you'd like in detail**
I'd like the provisioned SC to have `allowVolumeExpansion` set to true.

**Describe alternatives you've considered**
none

**Additional context**
* [k8s docs about SC volume expansion](https://kubernetes.io/docs/concepts/storage/storage-classes/#allow-volume-expansion)
* [k8s docs about resizing in-use PVCs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#resizing-an-in-use-persistentvolumeclaim)
* [k8s blog post about resizing PVs at k8s version 1.11](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/)

Deployed via Helm, currently using chart version 2.1.5 (app version 1.3.3).

**Steps to reproduce**

```sh
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-example-pvc
spec:
  storageClassName: your-efs-sc-name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
EOF
```

After the PVC has been provisioned successfully, run:
```sh
kubectl patch pvc my-example-pvc -p '{"spec": {"resources": {"requests": {"storage": "16Mi"}}}}'
```

**Comment by steveizzle** [comment]
I am not from the project, but this is a quote from [https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/](https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/)

_Note that the actual storage capacity value in the persistent volume claim is not used, given the elastic capabilities of EFS. However, since the storage capacity is a required field in Kubernetes, you must specify a value._ 

I think this has to be discussed and it is a matter of taste, but in my opinion it would be less confusing to have allowVolumeExpansion set to true. Even if the expansion has no real effect on the volume.

**Comment by Anticom** [comment]
> I am not from the project, but this is a quote from https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/
> 
> _Note that the actual storage capacity value in the persistent volume claim is not used, given the elastic capabilities of EFS. However, since the storage capacity is a required field in Kubernetes, you must specify a value._
> 
> I think this has to be discussed and it is a matter of taste, but in my opinion it would be less confusing to have allowVolumeExpansion set to true. Even if the expansion has no real effect on the volume.

So if I'm understanding you correctly what you're saying is that the specified limits are not enforced?
