### ISSUE TITLE
Run containers with readOnlyRootFilesystem

### ISSUE THREAD

**Issue by entscheidungsproblem** [kubernetes-sigs/aws-efs-csi-driver#682]
**Is your feature request related to a problem? Please describe.**
 Running containers with a read-only root filesystem--when feasible--is considered a best practice. Not doing so causes EFS CSI driver containers to get flagged by security scanners/linters/questionnaires/overzealous admission controllers.

**Describe the solution you'd like in detail**
 Support running some or all containers with readOnlyRootFilesystem: true.

**Describe alternatives you've considered**
 An explanation as to why a read-write container filesystem is required is also totally fine. But I would expect that at least some of the containers in EFS CSI driver don't need it.

**Additional context**
Copied from [issue in aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1101).

**Comment by mskanth972** [comment]
Thanks for bringing here. Seems the same issue as [749](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/749). Will address it soon by adding in the security context.

**Comment by mskanth972** [comment]
Closing the issue as [PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1001) for enabling security context for container level is merged and will mark it in the coming release.
