### ISSUE TITLE
Regional STS endpoint is not in chart (v2.2.6) anymore

### ISSUE THREAD

**Issue by MatteoMori** [kubernetes-sigs/aws-efs-csi-driver#686]
/kind bug

**What happened?**
I have a private cluster and I am trying to configure regional STS. I can see that v2.2.5 of this chart does support [regional endpoints](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/helm-chart-aws-efs-csi-driver-2.2.5/charts/aws-efs-csi-driver/values.yaml#L79) while v2.2.6 does not have an option anymore.

Is the process different now?

thanks!

**Comment by BlackDark** [comment]
Maybe something is fishy with release script or automation? the variable and code is still available on the master branch and somehow got dropped between the tagging?
