### ISSUE TITLE
I would like an option to use EFS that doesn't require modifying node instancy policies.

### ISSUE THREAD

**Issue by bwinter** [kubernetes-sigs/aws-efs-csi-driver#690]
**Is your feature request related to a problem? Please describe.**
I am working with clusters where I don't have control over node provisioning. Currently the [EFS CSI driver installation documentation](https://github.com/kubernetes-sigs/aws-efs-csi-driver#set-up-driver-permission) shows the driver only supports IAM instance policy options for granting it permission to talk to EFS.

Possibly obviously, I would like to be able to use EFS dynamic provisioning but cannot.

**Describe the solution you'd like in detail**
I would like to be able to use the EFS provider without having to modify nodes and their instance policies.

**Describe alternatives you've considered**
I see that [the EBS driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/README.md#set-up-driver-permission) is able to use a secret object. Is this something EFS could support? I believe this would get me around my inability to modify node instance policies.

**Additional context**
N/A

**Comment by bwinter** [comment]
Oh cool. Maybe the ask here is to update the docs and add an example?

**Comment by bwinter** [comment]
One of my biggest struggles with those EKS docs is I am not using EKS. Converting those instructions which are so EKS heavy is not triavl for me, specific documentation - similar to what ebs has would be nice. Additionally, all I really need to do with ebs is add an account secret to the cluster - where it looks like I need to do some surgery on the efs manifests any time I want to update them / install them etc.

**Comment by rmccarth** [comment]
@bwinter did you get EBS working with a non-aws cluster? I would be interested in seeing your steps as I'm trying to do the same thing.
