### ISSUE TITLE
Add tags to dynamically created Access Points using YAML file

### ISSUE THREAD

**Issue by dheerajgss** [kubernetes-sigs/aws-efs-csi-driver#692]
**Is your feature request related to a problem? Please describe.**

Whenever an access point is created dynamically using PV/PVC with the help of the EFS CSI driver, there are no tags associated with it to identify which PVC it belongs to (or) there is no way to add tags using the YAML file to categorize which pods/deployments are using those access points.

For example, if I want to use an access point with one of my application pods while creating a PVC for it, I want to tag that access point from the YAML file itself to know and notify other users that this particular access point is being used by this application pods/deployment.

**Describe the solution you'd like in detail**

Tweaking the YAML file definition to add the 'tags' parameter as well.

**Describe alternatives you've considered**

Open the AWS EFS console, search for the dynamically created access point, and then use the 'Manage Tags' option to add more tags. There is also the 'extraCreateMetadata' option which can be added to the helm chart, but it only provides static tags to all the access points created and does not support adding customized tags as per access point usage.

**Comment by dheerajgss** [comment]
#689 partially covers the requirement, but if I want to categorize my access points in a much-refined way (like application level or pod level as mentioned in my initial description) then these static tags would not help me.

**Comment by jonathanrainer** [comment]
Ah yes I see what you mean. Would you be happy to be able to set the tags per StorageClass? Or do you need it more fine grained than that?

**Comment by dheerajgss** [comment]
StorageClass settings would help I guess. I don't have any ideas about fine graining it as of now😅.
