### ISSUE TITLE
error: git cmd = '/usr/bin/git checkout FETCH_HEAD': exit status 128

### ISSUE THREAD

**Issue by juanise** [kubernetes-sigs/aws-efs-csi-driver#697]
/kind bug

What happened?
If I try to install driver with:
kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr/?ref=release-1.3"
or
kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.3"
I get an error
error: git cmd = '/usr/bin/git fetch --depth=1 origin release-1.3': exit status 128
What you expected to happen?
command end wihtout error and get driver installed
How to reproduce it (as minimally and precisely as possible)?
just execute
kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr/?ref=release-1.3"

Anything else we need to know?:

Environment

    Kubernetes version (use kubectl version):
    Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-14c7a48", GitCommit:"35f06c94ad99b78216a3d8e55e04734a85da3f7b", GitTreeState:"clean", BuildDate:"2022-04-01T03:18:05Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
    Driver version: 1.3

**Comment by bwinter** [comment]
As a workaround you might try adding `&timeout=90s` to your url. That got me past the same error in a similar context.

**Comment by juanise** [comment]
Thank you i'will try your solution. But finally I clone the repository and execute kubectl apply -k  locally
