### ISSUE TITLE
Instructions for installing EFS CSI driver on non-EKS clusters.

### ISSUE THREAD

**Issue by bwinter** [kubernetes-sigs/aws-efs-csi-driver#713]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I would like to use the EFS driver in a non-EKS cluster.

**Describe the solution you'd like in detail**

I would like documentation on how to do this. Or if it is not possible, mention that explicitly.

**Additional context**

I have been trying this on my own and I seem all documentation requires an identity provider currently - when not using EKS this is non trivial.

Is there a way I can use the authorize the driver using a service account IAM user's key and token? (Maybe something like what EBS supports? https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/base/controller.yaml#L48-L59)

**Comment by rmccarth** [comment]
Did you ever get an answer to your question @bwinter ?

**Comment by cqc5511** [comment]
I agree this would be really helpful
