### ISSUE TITLE
Allow dynamic provisioning to use the same access point between multiple PVCs and Namespaces

### ISSUE THREAD

**Issue by wmgroot** [kubernetes-sigs/aws-efs-csi-driver#715]
**Is your feature request related to a problem? Please describe.**
We currently have a desire to share the same EFS path between pods in different namespaces. I could set this up using static provisioning and explicit PV specifications, but I would need to create a PV for each supported namespace, since each PVC can claim one and only one PV.

We would like to support attaching a shared EFS path across pods in an arbitrary number of namespaces.

**Describe the solution you'd like in detail**
I believe this could be accomplished with a parameter in the StorageClass specification that effectively overrides the logic that maps PV ids to sub paths within the EFS. Any PVC using the StorageClass with the suggested parameter would mount the same shared space to these pods, allowing our users to share a filesystem between their namespaces.

It is understood that these users would be able to clobber files that each pod had written to this shared filesystem. Having a mechanism to designate namespaces that are allowed to write, and namespaces that are allowed to read is nice to have, and not required. I think this could be alternatively enforced via an OPA policy or similar on the PVC being ReadWriteMany or ReadOnlyMany instead of the CSI driver implementing this enhancement.

**Describe alternatives you've considered**
I've been reading through the docs and examples thoroughly, but I cannot think of an alternative implementation that supports an arbitrary number of namespaces and PVs. Please let me know if there's a way to accomplish this use case without a new feature.

**Comment by jonathanrainer** [comment]
If you look at the implementation in #640 that would solve your problem wouldn't it? You could set the subPathPattern to be deterministic/templated depending on what you want and setting ensureUniqueDirectories to false would mean you would get the sharing behaviour you want. Like you say you'd need to take care but wouldn't that work?

**Comment by wmgroot** [comment]
Thanks for the reply, I'll give that a try and report back.
