### ISSUE TITLE
Pod Fails with: 0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. efs 

### ISSUE THREAD

**Issue by ptwohig** [kubernetes-sigs/aws-efs-csi-driver#728]
/kind bug

**What happened?**

Deploying via helm, the EFS driver will attempt to run two pods. One pod runs fine, one pod fails with the following message:

```0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. efs```

**What you expected to happen?**

I'm not sure the intended behavior. I suspect that:

* All pods start up properly.
* Two pods using the same port aren't launched on the same node.

**How to reproduce it (as minimally and precisely as possible)?**

I am running a simple cluster which deploys a single m5.medium node in to AZs. I believe this is the minimum required node pool.

**Anything else we need to know?**:

I've tried two separate ways to install the driver. This happens with the instructions provided as well as my Terraform configuration.

```
helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver/
helm repo update
helm upgrade --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver
```
Or
```
resource "helm_release" "efs_csi_driver" {
  name = "aws-efs-csi-driver"
  chart = "aws-efs-csi-driver"
  repository = "https://kubernetes-sigs.github.io/aws-efs-csi-driver/"
  namespace = "kube-system"
}
```

If I were to guess it's making one pod for each AZ but since I'm running one pod it's trying to place two pods on the same machine resulting in the port conflict. 

The problem for Terraform users is that if all pods aren't healthy within five minutes of launch, the deployment fails. 

**Environment**

- Kubernetes version (use `kubectl version`):
```
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.22.9-eks-a64ea69
```

- Driver version: Unsure. I'm presuming the master version.

**Comment by ptwohig** [comment]
Yep. Confirmed that by adding a second node to my pool solves the issue.

**Comment by dremmos** [comment]
@jonathanrainer Hey. Had the same issue with an old version of the driver. Can confirm that it is now working with 1 node and Helm Chart 2.2.7.

**Comment by h1manshu98** [comment]
Any update on this ?

Getting the same error in helmchart version : `2.4.4`
```bash
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  3m36s (x2 over 8m48s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..

```

### terraform
```hcl
    name        = "aws-efs-csi-driver"
    chart       = "aws-efs-csi-driver"
    repository  = "https://kubernetes-sigs.github.io/aws-efs-csi-driver/"
    version     = "2.4.4"
    namespace   = "kube-system"
    description = "AWS EFS CSI Driver helm Chart deployment configuration"
```

**Comment by anandshivam44** [comment]
As of Today this problem still exists 

```bash
4m2s        Warning   FailedScheduling    pod/efs-csi-controller-6ffcb4cf58-r5cs9    0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports..

```

helm version = "~> 2.10.1
k88 version 1.27
efs CSI driver version v1.5.8 and v1.5.9
