### ISSUE TITLE
Remove hostNetwork from Helm chart

### ISSUE THREAD

**Issue by plockaby** [kubernetes-sigs/aws-efs-csi-driver#736]
/kind bug

**What happened?**

Now that #681 has been merged and released, allowing `hostNetwork` to be removed from configurations, can the helm chart be updated to remove `hostNetwork`?

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/5e1fcd3e915d62d3b091c6de780ff9e6816f3a7b/charts/aws-efs-csi-driver/templates/node-daemonset.yaml#L52

**What you expected to happen?**

I expect no host network.

**How to reproduce it (as minimally and precisely as possible)?**

Current helm chart sets up the `efs-csi-node` pods with `hostNetwork: true`.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 

Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

- Driver version: 1.4.0
- Chart version: 2.2.7

**Comment by groodt** [comment]
I believe we can remove it. I've tested the changes and it works for me. I raised a PR here https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/851
