### ISSUE TITLE
Allow seting updateStrategy

### ISSUE THREAD

**Issue by lefterisALEX** [kubernetes-sigs/aws-efs-csi-driver#739]
Default setting of the chart do not allow defining the updateStrategy of controller deployment neithe daemonset.
I made this [PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/740) which will allow this to be configured in `values.yaml`

**Comment by pierluigilenoci** [comment]
This is a clone of #634

**Comment by mskanth972** [comment]
#740 PR has been merged
/close
