### ISSUE TITLE
Cannot get efs-csi-node to Assume Role

### ISSUE THREAD

**Issue by sinkr** [kubernetes-sigs/aws-efs-csi-driver#746]
/kind bug

**What happened?**

Hello, thanks for your help in advance!

Chart 2.2.7 (I have also tried chart 2.1.5 to no avail):

_efs-csi-controller_, according to CloudWatch, correctly assumes the EFS role using the prescribed policy in the documentation [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json) and create an access point, however, _efs-csi-node_ with the same annotation will not assume the rule.

When I exec into an _efs-csi-node_ pod, install _awscli_ and perform `aws sts get-caller-identity`, the assumed role is correct.  

The annotation is set correctly on the DaemonSet's annotation, and the _AWS_ROLE_ARN_ environment variable are correctly set, however, while I see _efs-csi-controller_ correctly assuming the role for activities such as `CreateAccessPoint`, anything coming from _efs-csi-node_ comes across as _ANONYMOUS_PRINCIPAL_.

**What you expected to happen?**
I expect _efs-csi-node_ to assume the EFS-specific role using the prescribed policy in the documentation just like _efs-csi-controller_ correctly does, per the annotation in the SA + what is shown on the pod under _AWS_ROLE_ARN_.

**How to reproduce it (as minimally and precisely as possible)?**

1. Helm install chart v2.2.7
2. Create the IAM role w/ the prescribed policy in the documentation here.
3. Update the trust policy to allow both node and controller service accounts to assume the IAM role.
4. Apply the EFS policy allowing the IAM role access to the EFS filesystem.
5. Annotate the service accounts for both the controller and node w/ the IAM role from step 2 above.
6. Create the storage class using the FSid in _examples/kubernetes/dynamic_provisioning/specs_.
7. Create the pod using _pod.yaml_ in examples/kubernetes/dynamic_provisioning/specs
8. Inspect the efs-csi logs from Kubernetes (permission denied)
9. Inspect the CloudWatch logs for  all `elasticfilesystem` activity in the last minute (see that _efs-csi-controller_ correctly assumes the EFS role and that _efs-csi-node_ comes across as _ANONYMOUS_PRINCIPAL_.

**Anything else we need to know?**:

efs-csi-controller correctly assumes the role, but
efs-csi-node does not attempt to assume the role, issues no error, even at `logLevel 9`, instead attempting to mount EFS via _ANONYMOUS_PRINCIPAL_.

**Environment**
- Kubernetes version (use `kubectl version`):
EKS 1.22

- Driver version:
1.4.0

**Comment by nicoodle** [comment]
Seeing the same on v1.5.6

**Comment by gadiener** [comment]
Same on v1.5.7

**Comment by andrewhharmon** [comment]
as a workaround i think you can specify the iam mount_option flag on the storageClass or the PV. That seemed to resolve it for me. I set a file system policy and it stated failing bc it was coming in as anonymous.

**Comment by icj217** [comment]
Also seeing this behavior. Not sure if there was a regression since [this](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/280#issuecomment-1370718319) comment
