### ISSUE TITLE
Dead link on README.md at 'Uncomment annotations and put the IAM role ARN in service-account manifest'

### ISSUE THREAD

**Issue by good92** [kubernetes-sigs/aws-efs-csi-driver#756]
/kind bug

**What happened?**
Clicked on 'Uncomment annotations and put the IAM role ARN in "service-account manifest"'

It points to a removed/renamed file:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/deploy/kubernetes/base/serviceaccount-csi-controller.yaml

Should we use this file instead? : 
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/deploy/kubernetes/base/controller-serviceaccount.yaml

**What you expected to happen?**
Navigate to the correct file.

**How to reproduce it (as minimally and precisely as possible)?**
1. Go to https://github.com/kubernetes-sigs/aws-efs-csi-driver#set-up-driver-permission
2. Click on "service-account manifest"'

**Anything else we need to know?**:
N/A

**Environment**
- Kubernetes version (use `kubectl version`): N/A - web
- Driver version: N/A

**Comment by mskanth972** [comment]
Hi, thanks for bringing to our attention. Will update the Doc and close the issue.

**Comment by mskanth972** [comment]
The README.md is updated. Closing the issue.
