### ISSUE TITLE
Update the Kubernetes Version Compability Matrix in README.md for 1.4.x

### ISSUE THREAD

**Issue by jebbens** [kubernetes-sigs/aws-efs-csi-driver#783]
A user wants to look at the Kubernetes Version Compability Matrix in README.md to see what versions of Kubernetes will work with version 1.4.x.

/triage support

**Comment by mskanth972** [comment]
@jebbens Thanks for letting us know. 
Updated the Kubernetes Version Compability Matrix in README.md
closing the issue.
