### ISSUE TITLE
1.4.2 changelog is missing

### ISSUE THREAD

**Issue by mazay** [kubernetes-sigs/aws-efs-csi-driver#784]
/kind bug

**What happened?**

The [CHANGELOG](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/CHANGELOG-1.x.md) is missing version 1.4.2

**What you expected to happen?**

I'd like to see the list of changes included in the 1.4.2 release.

**Comment by tjdett** [comment]
I'm trying to work out why pod impersonation was removed in 1.4.2:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/commit/863fa0b9c114920a4a3dd8d30f004961f185276d

It would be really helpful to have this changelog so I understand if 1.4.1 is broken, as there's no reference to why it was removed in #777 or #710 .

**Comment by rubroboletus** [comment]
It is always problem with new release. efs driver team is always pointing to CHANGELOG, but they always forget to update CHANGELOG.
