### ISSUE TITLE
Does the Pod implementation feature support dynamic provision ?

### ISSUE THREAD

**Issue by zhushendhh** [kubernetes-sigs/aws-efs-csi-driver#795]
I am happy to see that the feature "Pod Implementation" was released in version 1.4.11

But I didn't see the example from the Github. From the below link, it only shows a example for static provision mode:
[examples/kubernetes/pod_iam_impersonation/README.md](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/710/files#diff-71ad284fa68ed32ba2442a502ced05fb895a002ad18fff8c9254fc6e8f9a32f5)
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/710/files 

So how can I find the example to deploy it by steps ? And does it support dynamic provision ?

Thank you.

**Comment by zhushendhh** [comment]
Then how to deploy the CSI with podIAMAuthorization=true ?

I am tried to setup it via below command:
`helm upgrade -i aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver \
    --namespace kube-system \
    --set image.repository=xxxxxxxxxxxxx.dkr.ecr.us-east-2.amazonaws.com/eks/aws-efs-csi-driver \
    --set controller.serviceAccount.create=false \
    --set controller.serviceAccount.name=efs-csi-controller-sa \
    --set podIAMAuthorization=true`

But after creating SC/PV/PVC/Pod， I still got the error: 
`Warning  FailedMount  12s (x7 over 44s)  kubelet            MountVolume.SetUp failed for volume "efs-iam-pv1" : rpc error: code = InvalidArgument desc = Volume context property podIAMAuthorization not supported`

**Comment by Ashley-wenyizha** [comment]
Unfortunately this feature was rolled back because a security concern from EKS side. We will add this feature in efs-utils instead but not clear on the timeline when this can be released.
