### ISSUE TITLE
E2E tests can't run in kubernetes v1.25

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-sigs/aws-efs-csi-driver#807]
/kind bug

**What happened?**
kubernetes 1.25 started using ginkgo v2 however this repo is still using v1 and therefore the tests in https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/test/e2e/e2e.go will fail if the kubernetes version in `go.mod` is updated.

**What you expected to happen?**
The tests to run successfully in 1.25, maybe this repo should start using ginkgo v2 too.

**How to reproduce it (as minimally and precisely as possible)?**
Create a 1.25 cluster, run the e2e test

**Environment**
- Kubernetes version (use `kubectl version`): 1.25
- Driver version: latest

**Comment by mauriciopoppe** [comment]
More info: https://github.com/onsi/ginkgo/issues/945

**Comment by mauriciopoppe** [comment]
I found out the issue by comparing two runs:

- 1.24 k8s cluster with the ginkgo binary from OSS v1.24 which is v1
- 1.25 k8s cluster with the ginkgo binary from OSS v1.25 which is v2

I think it depends on how the binary in `test/e2e` is run, we run it like this:

```
go test -mod=vendor -ldflags -c -o bin/test-e2e ./test/e2e/
```

And then wrap the execution of the binary with the ginkgo binary from k8s:

```
# download the release from https://dl.k8s.io/v1.25.0/kubernetes-test-linux-amd64.tar.gz"
# untar the file and take the ginkgo binary

ginkgo bin/test-e2e -- ...
```

In this specific scenario it fails, I'm not sure what would happen if we run it without ginkgo as a wrapper though

**Comment by seanzatzdev-amazon** [comment]
[This PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1118) resolves failing e2e tests when run against a local EKS cluster, seems that the Ginkgo version has been updated as well. We are planning to include the aforementioned PR in the next release.

**Comment by mskanth972** [comment]
The above [PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1118) is released. Please feel free to open if you are facing the issue still.
/close
