### ISSUE TITLE
AMR64 images missing from ECR registry

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [kubernetes-sigs/aws-efs-csi-driver#819]
/kind bug

**What happened?**
AMR64 images for some components are missing from the 602401143452 ECR registry.

**What you expected to happen?**
All AMD64 images should have an equivalent AMR64 image, just like they do on Public ECR.

**How to reproduce it (as minimally and precisely as possible)?**

```sh
$ skopeo --override-os linux --override-arch arm64 inspect docker://602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner:v2.1.1
FATA[0002] Error parsing manifest for image: choosing image instance: no image found in manifest list for architecture arm64, variant "", OS linux 

$ skopeo --override-os linux --override-arch arm64 inspect docker://602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.2.0
FATA[0002] Error parsing manifest for image: choosing image instance: no image found in manifest list for architecture arm64, variant "", OS linux 

$ skopeo --override-os linux --override-arch arm64 inspect docker://602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v2.1.0
FATA[0002] Error parsing manifest for image: choosing image instance: no image found in manifest list for architecture arm64, variant "", OS linux 
```

**Anything else we need to know?**:
This problem is exactly the same as kubernetes-sigs/aws-ebs-csi-driver#1136 and probably is the fix. There, starting at some version, ARM64 images started to be pushed to Private ECR and the version of these components used by the CSI Driver were updated.

**Environment**
- Kubernetes version (use `kubectl version`): v1.22.15-eks-fb459a0
- Driver version: v1.4.1

**Comment by t0rr3sp3dr0** [comment]
@wongma7, can we update the version of the components used by AWS EFS CSI Driver to match the versions used by AWS EBS CSI Driver or is there something that requires us to use the old versions on this CSI Driver?

**Comment by collinhayden** [comment]
Running into this issue also.  When I docker inspect the relative images on the nodes that are having issue, I see they are running the amd64 version and not the arm64 version like they are supposed to be.  Therefore the liveness checks fail and things are in a backoff loop.  Is there a work around for this issue?

**Comment by collinhayden** [comment]
Just FYI, for someone else who might find it useful, as an interim and fix for us, we moved from using the path:
deploy/kubernetes/overlays/stable/ecr

to 

deploy/kubernetes/overlays/stable

and this works since the private repos for the sidecar containers in the pod aren't using the private repo, but the public and this seems to be where things are broken.  We are using kustomize as the installer, but noticed that the helm doesn't have that issue and we'll be moving to that instead later.

**Comment by mskanth972** [comment]
Hi [t0rr3sp3dr0](https://github.com/t0rr3sp3dr0), thanks for bringing here. Can you please confirm are you still facing this issue?

**Comment by mskanth972** [comment]
Closing the issue as there is no reply further. Please feel free to open if you are still facing the issue.
/close
