### ISSUE TITLE
Add support fo IAM for Service Account

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-efs-csi-driver#82]
**Is your feature request related to a problem? Please describe.**
Similar to https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/361

**Comment by leakingtapan** [comment]
This is only needed until dynamic provisioning is implemented

**Comment by jurgenweber** [comment]
I don't think this should get closed.. this is super important.
