### ISSUE TITLE
Performance of aws-efs-csi-driver vs. aws efs provisioner

### ISSUE THREAD

**Issue by chrisvdb** [kubernetes-sigs/aws-efs-csi-driver#83]
We're currently using the AWS EFS Provisioner (https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs) in a production environment. The driver works perfectly (after some initial tinkering) except that performance is abominable (several minutes to copy ~60MB file from instance to EFS and several seconds to do a directory listing).

I would like to understand if aws-efs-csi-driver is excepted to improve the performance (throughput and latency) or if we can expect the same/similar performance when we switch over.

**Comment by wongma7** [comment]
The main difference is that the provisioner mounts using NFS and this driver uses the EFS mount helper. Documentation makes no claim about one performing better than the other--the performance depends mostly on the mode of your filesystem, Bursting Throughput or Provisioned Throughput: https://docs.aws.amazon.com/efs/latest/ug/performance.html. If you're seeing "abominable" performance, you may be out of burst credits. Consider testing with the provisioner out of the equation (mount manually on a node) and if the problem persists, contact AWS directly for help.

**Comment by brunojcm** [comment]
@chrisvdb I've just migrated an app whose attachments are now in an EFS volume using the CSI driver, it took me ~30 minutes to transfer all files (5.6GB) from the old EC2 instance to the new container/EFS mount, using SSH, same AWS Region.

About listing, this is what I get (`/usr/src/app/files` is an EFS volume):
```
root@app-deployment-6697899fd4-kr4c8:/usr/src/app# time du -h --summarize /usr/src/app/files/
5.6G	/usr/src/app/files/

real	0m34.647s
user	0m0.054s
sys	0m0.514s
```

I'd guess average file size is 2MB.

Haven't tried EFS provisioner, but the performance looks pretty good so far.
