### ISSUE TITLE
Can't fetch metrics from Kubelet

### ISSUE THREAD

**Issue by SoulKyu** [kubernetes-sigs/aws-efs-csi-driver#841]
/kind bug

**What happened?**
I'm not able to get metrics for EFS on Kubelet

**What you expected to happen?**
Metrics available when option --vol-metrics-opt-in=true is enable

**How to reproduce it (as minimally and precisely as possible)?**
Create an EFS volume and deploy EFS-CSI with option --vol-metrics-opt-in=true on daemonset and deployment

**Anything else we need to know?**:
Their is the error message : 
W1130 14:58:32.816102       1 vol_statter.go:67] Volume metrics computation is underway for Vol ID: fs-0207ba5f1b1fc47bb::fsap-08f9f0c566872a8a7 and metrics are not available yet.
![image](https://user-images.githubusercontent.com/30684712/204832422-da6e7da9-0a06-4d96-8d71-74695d67d2a8.png)

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version: 602401143452.dkr.ecr.us-west-1.amazonaws.com/eks/aws-efs-csi-driver:v1.4.5

**Comment by makomatic** [comment]
> Create an EFS volume and deploy EFS-CSI with option --vol-metrics-opt-in=true on daemonset and deployment

_--vol-metrics-opt-in_ is not [implemented](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/node-daemonset.yaml) for the node daemonset.

Did you do that locally? Then please update #701 with your findings. If not, I'm afraid you'll have to wait for the upstream fix or fix it yourself locally.,

**Comment by mskanth972** [comment]
Hi @SoulKyu, thanks for bringing here. Can you pass the argument in the daemonset and post the logs of the csi-node here. I can help take a look at it.

**Comment by mskanth972** [comment]
Closing the issue as there is no further response. Please feel free to open if you need further assistance.
/close
