### ISSUE TITLE
mount failed: exit status 255

### ISSUE THREAD

**Issue by BartoszZawadzki** [kubernetes-sigs/aws-efs-csi-driver#887]
/kind bug

**What happened?**

So this happens every now and then, during our "morning rush-hour traffic" - when multiple environments (pods) are being deployed in our kubernetes cluster. All of our application pods have volumes that are connected to EFS through StorageClass.

Some of our pods are stuck at ContainerCreating status and no matter how much time passes the stay stuck with information:
```
  Warning  FailedMount  2m40s                kubelet            Unable to attach or mount volumes: unmounted volumes=[dumps], unattached volumes=[dumps scripts kube-api-access-mcwmt]: timed out waiting for the condition
  Warning  FailedMount  24s (x5 over 4m39s)  kubelet            MountVolume.SetUp failed for volume "pvc-3c098f00-55d6-4e9e-a378-39a95808214e" : rpc error: code = Internal desc = Could not mount "fs-0edbebe22b49aXXXX:/" at "/var/lib/kubelet/pods/b6bdcf96-2c49-4f48-9955-1750a7f51994/volumes/kubernetes.io~csi/pvc-3c098f00-55d6-4e9e-a378-39a95808214e/mount": mount failed: exit status 255
Mounting command: mount
Mounting arguments: -t efs -o accesspoint=fsap-012be83a94b06292b,tls fs-0edbebe22b49a8310:/ /var/lib/kubelet/pods/b6bdcf96-2c49-4f48-9955-1750a7f51994/volumes/kubernetes.io~csi/pvc-3c098f00-55d6-4e9e-a378-39a95808214e/mount
```

If also checked the syslog on that particular machine that the pod is scheduled on and I've noticed something similar:
```
"MountVolume.SetUp failed for volume \"pvc-3c098f00-55d6-4e9e-a378-39a95808214e\" (UniqueName: \"kubernetes.io/csi/efs.csi.aws.com^fs-0edbebe22b49a8310::fsap-012be83a94b06292b\") pod \"scrapper-pr-9892-668799656d-z5c8f\" (UID: \"48de144e-6ac7-4f1d-8752-88c273f25571\") : rpc error: code = Internal desc = Could not mount \"fs-0edbebe22b49aXXXX:/\" at \"/var/lib/kubelet/pods/48de144e-6ac7-4f1d-8752-88c273f25571/volumes/kubernetes.io~csi/pvc-3c098f00-55d6-4e9e-a378-39a95808214e/mount\": mount failed: exit status 255\nMounting command: mount\nMounting arguments: -t efs -o accesspoint=fsap-012be83a94b06292b,tls fs-0edbebe22b49aXXXX:/ /var/lib/kubelet/pods/48de144e-6ac7-4f1d-8752-88c273f25571/volumes/kubernetes.io~csi/pvc-3c098f00-55d6-4e9e-a378-39a95808214e/mount\nOutput: "
```
I've found a workaround to fix this - which is basically killing a `efs-csi-node` Pod (that is launched from `efs-csi-node` DaemonSet) which is running on the instance in question - after that mounting issues disappear until the next morning.

**What you expected to happen?**

EFS mounted successfully, Pod up and running

**How to reproduce it (as minimally and precisely as possible)?**

Deploy aws-efs-csi-driver to kubernetes cluster and launch multiple pods (20+) with volumes and volumeMounts that use StorageClass with EFS underneath. 

**Anything else we need to know?**:

Kubernetes cluster is built by kops on AWS. Base image for our EC2 instances (both master and worker nodes): Ubuntu 20.04.5 LTS.

**Environment**
- Kubernetes version (use `kubectl version`): v1.21.14
- Driver version: 1.49 (kubernetes-csi-external-provisioner-version: 3.4.0-eks-1-21-24; kubernetes-csi-liveness-probe-version: 2.9.0-eks-1-21-24; kubernetes-csi-node-driver-registrar-version: 2.7.0-eks-1-21-24)

**Comment by RyanStan** [comment]
Hi @BartoszZawadzki, we'll try to reproduce this on our end.  In the meantime, can you pull logs and post them here?  [Our troubleshooting guide](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting) has instructions on how to enable debug logging for efs-utils, and then use the log collector script to pull the logs (after another failure occurs).

**Comment by BartoszZawadzki** [comment]
Sorry for the delay, but due to that issue I was forced to disable the aws-efs-csi-driver in our cluster, and currently I don't have the data. I will try to get the necessary information to you some other way.

**Comment by Ashley-wenyizha** [comment]
Hi  @BartoszZawadzki

We will close this issue for now, feel free to re-open this issue after you have log in hand.

Thanks for reaching out to use!
