### ISSUE TITLE
Update k8s versions in go.mod / update golang version

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/aws-efs-csi-driver#898]
Could we please update the k8s versions here:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/go.mod#L12-L17

Also, can we please make sure we use the same version we seem to be mixing v0.22.3 and 0.24.3 for example.

While we are doing that, can update the version version of golang to 1.19.x?
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/Dockerfile#L15

**Comment by mskanth972** [comment]
Hi @dims, thanks for bringing here. We will work on it most probably in the coming release.

**Comment by mskanth972** [comment]
Bumped the k8s packages versions and golang version and released it. [PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1079)
/close
