### ISSUE TITLE
docs: Clarify Kubernetes version compatibility and beta status for v0.2.0

### ISSUE THREAD

**Issue by chadlwilson** [kubernetes-sigs/aws-efs-csi-driver#90]
/kind documentation

**What happened?**

The current `README` and `CHANGELOG` don't make clear 
- the Kubernetes version required for the recently released v0.2.0 version.
- whether the new `beta` status applies only to v0.2.0, or whether v0.1.0 is also considered stable enough to be `beta`.

Does v0.2.0 require Kubernetes 1.14? Is this the first release considered `beta`?

**What you expected to happen?**

I expect to see `v0.2.0` listed in the table of compatibility in addition to `v0.1.0` and `master` so readers know the cluster requirements for each version.

It might also be nice to add a column to say for each release its maturity phase, e.g `alpha` vs `beta`.

**Comment by leakingtapan** [comment]
Answered ur question as part of this PR: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/92 PTAL

**Comment by chadlwilson** [comment]
Perfect - thank you!
