### ISSUE TITLE
where is the link between a PVC and PV (and hence the EFS handle)

### ISSUE THREAD

**Issue by dszryan** [kubernetes-sigs/aws-efs-csi-driver#93]
/kind bug

not sure this is a bug or a gap.

when creating multiple EFS storages, you can provide their hanldes at a PV level.

but i fail to see where a PVC is attacted to a particular PV?
all the examples link a PVC to s storage class but not a PV??

your urgent help would be greatly appreciated

+RD

**Comment by wongma7** [comment]
Normally, kubernetes will automatically bind a PVC to any PV that satisfies the PVC's requirements.

But if you want to bind a PVC to a particular PV, you may make use of the `volumeName` or `claimRef` fields. This is not documented well officially, so please see the answers here https://stackoverflow.com/questions/34282704/can-a-pvc-be-bound-to-a-specific-pv for details.

**Comment by dszryan** [comment]
thank you !
