### ISSUE TITLE
Add VCP DNS requirements to Readme

### ISSUE THREAD

**Issue by aintbrokedontfix** [kubernetes-sigs/aws-efs-csi-driver#931]
**Is your feature request related to a problem?/Why is this needed**
The project's Readme should have a blurb about ensuring that the VPC has both DNS hostnames and DNS resolution enabled regardless of the type of EKS deployment (Public or Private). 

The requirement for DNS is document [here](https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html) but, in the context of EC2. 

/feature

**Comment by mskanth972** [comment]
@aintbrokedontfix, can you elaborate the issue?

**Comment by mskanth972** [comment]
Closing the issue as there is no reply. Please feel free to open if want to discuss further.
/close
