### ISSUE TITLE
API v1beta1 no longer supported in kubernetes 1.22

### ISSUE THREAD

**Issue by jesartea** [kubernetes-sigs/aws-efs-csi-driver#959]
/kind bug

**What happened?**

When attempting to run:

 `kubectl apply -k /deploy/kubernetes/overlays/stable/ecr/`

it throws the following error:

no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"

I believe this to be caused by the kubernetes version 1.22, that no longer supports APIs v1beta1

**What you expected to happen?**

The template should be applied without issues

**Environment**
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.17-eks-48e63af", GitCommit:"47b89ea2caa1f7958bc6539d6865820c86b4bf60", GitTreeState:"clean", BuildDate:"2023-01-24T09:34:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mskanth972** [comment]
Hi @jesartea, we merged this [PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1193/files) which updates the apiversion.
