### ISSUE TITLE
--set useFips=true flag not working

### ISSUE THREAD

**Issue by zac-t-GGBAE** [kubernetes-sigs/aws-efs-csi-driver#971]
/kind bug

**What happened?**
 helm upgrade --set useFips=true --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver is still hitting the default https://elasticfilesystem.<REGION>.amazonaws.com/2015-02-01/file-systems?FileSystemId=<REDACTED> endpoint instead of the https://elasticfilesystem-fips.<REGION>.amazonaws.com/2015-02-01/file-systems?FileSystemId=<REDACTED> endpoint.

**What you expected to happen?**
That the helm upgrade command with the --set useFips=true flag would hit the https://elasticfilesystem-fips.<REGION>.amazonaws.com/2015-02-01/file-systems?FileSystemId=<REDACTED> endpoint

**How to reproduce it (as minimally and precisely as possible)?**
Proceed with the installation instructions through helm and then start up the system with helm upgrade --set useFips=true --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-drive

**Anything else we need to know?**:
You'll see that the error shown is that there was a certificate error, but this is because its using the wrong endpoint, that error won't occur if it uses the elasticfilesystem-fips endpoint. The issue here is that starting up the system with the fips flag isn't making it use the fips endpoint. 

$ helm upgrade --set useFips=true --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver
Release "aws-efs-csi-driver" does not exist. Installing it now.
NAME: aws-efs-csi-driver
LAST DEPLOYED: Fri Mar 17 21:24:14 2023
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To verify that aws-efs-csi-driver has started, run:

    kubectl get pod -n kube-system -l "app.kubernetes.io/name=aws-efs-csi-driver,app.kubernetes.io/instance=aws-efs-csi-driver"

**Environment**
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16+rke2r1", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T22:12:37Z", GoVersion:"go1.19.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16+rke2r1", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T22:12:37Z", GoVersion:"go1.19.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}

NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                           APP VERSION
aws-efs-csi-driver      kube-system     1               2023-03-17 21:24:14.364574623 +0000 UTC deployed        aws-efs-csi-driver-2.4.1                        1.5.4

Running pods associated with efs-ci:
efs-csi-controller-f69d4b896-4fv8w                      3/3     Running     0          20m
efs-csi-controller-f69d4b896-vn7zl                      3/3     Running     0          20m
efs-csi-node-59rrt                                      3/3     Running     0          20m
efs-csi-node-62kvh                                      3/3     Running     0          20m
efs-csi-node-n9cwt                                      3/3     Running     0          20m
efs-csi-node-wf2x7                                      3/3     Running     0          20m
efs-csi-node-z62fr                                      3/3     Running     0          20m

**Please also attach debug logs to help us better diagnose**
$ kubectl logs pod/efs-csi-controller-f69d4b896-vn7zl -n kube-system -c efs-plugin
File System failed: RequestError: send request failed
caused by: Get "https://elasticfilesystem.<REGION>.amazonaws.com/2015-02-01/file-systems?FileSystemId=<REDACTED>": x509: certificate signed by unknown authority
E0317 21:43:37.141363       1 driver.go:103] GRPC error: rpc error: code = Internal desc = Failed to fetch File System info: Describe File System failed: RequestError: send request failed
caused by: Get "https://elasticfilesystem.<REGION>.amazonaws.com/2015-02-01/file-systems?FileSystemId=<REDACTED>": x509: certificate signed by unknown authority

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by repl-dheeraj-v** [comment]
> /kind bug
> 
> **What happened?** helm upgrade --set useFips=true --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver is still hitting the default https://elasticfilesystem..amazonaws.com/2015-02-01/file-systems?FileSystemId= endpoint instead of the https://elasticfilesystem-fips..amazonaws.com/2015-02-01/file-systems?FileSystemId= endpoint.
> 
> **What you expected to happen?** That the helm upgrade command with the --set useFips=true flag would hit the https://elasticfilesystem-fips..amazonaws.com/2015-02-01/file-systems?FileSystemId= endpoint
> 
> **How to reproduce it (as minimally and precisely as possible)?** Proceed with the installation instructions through helm and then start up the system with helm upgrade --set useFips=true --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-drive
> 
> **Anything else we need to know?**: You'll see that the error shown is that there was a certificate error, but this is because its using the wrong endpoint, that error won't occur if it uses the elasticfilesystem-fips endpoint. The issue here is that starting up the system with the fips flag isn't making it use the fips endpoint.
> 
> $ helm upgrade --set useFips=true --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver Release "aws-efs-csi-driver" does not exist. Installing it now. NAME: aws-efs-csi-driver LAST DEPLOYED: Fri Mar 17 21:24:14 2023 NAMESPACE: kube-system STATUS: deployed REVISION: 1 TEST SUITE: None NOTES: To verify that aws-efs-csi-driver has started, run:
> 
> ```
> kubectl get pod -n kube-system -l "app.kubernetes.io/name=aws-efs-csi-driver,app.kubernetes.io/instance=aws-efs-csi-driver"
> ```
> 
> **Environment** $ kubectl version Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16+rke2r1", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T22:12:37Z", GoVersion:"go1.19.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16+rke2r1", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T22:12:37Z", GoVersion:"go1.19.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
> 
> $ helm version version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}
> 
> NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION aws-efs-csi-driver kube-system 1 2023-03-17 21:24:14.364574623 +0000 UTC deployed aws-efs-csi-driver-2.4.1 1.5.4
> 
> Running pods associated with efs-ci: efs-csi-controller-f69d4b896-4fv8w 3/3 Running 0 20m efs-csi-controller-f69d4b896-vn7zl 3/3 Running 0 20m efs-csi-node-59rrt 3/3 Running 0 20m efs-csi-node-62kvh 3/3 Running 0 20m efs-csi-node-n9cwt 3/3 Running 0 20m efs-csi-node-wf2x7 3/3 Running 0 20m efs-csi-node-z62fr 3/3 Running 0 20m
> 
> **Please also attach debug logs to help us better diagnose** $ kubectl logs pod/efs-csi-controller-f69d4b896-vn7zl -n kube-system -c efs-plugin File System failed: RequestError: send request failed caused by: Get "https://elasticfilesystem..amazonaws.com/2015-02-01/file-systems?FileSystemId=": x509: certificate signed by unknown authority E0317 21:43:37.141363 1 driver.go:103] GRPC error: rpc error: code = Internal desc = Failed to fetch File System info: Describe File System failed: RequestError: send request failed caused by: Get "https://elasticfilesystem..amazonaws.com/2015-02-01/file-systems?FileSystemId=": x509: certificate signed by unknown authority
> 
> * Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

The flag should be `--set useFIPS=true`, and not `--set useFips=true` the readme is incorrect in terms of case
