### ISSUE TITLE
Allow custom ClusterRole name instead of efs-csi-external-provisioner-role

### ISSUE THREAD

**Issue by solomonraj-a-presidio** [kubernetes-sigs/aws-efs-csi-driver#975]
I want to test the efs-csi driver in a cluster that already has the efs-csi driver installed, the fullnameoverride does nothing because the ClusterRole name is hardcoded in the yaml files as efs-csi-external-provisioner-role

/feature
allow the ClusterRole and ClusterRoleBinding to have a custom name

**Comment by Ashley-wenyizha** [comment]
hi @solomonraj-a-presidio 

Thanks for reaching out to use, could you add more details about your use case for this feature? 

Thanks

**Comment by ferasawadi** [comment]
am trying to install the driver in multiple namespaces. but am getting an error 
│ Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "efs-csi-external-provisioner-role" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "[meta.helm.sh/release-name](http://meta.helm.sh/release-name)" must equal "oneday-efs-csi-driver-prod": current value is "be-gentle-efs-csi-driver-prod"; annotation validation error: key "[meta.helm.sh/release-namespace](http://meta.helm.sh/release-namespace)" must equal "new-customer-apps-prod": current value is "be-gentle-apps-prod"
