### ISSUE TITLE
ArtifactHub Security Report is a D

### ISSUE THREAD

**Issue by flickerfly** [kubernetes-sigs/aws-efs-csi-driver#977]
/kind bug

**What happened?**

I went to https://artifacthub.io/packages/helm/aws-efs-csi-driver/aws-efs-csi-driver?modal=security-report and found a report that there are several High level vulnerabilities in the containers for this. 

**What you expected to happen?**

I was hoping to see 0 fixable high vulnerabilities.

**How to reproduce it (as minimally and precisely as possible)?**

Go to https://artifacthub.io/packages/helm/aws-efs-csi-driver/aws-efs-csi-driver?modal=security-report and observe.

**Anything else we need to know?**:

Seems to largely be related to dependencies that I assume can just be updated.

**Environment**
- Kubernetes version (use `kubectl version`): N/A
- Driver version: 1.5.4

**Comment by mskanth972** [comment]
Hi @flickerfly, the latest version v1.5.5 has the side cars bumped to the latest version which is able to mitigate the CVEs
