### ISSUE TITLE
How to use Single EFS with EKS on multiple namespace 

### ISSUE THREAD

**Issue by narayan-nes** [kubernetes-sigs/aws-efs-csi-driver#982]
How to use Single EFS with EKS on multiple namespaces using with and without dynamic provisioning ?
Do we need different access point for each namespace ?

/triage support

**Comment by Ashley-wenyizha** [comment]
Hi @narayan-nes 

We currently do not support this feature, what is your use case? We'd happy to know more of your use case and add it to our Road Map if this can benefit more csi-driver customers.

thanks

**Comment by narayan-nes** [comment]
@Ashley-wenyizha 

How we can leverage Single EFS Cluster with Single/Multiple EKS on multiple namespaces ?

**Comment by RyanStan** [comment]
Hi @narayan-nes,

Are you referring to Kubernetes namespaces? 

You can use the aws-efs-csi-driver to mount an EFS filesystem onto Pods, regardless of the Kubernetes namespace which those Pods are placed in.  This assumes that the Persistent Volume Claim is also in the same namespace as the Pod that is referencing the PVC.

If that's not what you're asking, then more clarification or a specific use case would help us understand.
