### ISSUE TITLE
Flaky test: pull-aws-efs-csi-driver-external-test-eks - Failed to create cluster

### ISSUE THREAD

**Issue by adammw** [kubernetes-sigs/aws-efs-csi-driver#990]
/kind bug

Test flake: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-efs-csi-driver/988/pull-aws-efs-csi-driver-external-test-eks/1654115195150143488

Failed to create an EKS cluster to test against from some CloudFormation error (not shown).

**Comment by Ashley-wenyizha** [comment]
Hi @adammw 

Thanks for reaching out and the new feature PR. We have checked in the fix yesterday and merged in mainline, test `
pull-aws-efs-csi-driver-external-test-eks`in PR 988 looking good now. 

Closing this issue.

thanks
