### ISSUE TITLE
EFS CSI Driver GitHub Readme Suggestion

### ISSUE THREAD

**Issue by pgasca** [kubernetes-sigs/aws-efs-csi-driver#998]
/kind bug

**What happened?**
From zprajwal (submitting this for him on his behalf, please contact him for more information):
"I had a customer on the Case ID 12237613911 who was facing a permission denied error while attempting to delete the PV which in turn deletes the File System Access Point.

The root cause of this error was that the file system access policy did not provide elasticfilesystem:ClientRootAccess.

The customer mentioned that he was referring to this [Github link](https://github.com/kubernetes-sigs/aws-efs-csi-driver). They have raised a request where if we can mention this as a necessary permission for the file system access policy in the readme document, it would be helpful for the customers."

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by mskanth972** [comment]
Hi @pgasca, thanks for bringing here, we will take a look into this.

**Comment by mskanth972** [comment]
Updated the README with this [PR](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1004)

**Comment by mskanth972** [comment]
Closing the issue as it is solved
/close
